- libraries/core-react/src/SideSheet/SideSheet.test.jsx
Removed this test which keeps generating a snapshat with "undefined" value.
> Removed false positive test

- apps/storybook-react/stories/Slider.stories.jsx
- libraries/core-react/src/Slider/Slider.jsx
- libraries/core-react/src/Slider/Slider.test.jsx
- libraries/core-react/src/Slider/SliderInput.jsx
> Add committed change for sliders

- libraries/core-react/src/SelectionControls/Switch/Input.jsx
- libraries/core-react/src/SelectionControls/Switch/SwitchDefault.jsx
- libraries/core-react/src/SelectionControls/Switch/SwitchSmall.jsx
- libraries/core-react/src/Snackbar/Snackbar.jsx
> Fix eslint issues

- libraries/core-react/azure-pipelines.yml
Minimal setup that runs tests and eslint. Runs automatically for pull requests, the comment triggers were just for testing. I’ve commented out the tests that are failing, will create a separate issue for those. There are some eslint errors that someone is looking into at the moment. 
resolves #302 
resolves #185
> Add test pipeline for react components

- apps/storybook-react/package.json
- libraries/core-react/CHANGELOG.md
- libraries/core-react/package.json
Correct version should be 0.4.0 since we have new components
> Change eds-core-react version from v0.3.2 to v0.4.0

- apps/storybook-react/stories/Table.stories.jsx
- apps/storybook-react/stories/Tooltip.stories.jsx
- libraries/core-react/src/Tooltip/Tooltip.jsx
Tooltip no longer move content if content is smaller than tooltip, as well as tooltip content doesn't wrap
> Tooltip wrap bug

- apps/storybook-react/stories/SelectionControls.Switch.stories.jsx
- apps/storybook-react/stories/SideSheet.stories.jsx
- apps/storybook-react/stories/Slider.stories.jsx
- apps/storybook-react/stories/Snackbar.stories.jsx
- apps/storybook-react/stories/TableOfContents.stories.jsx
- apps/storybook-react/stories/Tabs.stories.jsx
Fixed linting errors for: Switch, Slider, SideSheet, Snackbar, Table of Contents, Table
> Linting bugfix - Switch --- Table Components

- apps/storybook-react/.eslintrc.yaml
- apps/storybook-react/stories/Icon.stories.jsx
- apps/storybook-react/stories/Popover.stories.jsx
- apps/storybook-react/stories/Progress Indicators/Dots.stories.jsx
- apps/storybook-react/stories/Progress Indicators/Star.stories.jsx
- apps/storybook-react/stories/Scrim.stories.jsx
- apps/storybook-react/stories/Search.stories.jsx
- apps/storybook-react/stories/SelectionControls.Checkbox.stories.jsx
- apps/storybook-react/stories/SelectionControls.Radio.stories.jsx
> Fix eslint errors for Radio component

- libraries/core-react/src/SelectionControls/Switch/Input.jsx
- libraries/core-react/src/SelectionControls/Switch/Switch.tokens.js
- libraries/core-react/src/SelectionControls/Switch/SwitchSmall.jsx
Color change solves confusion between on/off states on the small switch
> Small Switch off state color change

- libraries/core-react/src/Breadcrumbs/Breadcrumb.jsx
- libraries/core-react/src/Breadcrumbs/Breadcrumbs.jsx
- libraries/core-react/src/Card/Card.test.jsx
- libraries/core-react/src/TopBar/TopBar.test.jsx
A couple of new errors showed up after merging #385 into the storefront branch.
These must be fixed before merging the storefront branch into develop.
resolves #418
> Fix new eslint errors

- apps/storybook-react/stories/Card.stories.jsx
- apps/storybook-react/stories/SelectionControls.Checkbox.stories.jsx
- apps/storybook-react/stories/SelectionControls.Radio.stories.jsx
- apps/storybook-react/stories/Slider.stories.jsx
> Fixed jsx-a11y linting errors in Storybook

- apps/storybook-react/stories/Typography.stories.jsx
- libraries/core-react/src/Icon/Icon.jsx
- libraries/core-react/src/Typography/Typography.jsx
* `Icon` now has `currentColor` as default color/fill
* Expanded `Typography` to also accept any string value for color in addition to pre-selected color "group"
> Icon & Typography tweaks

- apps/storybook-react/package.json
- libraries/core-react/CHANGELOG.md
- libraries/core-react/package.json
- libraries/core-react/pnpm-lock.yaml
- libraries/core-react/rollup.config.js
- libraries/core-react/src/Accordion/Accordion.jsx
- libraries/core-react/src/Tabs/Tabs.jsx
> Prepare release of EDS Core@0.5.0

- libraries/core-react/src/Button/Button.jsx
> Fix file upload and link buttons

- apps/storefront/docs/components/buttons/overview.mdx
- apps/storefront/src/components/ComponentStatus/ComponentStatus.jsx
- apps/storefront/src/components/HeroBanner.jsx
- Fix margin but on front page
- Increase font size in component status table
- Remove fixed width on link button example
> Minor Storefront fixes

- apps/storefront-docz/src/components/figmaImage.jsx
> Fix missing lookbehind support in Safari

- apps/figma-broker/Dockerfile
- apps/storybook-react/Dockerfile.dev
> Bump node version in Dockerfiles

- apps/storefront/src/components/figmaImage.jsx
> Fix for missing lookbehind support in Safari

- apps/storefront/docs/patterns/data-visualisation/data-visualisation.mdx
- apps/storefront/docs/updates/release-information/changelog.mdx
Two files got lost between the old and the new storefront. Let’s merge them into develop and get them out into the world.
> Move updated files from old documentation branch

- apps/storefront/docs/updates/release-information/changelog.mdx
Redirect error due to missing route field in frontmatter
> add route and meta-title to changelog

- apps/storybook-react/stories/Button.stories.jsx
The size prop isn't supported inside buttons yet so this code was removed to avoid confusion
> Removed size prop in Button Icon Story

- libraries/core-react/src/Tabs/Tabs.tokens.js
> React Tabs, fix background color

- libraries/core-react/src/Dialog/Dialog.tokens.js
> Fix Dialog elevation color

- apps/storefront/src/data/component-status/component-status.yaml
- apps/storybook-react/package.json
- libraries/core-react/CHANGELOG.md
- libraries/core-react/README.md
- libraries/core-react/package.json
- libraries/tokens/CHANGELOG.md
- libraries/tokens/base/colors.js
- libraries/tokens/package.json
- libraries/tokens/tokens.css
> Release core-react v0.6.0 & tokens v0.4.0

- apps/storefront/src/data/component-status/component-status.yaml
> Updated status for components on Storefront

- libraries/core-react/src/Menu/MenuItem.jsx
- libraries/core-react/src/Menu/MenuList.jsx
* Fixed focus being displayed onClick on MenuItems
* Fixed index not being applied to children when being provided from a fragment
* Found new bug with keyboard navigation #604 
fixes #544
> Fixed focus on menuItem when open

- libraries/core-react/src/Divider/Divider.jsx
- libraries/core-react/src/Popover/PopoverTitle.jsx
> Divider width 100%

- README.md
- package.yaml
> 📝  How to run docs

- libraries/core-react/src/Banner/BannerActions.jsx
> 🐛 fix missing props spread on BannerActions

- README.md
- apps/storefront/docs/patterns/grid-alignment/grid-alignment.mdx
- apps/storefront/docs/patterns/placement-and-order/placement-and-order.mdx
- apps/storefront/docs/patterns/spacings/spacings.mdx
- libraries/core-react/src/Banner/BannerActions.jsx
- libraries/core-react/src/Card/CardMedia.jsx
- package.yaml
Resolve #632  
Added pages as `draft`
> 📝  Add pages for spacings, placement and order and grid alignment

- libraries/core-react/src/Pagination/Pagination.jsx
> Fix pagination bug

- libraries/core-react/src/Button/Button.tsx
> Make button great again

- .eslintrc.js
- libraries/core-react/azure-pipelines.yml
> Fix linting and tests in typescript branch

- libraries/tokens/package.json
- libraries/tokens/rollup.config.js
- libraries/tokens/tsconfig.json
> Typescript declarations for eds-tokens

- libraries/icons/package.json
- libraries/icons/rollup.config.js
- libraries/icons/tsconfig.json
> Typescript declarations for eds-icons

- libraries/core-react/src/Card/CardMedia.tsx
> Clean up spacings in CardMedia

- apps/storybook-react/stories/Divider.stories.tsx
- libraries/core-react/src/index.ts
Forgot an export, and the story was missing args for some reason
> 🐛 Fix divider story

- apps/figma-broker/README.md
- package.yaml
Missing information about updating images etc.
> Update Figma-broker documentation

- libraries/core-react/src/Chip/Chip.tsx
- libraries/core-react/src/Divider/Divider.tokens.ts
- libraries/core-react/src/Divider/Divider.tsx
- libraries/core-react/src/Search/Search.test.tsx
- libraries/core-react/src/Search/Search.tsx
- libraries/core-react/src/SelectionControls/Checkbox/Checkbox.tokens.ts
- libraries/core-react/src/Tabs/TabList.tsx
- libraries/core-react/src/Typography/Typography.tsx
- pnpm-lock.yaml
> 🚨 Fix TS warnings

- apps/storybook-react/stories/Menu.stories.tsx
- libraries/core-react/src/Menu/MenuItem.tsx
> 🚨 Fix Menu warnings

- libraries/tokens/base/colors.ts
- libraries/tokens/base/typography.ts
- libraries/tokens/elements.css
- libraries/tokens/tokens.css
resolves #824
Ran tokens update before working on theming.
* Updated typography line height
* Updated snackbar color
> 🍱  Updated base tokens with latest changes

- apps/figma-broker/files/design-tokens/index.js
- apps/figma-broker/files/design-tokens/interactions.js
- apps/figma-broker/transformers/index.js
- libraries/tokens/base/index.ts
- libraries/tokens/base/interactions.ts
Added `interactions` base token from [Figma](https://www.figma.com/file/0TbIXrrObWj80Cf7KucKYFL0/Design-Tokens?node-id=2%3A12)
> ✨ Added interactions base token

- apps/storefront/docs/guidelines/spacing/overview.mdx
- apps/storefront/gatsby-config.js
- apps/storefront/src/data/component-status/component-status.yaml
- apps/storefront/src/gatsby-theme-docz/base/Seo.js
- apps/storefront/src/gatsby-theme-docz/components/Layout/index.js
- apps/storefront/src/gatsby-theme-docz/wrapper.js
> a11y issues with Storefront

- libraries/core-react/src/components/Tooltip/Tooltip.tsx
> Don't show Tooltip if title is empty

- apps/storefront/docs/components/select/overview.mdx
- apps/storefront/docs/components/select/usage.mdx
- apps/storefront/src/gatsby-theme-docz/wrapper.js
> Page for Select documentation

- apps/storybook-react/package.json
- apps/storybook-react/pnpm-lock.yaml
- apps/storybook-react/stories/Select/MultiSelect.stories.tsx
- apps/storybook-react/stories/Select/SingleSelect.stories.tsx
- apps/storybook-react/stories/Select/data.ts
- apps/storybook-react/stories/TextField.stories.tsx
- libraries/core-react/package.json
- libraries/core-react/pnpm-lock.yaml
- libraries/core-react/src/components/Label/Label.tokens.ts
- libraries/core-react/src/components/Label/Label.tsx
- libraries/core-react/src/components/Select/MultiSelect/MultiSelect.test.tsx
- libraries/core-react/src/components/Select/MultiSelect/MultiSelect.tsx
- libraries/core-react/src/components/Select/MultiSelect/index.ts
- libraries/core-react/src/components/Select/NativeSelect/NativeSelect.test.tsx
- libraries/core-react/src/components/Select/NativeSelect/Select/Select.tokens.ts
- libraries/core-react/src/components/Select/NativeSelect/Select/Select.tsx
- libraries/core-react/src/components/Select/Select.tokens.ts
- libraries/core-react/src/components/Select/SingleSelect/SingleSelect.test.tsx
- libraries/core-react/src/components/Select/SingleSelect/SingleSelect.tokens.ts
- libraries/core-react/src/components/Select/SingleSelect/SingleSelect.tsx
- libraries/core-react/src/components/Select/SingleSelect/index.ts
- libraries/core-react/src/components/Select/commonStyles.ts
- libraries/core-react/src/components/Select/index.ts
- libraries/core-react/src/components/SelectionControls/Checkbox/Checkbox.tsx
- libraries/core-react/src/components/SelectionControls/Checkbox/Input.tsx
- libraries/core-react/src/components/TextField/Input/Input.tokens.ts
- libraries/core-react/src/components/TextField/Input/Input.tsx
> Single and Multi select

- apps/storybook-react/stories/Chips.stories.tsx
- libraries/core-react/src/components/Chip/Chip.test.tsx
- libraries/core-react/src/components/Chip/Chip.tsx
- libraries/core-react/src/components/Icon/Icon.test.tsx
- libraries/core-react/src/components/Icon/Icon.tsx
> Fix chip spacing issues

- libraries/core-react/src/components/Button/Button.tsx
- libraries/core-react/src/components/Button/tokens/icon.ts
> 🐛 Fixed icon button horizontal clickbound

- libraries/core-react/CHANGELOG.md
- libraries/core-react/README.md
- libraries/core-react/package.json
Part of #965 
- `SingeSelect` component ([#896](https://github.com/equinor/design-system/issues/896))
- `MultiSelect` component ([#897](https://github.com/equinor/design-system/issues/897))
- Hover size on ghost buttons ([#595](https://github.com/equinor/design-system/issues/595))
- Fix wrong spacings inside `Chip` causing the content to not be proper centered ([#956](https://github.com/equinor/design-system/issues/956))
- Use base tokens in `Button` component ([#831](https://github.com/equinor/design-system/issues/831))
- Use base tokens in `Table` component ([#830](https://github.com/equinor/design-system/issues/830))
- Support for React 17 ([#813](https://github.com/equinor/design-system/issues/813))
- Update dependencies ([#904](https://github.com/equinor/design-system/issues/904))
> Release eds-core-react

- libraries/core-react/CHANGELOG.md
- libraries/core-react/package.json
- Removed unintended full width on `<Button>` ([#976](https://github.com/equinor/design-system/pull/976))
> Release eds-core-react@0.8.3

- apps/figma-broker/transformers/typography.js
- libraries/core-react/src/components/Table/Table.test.tsx
- libraries/tokens/base/typography.ts
- libraries/tokens/elements.css
- package.yaml
> Tests for table component

- apps/storybook-react/stories/Table.stories.tsx
- libraries/core-react/src/components/Table/Cell/DataCell.tsx
- libraries/core-react/src/components/Table/Cell/HeaderCell.tsx
- libraries/core-react/src/components/Table/Cell/index.tsx
- libraries/core-react/src/components/Table/Row.tsx
- libraries/core-react/src/components/Table/Table.test.tsx
- libraries/core-react/src/components/Table/Table.tsx
- libraries/core-react/src/components/Table/Table.types.ts
> Table: Hover & Error state on rows

- apps/storefront/docs/components/accordion/overview.mdx
- apps/storefront/docs/components/chips/overview.mdx
- apps/storefront/docs/components/divider/overview.mdx
- apps/storefront/docs/components/menu/overview.mdx
- apps/storefront/docs/components/navigation-app-launcher/overview.mdx
- apps/storefront/docs/components/navigation-breadcrumbs/overview.mdx
- apps/storefront/docs/components/navigation-navigation-drawer/overview.mdx
- apps/storefront/docs/components/navigation-pagination/overview.mdx
- apps/storefront/docs/components/notification-banner/overview.mdx
- apps/storefront/docs/components/notification-dialog/overview.mdx
- apps/storefront/docs/components/search/overview.mdx
- apps/storefront/docs/components/select/overview.mdx
- apps/storefront/docs/components/select/usage.mdx
- apps/storefront/docs/components/selection-controls/overview.mdx
- apps/storefront/docs/components/slider/overview.mdx
- apps/storefront/docs/components/table/overview.mdx
- apps/storefront/package.json
- apps/storefront/pnpm-lock.yaml
118 images updated 🤔 
Does this sound correct @equinor/eds-ux?
> 🚀 Deploy storefront

- apps/storybook-react/stories/Table.stories.tsx
- libraries/core-react/src/components/Table/Cell/DataCell.tokens.ts
- libraries/core-react/src/components/Table/Cell/DataCell.tsx
- libraries/core-react/src/components/Table/Cell/HeaderCell.tokens.ts
- libraries/core-react/src/components/Table/Cell/HeaderCell.tsx
- libraries/core-react/src/components/Table/Cell/utils.ts
- libraries/core-react/src/components/Table/Table.context.tsx
- libraries/core-react/src/components/Table/Table.test.tsx
- libraries/core-react/src/components/Table/Table.tsx
- libraries/core-react/src/components/Table/Table.types.ts
- libraries/core-react/src/components/Table/index.tsx
> ✨  Add compact table 

- apps/storybook-react/stories/Icon.stories.tsx
Solves #955 
Adding a selection of icons in the control solves crash when changing icon name in demo.
Did not include all Icons. Is it ok with only a selection or should we add all available EDS icons to this list?
> 📝 Updated Icon story with controls

- README.md
- apps/storefront/docs/getting-started/developers/introduction.mdx
- libraries/core-react/README.md
- libraries/icons/README.md
- libraries/tokens/README.md
> 📝  Document required TS version

- libraries/core-react/src/components/Table/Body.tsx
- libraries/core-react/src/components/Table/Cell/DataCell.tsx
- libraries/core-react/src/components/Table/Cell/HeaderCell.tsx
- libraries/core-react/src/components/Table/Head.tsx
- libraries/core-react/src/components/Table/Row.tsx
- libraries/core-react/src/components/Table/Table.tsx
> 🎨  Update Table to use forwardRef

- apps/storybook-react/stories/Table.stories.tsx
- libraries/core-react/src/components/Table/Cell/HeaderCell.tsx
- libraries/core-react/src/components/Table/Cell/index.tsx
- libraries/core-react/src/components/Table/Head.tsx
- libraries/core-react/src/components/Table/Inner.context.tsx
> ✨ Added sticky option for Table head

- apps/storybook-react/stories/DataTable.stories.tsx
- apps/storybook-react/stories/Table.stories.tsx
resolve #1027 
This is not actually code we want to document in the Table stories for end users and it also added a lot of code. That's why I created a new menu item called Playground. As this is just an exercise for us to find pain points, we don't actually have a good way of doing this 🤷‍♀️
> Verify input elements in compact table

- apps/storefront/Dockerfile
- apps/storefront/package.json
Npm installed an old version of pnpm in Docker. Added latest to version to fix it. Also bumped required version in package.json.
Resolves #999
> 🐛 Fix pnpm version

- apps/storybook-react/stories/Table.stories.tsx
- libraries/core-react/src/components/EdsProvider/eds.context.tsx
resolves #1042 
- Found an edge-case when using `EdsProvider` and changing values that was not being updated correctly which I fixed here
- Update existing "Compact table" story with `Topbar` and `Menu` for switching `density` on `Table`
> Compact table with density switcher

- libraries/core-react/src/components/Select/SingleSelect/SingleSelect.tsx
fixes #1064 with useEffect to update local state inputItems
> Fix SingleSelect rerender (equinor#1064)

- libraries/core-react/src/components/Menu/Menu.context.tsx
- libraries/core-react/src/components/Search/Search.tsx
- libraries/core-react/src/components/TextField/context.tsx
resolves #1062 
Fixed `useState` where objects are used for storing multiple values and updates are done to avoide race conditions because of `useState` async nature
> Use state improvements

- apps/storefront/docs/components/table/overview.mdx
> Update table example in storefront

- apps/storybook-react/stories/Table.stories.tsx
- libraries/core-react/src/components/EdsProvider/eds.context.tsx
- libraries/core-react/src/components/Table/Table.test.tsx
- libraries/core-react/src/components/Table/Table.tsx
This reverts commit 0b7cde244bcd7a271d27887f5beabdac0cf201a9.
> Revert "❌ Disabled density table functionality (#1069)"

- apps/figma-broker/files/design-tokens/interactions.js
- apps/figma-broker/files/design-tokens/shape.js
- libraries/tokens/base/colors.ts
- libraries/tokens/tokens.css
> Updated eds-tokens

- libraries/core-react/src/components/Progress/Circular/CircularProgress.tokens.ts
> ♻️ Updated circular progress to use new token

- libraries/core-react/CHANGELOG.md
- libraries/core-react/package.json
- libraries/tokens/CHANGELOG.md
- libraries/tokens/package.json
resolves #1122 
Added changelog & bumped version
Release logs: https://github.com/equinor/design-system/releases
> Release core-react & tokens

- apps/figma-broker/files/design-tokens/color.js
- libraries/core-react/src/components/Card/Card.test.tsx
- libraries/tokens/base/colors.ts
> Add css variable to rgba value in tokens

- libraries/core-react/src/components/TextField/Icon/Icon.tsx
- libraries/core-react/src/components/TextField/TextField.test.tsx
- libraries/core-react/stories/components/TextField.stories.tsx
>  ♻️  Update TextField  to use EDS Icon component

- libraries/core-react/src/components/TextField/TextField.tsx
> 🐛 Fixed disabled label styling in Textfield

- libraries/core-react/CHANGELOG.md
- libraries/core-react/package.json
- libraries/tokens/CHANGELOG.md
- libraries/tokens/package.json
> 📝  Release eds-core-react and eds-tokens

- libraries/core-react/stories/components/Popover.stories.tsx
> Popover hover example improved

- libraries/core-react/src/components/Banner/Banner.tsx
Alert was most fitting as it's a notification banner
Resolves #1178
> ♿️  Added role to Banner

- libraries/core-react/src/components/Menu/Menu.tsx
- libraries/core-react/src/components/Popover/Popover.tsx
- libraries/core-react/src/components/Scrim/Scrim.tsx
- libraries/core-react/src/hooks/index.ts
- libraries/core-react/src/hooks/useEscapePress.ts
- libraries/core-react/src/hooks/useGlobalKeyPress.ts
- libraries/core-react/stories/components/Menu.stories.tsx
- libraries/core-react/stories/components/Popover.stories.tsx
> Conform close logic with 'Escape' key

- libraries/core-react/src/components/Menu/Menu.tsx
- libraries/core-react/src/components/Menu/index.tsx
- libraries/core-react/src/hooks/useGlobalKeyPress.ts
- libraries/core-react/src/hooks/useOutsideClick.ts
- libraries/core-react/stories/components/Menu.stories.tsx
resolves #1164 
* Fixed missing props table for menu
* Removed some superfluous Menu stories
* Simplified remaining Menu stories so its easier to understand
* Fixed hooks when changes to parameters occur
> Fixed missing Menu props table in Storybook

- libraries/core-react/stories/components/Menu.stories.tsx
- libraries/core-react/stories/components/Popover.stories.tsx
- libraries/core-react/stories/components/Tooltip.stories.tsx
> ♻️ Story improvments for Menu, Popover & Tooltip

- libraries/core-react/src/components/Menu/Menu.tsx
- libraries/core-react/src/components/Popover/Popover.tsx
- libraries/core-react/src/components/Tooltip/Tooltip.tsx
> ♻️ Optional & nullable anchorEl

- libraries/core-react/src/components/Banner/BannerActions.tsx
- libraries/core-react/stories/components/Banner.stories.tsx
> ♻️ Clarified use of Banner.Actions in story

- .github/workflows/checks.yaml
- .github/workflows/publish_core_react.yaml
- .github/workflows/publish_icons.yaml
- .github/workflows/publish_storybook.yaml
- .github/workflows/publish_tokens.yaml
- apps/figma-broker/pnpm-lock.yaml
- apps/storefront/pnpm-lock.yaml
- libraries/core-react/pnpm-lock.yaml
- libraries/icons/pnpm-lock.yaml
- libraries/tokens/pnpm-lock.yaml
- pnpm-lock.yaml
> 👷🏻Actions pnpm v6 update

- libraries/core-react/stories/components/Popover.stories.tsx
> 🐛  Remove Card.Actions from Popover story

- libraries/core-react/src/components/Menu/Menu.tsx
> 🐛 Fix wrong offset Menu

- .eslintrc.js
- apps/figma-broker/transformers/jsonToSass.js
- apps/figma-broker/transformers/jsonToSassClass.js
- libraries/core-react/src/components/Button/Button.tsx
- libraries/core-react/src/components/Chip/Chip.tsx
- libraries/core-react/src/components/EdsProvider/eds.context.tsx
- libraries/core-react/src/components/Popover/Popover.tsx
- libraries/core-react/src/components/Progress/Linear/LinearProgress.tsx
- libraries/core-react/src/components/TextField/InputWrapper.tsx
- libraries/core-react/src/hooks/usePopper.ts
- libraries/core-react/src/utils/test/withAnchorEl.tsx
- libraries/core-react/stories/components/Avatar.stories.tsx
- libraries/core-react/stories/components/DataTable.stories.tsx
- libraries/core-react/stories/components/Menu.stories.tsx
- libraries/core-react/stories/components/Popover.stories.tsx
- libraries/core-react/stories/components/Table.stories.tsx
- libraries/core-react/stories/components/TopBar.stories.tsx
- package.yaml
- pnpm-lock.yaml
- tsconfig.eslint.json
Cleaned up eslint and fixed some linting errors. 
Was not able to fix issue #1187, but cleared up and disabled the rules which leads to these "wrong" warnings.
> 🚨 Clean up eslint rules and plugins

- libraries/core-react/src/components/Breadcrumbs/Breadcrumb.tsx
- libraries/core-react/src/components/Breadcrumbs/Breadcrumbs.tokens.ts
- libraries/core-react/src/components/Breadcrumbs/Breadcrumbs.tsx
- libraries/core-react/src/components/Typography/Typography.test.tsx
- libraries/core-react/src/components/Typography/Typography.tokens.ts
- libraries/core-react/src/components/Typography/Typography.tsx
- libraries/core-react/stories/components/Breadcrumbs.stories.tsx
- libraries/core-react/stories/components/Typography.stories.tsx
> Typography link focus

- libraries/core-react/src/components/Button/tokens/button.ts
> 🐛 fixed button outline offset

- libraries/core-react/CHANGELOG.md
- libraries/core-react/package.json
> 📝  Release eds-core-react

- libraries/core-react/src/components/Menu/Menu.tsx
- libraries/core-react/src/components/Popover/Popover.tsx
- libraries/core-react/src/components/Tooltip/Tooltip.tsx
- libraries/core-react/src/hooks/usePopper.ts
- libraries/core-react/stories/components/Popover.stories.tsx
> 🐛 Fixed decleration types does not support aliases

- libraries/core-react/CHANGELOG.md
- libraries/core-react/package.json
- libraries/core-react/src/components/Tooltip/Tooltip.tsx
> 🐛  Fixed Tooltip anchor to be mounted before using portal

- libraries/core-react/src/components/Accordion/index.ts
- libraries/core-react/src/components/Banner/index.ts
- libraries/core-react/src/components/Breadcrumbs/index.ts
- libraries/core-react/src/components/Card/index.ts
- libraries/core-react/src/components/Dialog/index.ts
- libraries/core-react/src/components/List/index.ts
- libraries/core-react/src/components/Menu/index.tsx
- libraries/core-react/src/components/Popover/index.ts
- libraries/core-react/src/components/Slider/Slider.tsx
- libraries/core-react/src/components/Table/index.tsx
- libraries/core-react/src/components/TableOfContents/index.ts
- libraries/core-react/src/components/Tabs/index.ts
- libraries/core-react/src/components/TopBar/index.tsx
> DisplayNames on compound components

- libraries/core-react/src/components/Slider/Slider.stories.tsx
Resolves #1238 
NB! Slider was the only story with component decorator
> 🐛  Storybook decorators disrupts code examples

- .eslintrc.js
- libraries/core-react/src/components/TopBar/Header.tsx
- libraries/core-react/src/components/TopBar/TopBar.test.tsx
- libraries/core-react/src/components/TopBar/TopBar.tokens.ts
- libraries/core-react/src/components/TopBar/TopBar.tsx
- libraries/tokens/src/types/borders.ts
- libraries/tokens/src/types/component.ts
> Conform token topbar

- libraries/core-react/src/components/Tooltip/Tooltip.tokens.ts
- libraries/core-react/src/components/Tooltip/Tooltip.tsx
- libraries/core-react/src/utils/templates/common.ts
resolves #1252 
before:
after:
> ♻️ Updated Tooltip tokens

- libraries/core-react/src/components/Paper/Paper.tokens.tsx
- libraries/core-react/src/components/Paper/Paper.tsx
> ♻️ Updated Paper tokens

- libraries/core-react/src/components/Pagination/Pagination.stories.tsx
- libraries/core-react/src/components/Pagination/Pagination.tokens.ts
- libraries/core-react/src/components/Pagination/Pagination.tsx
- libraries/core-react/src/components/Pagination/PaginationItem.tsx
> ♻️Updated Pagination tokens

- libraries/core-react/src/components/Scrim/Scrim.tokens.ts
> ♻️ Updated Scrim tokens

- libraries/core-react/src/components/Avatar/Avatar.test.tsx
- libraries/core-react/src/components/Avatar/Avatar.tokens.ts
- libraries/core-react/src/components/Avatar/Avatar.tsx
> ♻️ Update Avatar tokens

- libraries/core-react/src/components/Accordion/Accordion.tokens.ts
- libraries/core-react/src/components/Accordion/AccordionHeader.tsx
- libraries/core-react/src/components/Accordion/AccordionHeaderTitle.tsx
- libraries/core-react/src/components/Accordion/AccordionPanel.tsx
> ♻️ Updated Accordion tokens

- libraries/core-react/src/components/List/List.tokens.ts
> ♻️ Updated List tokens

- libraries/core-react/src/components/Label/Label.tokens.ts
- libraries/core-react/src/components/Label/Label.tsx
> ♻️ Updated Label tokens

- libraries/core-react/src/components/Paper/Paper.tokens.tsx
- libraries/core-react/src/components/Paper/Paper.tsx
- libraries/tokens/src/types/component.ts
> ♻️ Update ComponentToken type

- libraries/core-react/src/components/Menu/Menu.tokens.ts
- libraries/core-react/src/components/Menu/Menu.tsx
- libraries/core-react/src/components/Menu/MenuItem.tsx
- libraries/core-react/src/components/Menu/MenuSection.tsx
> ♻️ Update Menu token

- libraries/core-react/src/components/Dialog/Dialog.tokens.ts
- libraries/core-react/src/components/Divider/Divider.test.tsx
- libraries/core-react/src/components/Divider/Divider.tokens.ts
- libraries/core-react/src/components/Divider/Divider.tsx
> ♻️  Updated Divider tokens

- libraries/core-react/src/components/Snackbar/Snackbar.tokens.ts
- libraries/core-react/src/components/Snackbar/Snackbar.tsx
- libraries/core-react/src/components/Snackbar/SnackbarAction.tsx
> ♻️ Updated Snackbar tokens

- libraries/core-react/src/components/Popover/Popover.tokens.ts
- libraries/core-react/src/components/Popover/Popover.tsx
- libraries/core-react/src/components/Popover/PopoverTitle.tsx
- libraries/tokens/src/types/clickbound.ts
> ♻️ Conform Popover tokens

- libraries/core-react/src/components/TableOfContents/LinkItem.tsx
- libraries/core-react/src/components/TableOfContents/TableOfContents.tokens.ts
- libraries/core-react/src/components/TableOfContents/TableOfContents.tsx
> ♻️ Updated TOC tokens

- libraries/core-react/src/components/Tabs/Tab.tsx
- libraries/core-react/src/components/Tabs/TabPanel.tsx
- libraries/core-react/src/components/Tabs/TabPanels.tsx
- libraries/core-react/src/components/Tabs/Tabs.tokens.ts
- libraries/tokens/src/types/component.ts
> ♻️ Conform Tabs tokens

- libraries/core-react/src/components/Select/MultiSelect/MultiSelect.test.tsx
- libraries/core-react/src/components/Select/MultiSelect/MultiSelect.tsx
- libraries/core-react/src/components/Select/NativeSelect/NativeSelect.test.tsx
- libraries/core-react/src/components/Select/NativeSelect/Select/Select.tokens.ts
- libraries/core-react/src/components/Select/NativeSelect/Select/Select.tsx
- libraries/core-react/src/components/Select/Select.tokens.ts
- libraries/core-react/src/components/Select/SingleSelect/SingleSelect.test.tsx
- libraries/core-react/src/components/Select/SingleSelect/SingleSelect.tsx
- libraries/core-react/src/components/Select/commonStyles.ts
- libraries/core-react/src/components/Tabs/Tab.tsx
- libraries/core-react/src/components/Tabs/TabPanel.tsx
- libraries/core-react/src/components/Tabs/TabPanels.tsx
- libraries/core-react/src/components/Tabs/Tabs.tokens.ts
- libraries/tokens/src/types/component.ts
> Conform token select

- libraries/core-react/src/components/SideSheet/SideSheet.tokens.ts
- libraries/core-react/src/components/SideSheet/SideSheet.tsx
> ♻️ Updated Sidesheet tokens

- libraries/core-react/src/components/Tooltip/Tooltip.tsx
> 🐛 Check if title is set before opening

- libraries/core-react/src/components/Slider/MinMax.tsx
- libraries/core-react/src/components/Slider/Output.tsx
- libraries/core-react/src/components/Slider/Slider.tokens.ts
- libraries/core-react/src/components/Slider/Slider.tsx
- libraries/core-react/src/components/Slider/SliderInput.tsx
> ♻️ Updated Slider tokens

- libraries/core-react/src/components/Dialog/Actions.tsx
- libraries/core-react/src/components/Dialog/CustomContent.tsx
- libraries/core-react/src/components/Dialog/Dialog.tokens.ts
- libraries/core-react/src/components/Dialog/Dialog.tsx
- libraries/core-react/src/components/Dialog/Title.tsx
> ♻️ Updated Dialog tokens

- libraries/core-react/src/components/Input/Input.test.tsx
- libraries/core-react/src/components/Input/Input.tokens.ts
- libraries/core-react/src/components/Input/Input.tsx
- libraries/tokens/src/types/component.ts
> ♻️ Conform Input tokens

- libraries/core-react/src/components/Select/NativeSelect/Select/Select.tokens.ts
- libraries/core-react/src/components/Select/NativeSelect/Select/Select.tsx
> 🐛  NativeSelect border / focus bug

- libraries/core-react/CHANGELOG.md
- libraries/core-react/package.json
> eds-core react@0.11.0

- libraries/core-react/src/components/Avatar/Avatar.tokens.ts
- libraries/core-react/src/components/Banner/Banner.tokens.ts
- libraries/core-react/src/components/Button/tokens/button.ts
- libraries/core-react/src/components/Button/tokens/contained.ts
- libraries/core-react/src/components/Button/tokens/outlined.ts
- libraries/core-react/src/components/Card/Card.tokens.ts
- libraries/core-react/src/components/Chip/Chip.tokens.ts
- libraries/core-react/src/components/Popover/Popover.tokens.ts
- libraries/core-react/src/utils/templates/common.ts
- libraries/tokens/src/types/borders.ts
> 🐛 Fix missing border on Outlined Buttons

- libraries/tokens/CHANGELOG.md
- libraries/tokens/package.json
- Updates to internal types for tokens
> Release eds-tokens@0.5.8

- .eslintrc.js
- libraries/core-react/src/components/Progress/Circular/Circular.stories.tsx
- libraries/core-react/src/components/Progress/Linear/Linear.stories.tsx
- libraries/core-react/src/components/Progress/Star/Star.stories.tsx
- libraries/core-react/src/components/Slider/Slider.tsx
- libraries/core-react/src/components/Tabs/TabList.tsx
- libraries/core-react/src/stories/useMockProgress.ts
- package.yaml
- pnpm-lock.yaml
> 🚨 eslint hooks rules

- libraries/core-react/src/components/Popover/Popover.test.tsx
- libraries/core-react/src/components/Popover/Popover.tsx
> 🐛  Render Popover conditionally

- libraries/core-react/src/components/Menu/MenuItem.tsx
- libraries/core-react/src/components/Search/Search.tsx
- libraries/core-react/src/hooks/useCombinedRefs.ts
> ♻️ CombinedRefs update

- libraries/core-react/src/components/Input/Input.tsx
- libraries/core-react/src/components/TextField/Field.tsx
- libraries/core-react/src/components/TextField/InputWrapper.tsx
- libraries/core-react/src/components/TextField/TextField.tsx
- libraries/core-react/src/components/Textarea/Textarea.tsx
- libraries/core-react/src/components/Textarea/index.ts
- libraries/core-react/src/hooks/useAutoResize.ts
> Textarea component

- libraries/core-react/CHANGELOG.md
- libraries/core-react/package.json
> Release core react@0.12.0

- libraries/tokens/CHANGELOG.md
- libraries/tokens/base/typography.ts
- libraries/tokens/elements.css
- libraries/tokens/package.json
- libraries/tokens/tokens.css
> 🍱 Update tokens

- libraries/core-react/src/components/Accordion/Accordion.stories.tsx
- libraries/core-react/src/components/Accordion/Accordion.test.tsx
- libraries/core-react/src/components/Button/Button.stories.tsx
- libraries/core-react/src/components/Button/Button.test.tsx
- libraries/core-react/src/components/Button/Button.tsx
- libraries/core-react/src/components/Button/ButtonFullWidth.tsx
- libraries/core-react/src/components/Button/InnerFullWidth.tsx
> Split fullWidth Button and regular Button

- libraries/core-react/src/components/Button/Button.stories.tsx
- libraries/core-react/src/components/Button/InnerFullWidth.tsx
> Small Button fix

- libraries/core-react/src/components/Radio/Radio.stories.tsx
> 📝  Clarify Radio story

- libraries/core-react/CHANGELOG.md
- libraries/core-react/package.json
> Release eds-core-react@0.12.1

- apps/figma-broker/files/design-tokens/interactions.js
- apps/figma-broker/files/design-tokens/shape.js
- libraries/tokens/base/interactions.ts
- libraries/tokens/base/shape.ts
> Compact tokens figma broker

- libraries/core-react/src/components/Button/Button.stories.tsx
Resolves #1374 
It works in Storybook Canvas but not Storybook Docs (probably because of iframe?) so I just specified the story.
> File Upload Storybook bug

- libraries/core-react/src/components/Input/Input.stories.tsx
- libraries/core-react/src/components/Input/Input.tokens.ts
- libraries/core-react/src/components/Input/Input.tsx
- libraries/core-react/src/components/TextField/Field.tsx
- libraries/core-react/src/components/TextField/HelperText/HelperText.tsx
- libraries/core-react/src/components/TextField/TextField.stories.tsx
- libraries/core-react/src/components/TextField/TextField.tsx
- libraries/core-react/src/components/Textarea/Textarea.tsx
- libraries/core-react/src/index.ts
> Compact Textfield

- libraries/core-react/src/components/TopBar/TopBar.tokens.ts
> 🐛  Added missing border style to TopBar

- libraries/core-react/src/components/Button/Button.tsx
> 🐛  Justify Button content center

- libraries/core-react/src/components/Checkbox/Checkbox.tokens.ts
> 💄 Update compact Checkbox tokens

- libraries/core-react/src/components/Select/MultiSelect/MultiSelect.stories.tsx
- libraries/core-react/src/components/Select/MultiSelect/MultiSelect.tsx
- libraries/core-react/src/components/Select/Select.tokens.ts
- libraries/core-react/src/components/Select/SingleSelect/SingleSelect.stories.tsx
- libraries/core-react/src/components/Select/SingleSelect/SingleSelect.tsx
- libraries/core-react/src/components/Select/commonStyles.ts
- libraries/core-react/stories/playground/DataTable.stories.tsx
> ✨ Compact SingleSelect & MultiSelect

- libraries/core-react/src/components/Pagination/Pagination.tsx
> 🐛  Pagination unwanted onChange type 

- libraries/core-react/src/components/Button/Button.stories.tsx
- libraries/core-react/src/components/Button/Button.tsx
- libraries/core-react/src/components/Button/tokens/button.ts
- libraries/core-react/src/components/Button/tokens/icon.ts
> ✨ Compact button

- libraries/core-react/package.json
- libraries/core-react/pnpm-lock.yaml
- libraries/core-react/src/components/Checkbox/Checkbox.stories.tsx
- libraries/core-react/src/components/Select/MultiSelect/MultiSelect.stories.tsx
- libraries/core-react/src/components/Select/SingleSelect/SingleSelect.stories.tsx
- libraries/core-react/src/components/TextField/TextField.stories.tsx
> ⬆️  Upgrade react-hook-forms and update examples

- libraries/core-react/src/components/TextField/Field.tsx
> 🐛  Multiline TextField double box-shadow

- libraries/core-react/src/components/Switch/Switch.stories.tsx
- libraries/core-react/src/components/Switch/Switch.tsx
- libraries/core-react/src/stories/data.tsx
> Optional label on Switch

- libraries/core-react/src/components/Menu/Menu.stories.tsx
- libraries/core-react/src/components/Menu/Menu.tokens.ts
- libraries/core-react/src/components/Menu/Menu.tsx
- libraries/core-react/src/components/Menu/MenuItem.tsx
- libraries/core-react/src/components/Menu/MenuList.tsx
- libraries/core-react/stories/playground/DataTable.stories.tsx
> Compact Menu

- libraries/core-react/src/components/Checkbox/Checkbox.stories.tsx
Optional label was already done so I just updated the Storybook with an example
Resolves #1453
> Optional Label for Checkbox

- libraries/core-react/src/components/Radio/Radio.stories.tsx
- libraries/core-react/src/components/Radio/Radio.tsx
> Optional label Radio

- libraries/core-react/src/components/Button/Button.stories.tsx
- libraries/core-react/src/components/Button/Button.tsx
Resolves #1456 
~~Updated Storybook with an example of a workaround for disabled links~~
> Disabled Link Button

- libraries/core-react/src/components/Button/Button.tsx
> ♻️ Themeprovider in Button

- libraries/core-react/stories/playground/DataTable.stories.tsx
- libraries/core-react/stories/playground/Examples.stories.tsx
Added an examples page so we can test multiple components together...
> ✨ Examples page

- libraries/core-react/src/components/Select/MultiSelect/MultiSelect.tsx
- libraries/core-react/src/components/Select/NativeSelect/NativeSelect.tsx
- libraries/core-react/src/components/Select/SingleSelect/SingleSelect.tsx
> ThemeProvider in Select

- libraries/core-react/src/components/TextField/Field.tsx
- libraries/core-react/src/components/TextField/TextField.tokens.ts
- libraries/core-react/src/components/TextField/TextField.tsx
> ThemeProvider in TextField

- libraries/core-react/src/components/Checkbox/Checkbox.tsx
- libraries/core-react/src/components/Checkbox/Input.tsx
> ThemeProvider in Checkbox

- libraries/core-react/src/components/Input/Input.test.tsx
- libraries/core-react/src/components/Input/Input.tokens.ts
- libraries/core-react/src/components/Input/Input.tsx
- libraries/core-react/src/components/Textarea/Textarea.tsx
> ThemeProvider in Input

- libraries/core-react/src/components/Table/DataCell/DataCell.tokens.ts
- libraries/core-react/src/components/Table/HeaderCell/HeaderCell.tokens.ts
> ♻️ Reduced line-height in Compact Table 

- libraries/core-react/src/components/EdsProvider/eds.context.tsx
- libraries/core-react/src/components/Table/Table.stories.tsx
- libraries/core-react/src/components/Table/Table.test.tsx
- libraries/core-react/src/components/Table/Table.tsx
- libraries/core-react/src/components/Table/Table.types.ts
> 🔥  Remove internal EdsProvider in Table

- libraries/core-react/CHANGELOG.md
- libraries/core-react/package.json
- libraries/core-react/stories/playground/DataTable.tsx
- libraries/core-react/stories/playground/Examples.stories.tsx
> 🔖 Release core react@0.13.0

- libraries/core-react/src/components/Snackbar/Snackbar.test.tsx
- libraries/core-react/src/components/Snackbar/Snackbar.tsx
Resolves #1173, resolves #1172
> Stacking Snackbar

- libraries/core-react/src/components/Snackbar/Snackbar.tsx
> ♻️ Improve Snackbar timeout

- libraries/core-react/CHANGELOG.md
- libraries/core-react/package.json
> 🔖  Updated changelog & version for pre-release

- libraries/core-react/package.json
> 🔖  Release core react@0.13.1

- libraries/core-react/src/components/Popover/Popover.stories.tsx
- libraries/core-react/src/components/Popover/Popover.tsx
- libraries/core-react/src/components/Tooltip/Tooltip.tsx
> 🐛 Fixed using ref when inside Tooltip

- libraries/core-react/src/components/Select/MultiSelect/MultiSelect.tsx
- libraries/core-react/src/components/Select/SingleSelect/SingleSelect.tsx
> ✨ Open Select & MultiSelect on focus

- libraries/core-react/src/components/Select/MultiSelect/MultiSelect.tsx
- libraries/core-react/src/components/Select/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
- libraries/core-react/src/components/Select/Select.tokens.ts
- libraries/core-react/src/components/Select/SingleSelect/SingleSelect.tsx
- libraries/core-react/src/components/Select/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap
- libraries/core-react/src/components/Select/commonStyles.ts
> ✨ Select shows all items on reopen when an item is selected

- libraries/core-react/src/components/Select/NativeSelect/NativeSelect.tokens.ts
- libraries/core-react/src/components/Select/NativeSelect/__snapshots__/NativeSelect.test.tsx.snap
- libraries/core-react/src/components/Select/Select.tokens.ts
> 💄 Adjusted colors on Select compnents

- libraries/core-react/src/components/Select/MultiSelect/MultiSelect.tsx
- libraries/core-react/src/components/Select/SingleSelect/SingleSelect.tsx
> ✨ Select & MultiSelect "clear all" button

- libraries/core-react/src/components/Banner/Banner.tsx
- libraries/core-react/src/components/Banner/BannerActions.tsx
- libraries/core-react/src/components/Banner/BannerIcon.tsx
- libraries/core-react/src/components/Banner/BannerMessage.tsx
- libraries/core-react/src/components/Card/Card.tsx
- libraries/core-react/src/components/Card/CardActions.tsx
- libraries/core-react/src/components/Card/CardHeader.tsx
- libraries/core-react/src/components/Card/CardHeaderTitle.tsx
- libraries/core-react/src/components/Card/CardMedia.tsx
- libraries/core-react/src/components/Dialog/CustomContent.tsx
- libraries/core-react/src/components/Dialog/Title.tsx
- libraries/core-react/src/components/Pagination/Pagination.tsx
- libraries/core-react/src/components/Pagination/PaginationItem.tsx
- libraries/core-react/src/components/Popover/PopoverTitle.tsx
- libraries/core-react/src/components/SideSheet/SideSheet.tsx
- libraries/core-react/src/components/Snackbar/Snackbar.tsx
- libraries/core-react/src/components/Snackbar/SnackbarAction.tsx
- libraries/core-react/src/components/TableOfContents/LinkItem.tsx
- libraries/core-react/src/components/TableOfContents/TableOfContents.tsx
> Conform use of forwardRef and rest props

- libraries/core-react/src/components/Breadcrumbs/Breadcrumb.tsx
- libraries/core-react/src/components/Breadcrumbs/Breadcrumbs.stories.tsx
- libraries/core-react/src/components/Breadcrumbs/__snapshots__/Breadcrumbs.test.tsx.snap
> ♻️  Render breadcrumb as span when href is undefined

- libraries/core-react/src/components/Popover/Popover.tsx
> 🐛 Popover guard for onEscape

- apps/figma-broker/files/design-tokens/color.js
- apps/figma-broker/functions/utils.js
- libraries/core-react/src/components/Table/DataCell/DataCell.tokens.ts
- libraries/core-react/src/components/Table/DataCell/DataCell.tsx
- libraries/core-react/src/components/Table/HeaderCell/HeaderCell.tokens.ts
- libraries/core-react/src/components/Table/Table.test.tsx
- libraries/core-react/src/components/Table/Table.tsx
- libraries/tokens/base/typography.ts
>  ♻️ Update Table tokens with compact Typography tokens

- libraries/core-react/stories/playground/DataTable.tsx
- libraries/core-react/stories/playground/Examples.stories.tsx
> Fix a11y issues in example page

- libraries/core-react/src/components/Snackbar/Snackbar.stories.tsx
- libraries/core-react/src/components/Snackbar/Snackbar.test.tsx
- libraries/core-react/src/components/Snackbar/Snackbar.tsx
- libraries/core-react/src/components/Snackbar/__snapshots__/Snackbar.test.tsx.snap
> ✨ Snackbar placement

- libraries/core-react/src/components/TextField/Field.tsx
- libraries/core-react/src/components/TextField/TextField.context.tsx
> 🐛 TextField bugfix

- libraries/core-react/package.json
- libraries/core-react/pnpm-lock.yaml
- libraries/core-react/src/components/Combobox/Combobox.stories.tsx
- libraries/core-react/src/components/Combobox/Combobox.test.tsx
- libraries/core-react/src/components/Combobox/Combobox.tokens.ts
- libraries/core-react/src/components/Combobox/Combobox.tsx
- libraries/core-react/src/components/Combobox/__snapshots__/Combobox.test.tsx.snap
- libraries/core-react/src/components/Combobox/index.ts
- libraries/core-react/src/index.ts
> ✨ Combobox

- libraries/core-react/src/components/Radio/Radio.stories.tsx
Resolves #1566 
Known storybook issue https://github.com/storybookjs/storybook/issues/15282
Removing `<code>` in story fixed it.
> 🐛  Fix Radio story bug

- libraries/core-react/src/components/Tooltip/Tooltip.test.tsx
- libraries/core-react/src/components/Tooltip/Tooltip.tsx
- libraries/core-react/src/utils/index.ts
- libraries/core-react/src/utils/joinHandlers.ts
> 🐛 Fix Tooltip with external handlers

- libraries/core-react/src/components/Card/Card.stories.tsx
- libraries/core-react/src/components/Card/CardActions.tsx
> 💄Adjust card icon sizes and css fix

- libraries/core-react/src/components/Button/tokens/icon.ts
- libraries/core-react/src/components/Combobox/__snapshots__/Combobox.test.tsx.snap
- libraries/core-react/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
- libraries/core-react/src/components/Popover/__snapshots__/Popover.test.tsx.snap
- libraries/core-react/src/components/Select/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
- libraries/core-react/src/components/Select/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap
- libraries/core-react/src/components/SideSheet/__snapshots__/SideSheet.test.tsx.snap
> Update focus Ghost Icon Button 

- libraries/core-react/src/components/Radio/Radio.stories.tsx
- libraries/core-react/src/components/Radio/Radio.tokens.ts
- libraries/core-react/src/components/Radio/Radio.tsx
- libraries/core-react/src/components/Radio/__snapshots__/Radio.test.tsx.snap
> Radio focus + missing compact

- libraries/core-react/src/components/Switch/Switch.tokens.ts
- libraries/core-react/src/components/Switch/__snapshots__/Switch.test.tsx.snap
Resolves #1567 
Also conformed label spacing with the other selection controls
> Update Switch focus offset

- libraries/tokens/CHANGELOG.md
- libraries/tokens/package.json
> 🔖  Release eds-tokens@0.7.0

- libraries/core-react/src/components/Input/Input.stories.tsx
- libraries/core-react/src/components/Label/Label.stories.tsx
> 🐛 Removed <code> causing crashes in Label & Input story

- libraries/core-react/CHANGELOG.md
- libraries/core-react/package.json
> 🔖 Release eds-core-react@0.14.0

- libraries/icons/CHANGELOG.md
- libraries/icons/package.json
- libraries/icons/rollup.config.js
> 🔖 Release eds-icons@0.8.0

- libraries/core-react/src/components/Breadcrumbs/Breadcrumb.tsx
> fix breadcrumb missing href

- libraries/core-react/CHANGELOG.md
- libraries/core-react/package.json
> 🔖 Release eds-core-react@0.14.3

- libraries/core-react/src/components/Menu/Menu.context.tsx
> 🐛  Fix focusIndex on close for Menu

- libraries/core-react/src/components/TopBar/Actions.tsx
> Added central aligment for TopBar Actions

- libraries/core-react/src/components/Card/Card.stories.tsx
- libraries/core-react/src/components/Card/Card.tsx
- libraries/core-react/src/components/Card/CardActions.tsx
- libraries/core-react/src/components/Card/CardContent.tsx
- libraries/core-react/src/components/Card/CardHeader.tsx
- libraries/core-react/src/components/Card/CardHeaderTitle.tsx
- libraries/core-react/src/components/Card/CardMedia.tsx
- libraries/core-react/src/components/Card/__snapshots__/Card.test.tsx.snap
- libraries/core-react/src/components/Card/index.ts
The grid was created. I =n this stage there is question why `Card` component doesn't have`Card.Content` component?
>  :recycle:  Card.Media - introducing  grid, adding Card.Content

- libraries/core-react/src/components/Scrim/Scrim.stories.tsx
isDismissable is added to Scrim storybook, to close scrim with esc button.
> 🐛  Fix on close Scrim with esc button

- libraries/core-react/src/components/Card/CardMedia.tsx
- libraries/core-react/src/components/Card/__snapshots__/Card.test.tsx.snap
> ♻️Add spacing in Card.Media if fullWidth is false

- libraries/core-react/src/components/Search/Search.tokens.ts
- libraries/core-react/src/components/Search/Search.tsx
- libraries/core-react/src/components/Search/__snapshots__/Search.test.tsx.snap
resolves #1737
In Search.tokens `button` entity was created,  with defined height, width and spacing.
In Search component:
* `Button` component was imported. 
* New `button` entity was added.
> ♻️ Clean redundant code for btn in Search

- libraries/core-react/src/components/Combobox/Combobox.stories.tsx
- libraries/core-react/src/components/Combobox/Combobox.test.tsx
- libraries/core-react/src/components/Combobox/Combobox.tsx
- libraries/core-react/src/components/Combobox/Option.tsx
- libraries/core-react/src/index.ts
> ✨ Combobox data-model support with data property

- libraries/core-react/CHANGELOG.md
- libraries/core-react/package.json
> Release eds-core-react@0.16.1

- libraries/core-react/src/components/Tabs/Tab.tsx
- libraries/core-react/src/components/Tabs/TabPanel.tsx
- libraries/core-react/src/components/Tabs/Tabs.stories.tsx
- libraries/core-react/src/components/Tabs/Tabs.tsx
> ✨Add support for compact Tabs

- libraries/core-react/src/components/Banner/Banner.stories.tsx
- libraries/core-react/src/components/Banner/Banner.tsx
- libraries/core-react/src/components/Banner/BannerActions.tsx
- libraries/core-react/src/components/Banner/BannerIcon.tsx
> ✨Added support for compact Banner

- libraries/core-react/src/components/Popover/Popover.stories.tsx
- libraries/core-react/src/components/Popover/Popover.tokens.ts
- libraries/core-react/src/components/Popover/Popover.tsx
- libraries/core-react/src/components/Popover/PopoverTitle.tsx
> ✨ Added support for compact Popover

- libraries/core-react/src/components/Select/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
- libraries/core-react/src/components/Select/Select.tokens.ts
- libraries/core-react/src/components/Select/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap
- libraries/core-react/src/components/Select/commonStyles.ts
> 🐛 Change color on interactive icons in Select

- libraries/core-react/src/components/Accordion/Accordion.stories.tsx
- libraries/core-react/src/components/Accordion/Accordion.test.tsx
- libraries/core-react/src/components/Accordion/Accordion.tokens.ts
- libraries/core-react/src/components/Accordion/Accordion.tsx
- libraries/core-react/src/components/Accordion/AccordionHeader.tsx
- libraries/core-react/src/components/Accordion/AccordionHeaderTitle.tsx
- libraries/core-react/src/components/Accordion/AccordionPanel.tsx
> ✨Added support for compact accordion

- libraries/core-react/src/components/Banner/Banner.stories.tsx
- libraries/core-react/src/components/Banner/Banner.tokens.ts
> 📝 Add compact mode Banner story

- libraries/core-react/src/components/TableOfContents/LinkItem.tsx
- libraries/core-react/src/components/TableOfContents/TableOfContents.stories.tsx
- libraries/core-react/src/components/TableOfContents/TableOfContents.tokens.ts
- libraries/core-react/src/components/TableOfContents/TableOfContents.tsx
> ✨ Add support for compact TableOfContent

- libraries/core-react/src/components/Snackbar/Snackbar.stories.tsx
- libraries/core-react/src/components/Snackbar/Snackbar.tokens.ts
- libraries/core-react/src/components/Snackbar/Snackbar.tsx
- libraries/core-react/src/components/Snackbar/SnackbarAction.tsx
> ✨ Add support for compact Snackbar

- libraries/core-react/src/components/TopBar/TopBar.stories.tsx
- libraries/core-react/src/components/TopBar/TopBar.test.tsx
- libraries/core-react/src/components/TopBar/TopBar.tokens.ts
- libraries/core-react/src/components/TopBar/TopBar.tsx
> ✨ Add support for compact in TopBar

- libraries/core-react/src/components/Dialog/Actions.tsx
- libraries/core-react/src/components/Dialog/CustomContent.tsx
- libraries/core-react/src/components/Dialog/Dialog.stories.tsx
- libraries/core-react/src/components/Dialog/Dialog.tokens.ts
- libraries/core-react/src/components/Dialog/Dialog.tsx
- libraries/core-react/src/components/Dialog/Title.tsx
> ✨Add support for compact in Dialog

- libraries/core-react/src/components/Search/Search.stories.tsx
- libraries/core-react/src/components/Search/Search.tokens.ts
- libraries/core-react/src/components/Search/Search.tsx
- libraries/core-react/src/components/Search/__snapshots__/Search.test.tsx.snap
resolves #1747 
Edit: Keeping the close here as this has configured compact tokens according to design of how compact `Textfield`
> ✨ Added support for compact in Search

- libraries/core-react/src/components/Tabs/Tabs.stories.tsx
- libraries/core-react/src/components/Tabs/Tabs.tokens.ts
> 📝 Add compact mode Tabs story

- libraries/core-react/src/components/Button/Button.stories.tsx
- libraries/core-react/src/components/Group/Group.tokens.ts
- libraries/core-react/src/components/Group/Group.tsx
- libraries/core-react/src/components/Group/index.ts
> Create Group component

- CODE_OF_CONDUCT.md
> 📝 Add code of conduct doc

- libraries/core-react/src/components/Select/MultiSelect/MultiSelect.tsx
> 🚸 MultiSelect: clear input on blur, clearbutton

- .vscode/launch.json
- apps/figma-broker/functions/file.js
> 🐛 Fix parser warning in Figma-broker

- libraries/core-react/src/components/Combobox/Combobox.stories.tsx
- libraries/core-react/src/components/Combobox/Combobox.test.tsx
- libraries/core-react/src/components/Combobox/Combobox.tsx
- libraries/core-react/src/components/Combobox/Option.tsx
- libraries/core-react/src/index.ts
* ♻️ Moved some stuff around
* ♻️ Somewhat working example with optionLabel
* 🐛 Fixed reset for multiple
* ♻️ WIP on getting generic types to work
* ♻️ WIP getting generics to work
* Removed declare module as it was interfering with tests
* Fixed wrong type import
* 🚧 WIP on implementing existing features
* Example with onChangeOptions
* ♻️ Working Combobox again
* ✅ Fixed tests
> ✨ Updated combobox  with data-model support with data property (#1600)

- packages/eds-lab/package.json
- packages/eds-lab/pnpm-lock.yaml
- packages/eds-lab/src/components/Button/Button.stories.tsx
- packages/eds-lab/src/components/Button/Button.test.tsx
- packages/eds-lab/src/components/Button/Button.tsx
- packages/eds-lab/src/components/Button/Button.types.ts
- packages/eds-lab/src/components/Button/InnerFullWidth.tsx
- packages/eds-lab/src/components/Button/__snapshots__/Button.test.tsx.snap
- packages/eds-lab/src/components/Button/button.css
- packages/eds-lab/src/components/Button/index.ts
Moved code from long lived PR to `eds-lab` for further testing a spiking
> ♻️ Moved CSS Button spike to eds-lab

- .github/workflows/publish_lab.yaml
> 👷 Create publish lab action

- packages/eds-core-react/package.json
- packages/eds-core-react/pnpm-lock.yaml
- packages/eds-core-react/src/components/Dialog/Dialog.stories.tsx
- packages/eds-core-react/src/components/Scrim/Scrim.stories.tsx
> 🐛Fix argstable sync with useArgs

- packages/eds-core-react/src/components/Popover/Popover.stories.tsx
- packages/eds-core-react/src/components/Popover/Popover.test.tsx
- packages/eds-core-react/src/components/Popover/Popover.tokens.ts
- packages/eds-core-react/src/components/Popover/Popover.tsx
- packages/eds-core-react/src/components/Popover/PopoverActions.tsx
- packages/eds-core-react/src/components/Popover/PopoverContent.tsx
- packages/eds-core-react/src/components/Popover/PopoverHeader.tsx
- packages/eds-core-react/src/components/Popover/PopoverTitle.tsx
- packages/eds-core-react/src/components/Popover/__snapshots__/Popover.test.tsx.snap
- packages/eds-core-react/src/components/Popover/index.ts
> Refactor Popover

- packages/eds-core-react/src/hooks/useHideBodyScroll.ts
> 🐛 Fix scroll not being restored when scrim closes

- packages/eds-core-react/src/components/Menu/Menu.context.tsx
> 🐛Menu.context: Do onClose after setFocusedIndex

- packages/eds-core-react/src/components/Icon/Icon.docs.mdx
- packages/eds-core-react/src/components/Icon/Icon.stories.tsx
- packages/eds-core-react/src/components/Icon/Icon.tsx
- packages/eds-core-react/src/components/Search/__snapshots__/Search.test.tsx.snap
> ✨ Icon compact support

- package.yaml
- packages/eds-lab-react/.storybook/main.js
- packages/eds-lab-react/src/components/Combobox/Combobox.stories.tsx
- packages/eds-lab-react/src/components/Combobox/Combobox.test.tsx
- packages/eds-lab-react/src/components/Combobox/Combobox.tokens.ts
- packages/eds-lab-react/src/components/Combobox/Combobox.tsx
- packages/eds-lab-react/src/components/Combobox/Option.tsx
- packages/eds-lab-react/src/components/Combobox/__snapshots__/Combobox.test.tsx.snap
> ✨ Disabled options in Combobox

- packages/eds-lab-react/.storybook/components/PropsTable.tsx
- packages/eds-lab-react/.storybook/components/Stack.tsx
- packages/eds-lab-react/.storybook/components/Story.tsx
- packages/eds-lab-react/.storybook/components/index.ts
- packages/eds-lab-react/package.json
- packages/eds-lab-react/pnpm-lock.yaml
- packages/eds-lab-react/src/components/Combobox/Combobox.docs.mdx
- packages/eds-lab-react/src/components/Combobox/Combobox.stories.tsx
> 📝 Combobox documentation

- .github/workflows/publish_lab.yaml
- .github/workflows/publish_storybook.yaml
> 👷‍♂️ Add Lab to Publish Storybook

- packages/eds-utils/src/hooks/useAutoResize.test.tsx
- packages/eds-utils/src/hooks/useCombinedRefs.test.tsx
- packages/eds-utils/src/hooks/useGlobalKeyPress.test.ts
- packages/eds-utils/src/hooks/useHideBodyScroll.test.tsx
- packages/eds-utils/src/hooks/useHideBodyScroll.ts
- packages/eds-utils/src/hooks/useId.test.ts
- packages/eds-utils/src/hooks/useMountedRef.test.ts
- packages/eds-utils/src/hooks/useOutsideClick.test.tsx
- packages/eds-utils/src/hooks/usePopper.test.tsx
- packages/eds-utils/src/hooks/useToken.test.ts
>  ✅ eds-utils tests

- .github/workflows/checks lab.yaml
- .github/workflows/checks.yaml
- .github/workflows/publish_core_react.yaml
- .github/workflows/publish_lab.yaml
resolves #1847 
* Publish utils as part of lab or core-react
* Added build to lab & core-react checks
> 👷‍♂️ Add utils to actions

- packages/eds-utils/src/hooks/useId.test.ts
> ✅ fix useId test, number can be 1-5 digits

- packages/eds-core-react/src/components/Menu/Menu.stories.tsx
> 🐛 Fixed trapped focus in menu stories

- packages/eds-core-react/src/components/Avatar/Avatar.test.tsx
- packages/eds-core-react/src/components/Button/Button.test.tsx
- packages/eds-core-react/src/components/Dialog/Dialog.test.tsx
> ✅ Add a11y test for Avatar

- packages/eds-core-react/src/components/Banner/Banner.test.tsx
> ✅ Add a11y test for Banner

- packages/eds-core-react/src/components/Breadcrumbs/Breadcrumbs.test.tsx
> ✅ Add a11y test for Breadcrumbs

- packages/eds-core-react/src/components/Chip/Chip.test.tsx
> ✅ Add a11y test for Chip

- packages/eds-core-react/src/components/Card/Card.test.tsx
> ✅ Add a11y test for Card

- packages/eds-core-react/src/components/Input/Input.test.tsx
> ✅  Add a11y test for Input

- packages/eds-lab-react/src/components/Combobox/Combobox.docs.mdx
- packages/eds-lab-react/src/components/Combobox/Combobox.stories.tsx
- packages/eds-lab-react/src/components/Combobox/Combobox.tsx
> ✨ Combobox custom search filter

- packages/eds-core-react/src/components/Checkbox/Checkbox.test.tsx
> ✅ Add a11y test for Checkbox

- packages/eds-core-react/src/components/Snackbar/Snackbar.tsx
- packages/eds-core-react/src/components/Tooltip/Tooltip.tsx
> 🐛 Remove window references breaking SSR

- packages/eds-core-react/src/components/Tooltip/Tooltip.tsx
> 🐛 tooltip: merge popper.styles and style prop

- packages/eds-core-react/src/components/Chip/Chip.tsx
- packages/eds-core-react/src/components/Chip/__snapshots__/Chip.test.tsx.snap
- packages/eds-core-react/src/components/Menu/Menu.tsx
- packages/eds-core-react/src/components/Popover/Popover.tsx
- packages/eds-core-react/src/components/Popover/__snapshots__/Popover.test.tsx.snap
- packages/eds-core-react/src/components/Scrim/Scrim.tsx
- packages/eds-core-react/src/components/Scrim/__snapshots__/Scrim.test.tsx.snap
- packages/eds-core-react/src/components/SideSheet/SideSheet.tsx
- packages/eds-core-react/src/components/SideSheet/__snapshots__/SideSheet.test.tsx.snap
- packages/eds-core-react/src/components/Snackbar/Snackbar.tsx
- packages/eds-core-react/src/components/Snackbar/__snapshots__/Snackbar.test.tsx.snap
- packages/eds-core-react/src/components/Tooltip/Tooltip.tsx
- packages/eds-core-react/src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
- packages/eds-core-react/src/components/TopBar/TopBar.tsx
> 💄 Bump z-indexes inspired by MUI

- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/package.json
- packages/eds-utils/package.json
Resolves #1965 
also releases eds-utils@0.1.0
> 🔖 Release eds-core-react@0.18.0

- packages/eds-lab-react/src/components/Combobox/Combobox.docs.mdx
- packages/eds-lab-react/src/components/Combobox/Combobox.stories.tsx
- packages/eds-lab-react/src/components/Combobox/Combobox.tsx
resolves #961 
Suggest that this should just be an example (instead of built in) as it gives an indication on how to make other option types for quick selections in the combobox.
* Also found some bugs related to controlled that was fixed 🐛
> ✨ Combobox - Select all story

- packages/eds-core-react/src/components/Label/Label.test.tsx
> ✅ Add a11y test for label

- packages/eds-core-react/src/components/List/List.test.tsx
> ✅ Add a11y test for List

- packages/eds-core-react/src/components/Menu/Menu.test.tsx
> ✅ Add a11y test for Menu

- packages/eds-core-react/src/components/Pagination/Pagination.test.tsx
> ✅ Add a11y test for Pagination

- packages/eds-core-react/src/components/Popover/Popover.test.tsx
> ✅ Add a11y test for Popover

- packages/eds-lab-react/src/components/Autocomplete/Autocomplete.tsx
> 🐛 Autocomplete - Fix behaviour for placeholder declaration

- packages/eds-core-react/src/components/Menu/Menu.tsx
- packages/eds-core-react/src/components/Popover/Popover.tsx
- packages/eds-core-react/src/components/Tooltip/Tooltip.tsx
- packages/eds-lab-react/src/components/Autocomplete/Autocomplete.tsx
- packages/eds-utils/src/hooks/usePopper.test.tsx
- packages/eds-utils/src/hooks/usePopper.ts
> 🧑‍💻 usePopper object params

- packages/eds-core-react/src/components/Progress/Circular/CircularProgress.test.tsx
- packages/eds-core-react/src/components/Progress/Dots/DotProgress.test.tsx
- packages/eds-core-react/src/components/Progress/Linear/Linear.stories.tsx
- packages/eds-core-react/src/components/Progress/Linear/LinearProgress.test.tsx
- packages/eds-core-react/src/components/Progress/Star/StarProgress.test.tsx
> ✅  Add a11y test for Progress

- packages/eds-core-react/src/components/Accordion/Accordion.tokens.ts
- packages/eds-core-react/src/components/Accordion/__snapshots__/Accordion.test.tsx.snap
- packages/eds-core-react/src/components/Button/__snapshots__/Button.test.tsx.snap
- packages/eds-core-react/src/components/Button/tokens/button.ts
- packages/eds-core-react/src/components/Button/tokens/icon.ts
- packages/eds-core-react/src/components/Checkbox/Checkbox.tokens.ts
- packages/eds-core-react/src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap
- packages/eds-core-react/src/components/Chip/Chip.tokens.ts
- packages/eds-core-react/src/components/Chip/__snapshots__/Chip.test.tsx.snap
- packages/eds-core-react/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
- packages/eds-core-react/src/components/Radio/Radio.tokens.ts
- packages/eds-core-react/src/components/Radio/__snapshots__/Radio.test.tsx.snap
- packages/eds-core-react/src/components/Search/__snapshots__/Search.test.tsx.snap
- packages/eds-core-react/src/components/Select/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
- packages/eds-core-react/src/components/Select/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap
- packages/eds-core-react/src/components/SideSheet/__snapshots__/SideSheet.test.tsx.snap
- packages/eds-core-react/src/components/Slider/Slider.tokens.ts
- packages/eds-core-react/src/components/Slider/__snapshots__/Slider.test.tsx.snap
- packages/eds-core-react/src/components/Switch/Switch.tokens.ts
- packages/eds-core-react/src/components/Switch/__snapshots__/Switch.test.tsx.snap
- packages/eds-core-react/src/components/Tabs/Tabs.tokens.ts
- packages/eds-core-react/src/components/Typography/Typography.tokens.ts
- packages/eds-lab-react/src/components/CSSButton/button.css
- packages/eds-tokens/base/interactions.ts
- packages/eds-utils/src/utils/templates/focus.ts
- scripts/figma-broker/transformers/index.js
> 💄 Focus ring visibility

- packages/eds-core-react/src/components/Menu/Menu.test.tsx
- packages/eds-core-react/src/components/Popover/Popover.test.tsx
> ✅ Fix act warnings in menu and popover

- packages/eds-core-react/src/components/Radio/Radio.test.tsx
> ✅ Add a11y test for Radio

- packages/eds-core-react/src/components/Select/MultiSelect/MultiSelect.test.tsx
- packages/eds-core-react/src/components/Select/NativeSelect/NativeSelect.test.tsx
- packages/eds-core-react/src/components/Select/SingleSelect/SingleSelect.test.tsx
> ✅ Add a11y test for Select

- packages/eds-core-react/src/components/Scrim/Scrim.test.tsx
> ✅ Add a11y test for Scrim

- packages/eds-core-react/src/components/Slider/Slider.test.tsx
> ✅ Add a11y test for Slider

- packages/eds-core-react/src/components/Search/Search.test.tsx
>  ✅  Add a11y test for Search

- packages/eds-core-react/src/components/Switch/Switch.test.tsx
> ✅  Add a11y test for Switch

- packages/eds-core-react/src/components/Snackbar/Snackbar.test.tsx
> ✅  Add a11y test for Snackbar

- packages/eds-core-react/src/components/Table/Table.test.tsx
> ✅  Add a11y test for Table

- packages/eds-core-react/src/components/TableOfContents/TableOfContents.test.tsx
> ✅  Add a11y test for TableOfContents

- packages/eds-core-react/src/components/Tabs/Tabs.test.tsx
> ✅  Add a11y test for Tabs

- packages/eds-core-react/src/components/TextField/TextField.test.tsx
> ✅ Add a11y test for TextField

- packages/eds-core-react/src/components/TopBar/TopBar.test.tsx
> ✅  Add a11y test for TopBar

- packages/eds-core-react/src/components/Typography/Typography.test.tsx
> ✅  Add a11y test for Typography

- packages/eds-core-react/src/components/TextField/TextField.stories.tsx
> 📝 Explain input validation better in Textfield story

- .devcontainer/devcontainer.json
- .vscode/extensions.json
> 🔨  Add Axe Linter extension

- packages/eds-core-react/src/components/SideSheet/SideSheet.stories.tsx
> 🐛 fix sidesheet 'show code'

- packages/eds-core-react/src/components/Menu/Menu.stories.tsx
- packages/eds-core-react/src/components/Scrim/Scrim.tsx
Resolves #2092 
I included a story (menu inside a dialog) in menu stories temporarily if anyone wants to test more, with the intent to remove it again before merging once approved
> 🐛 Fix menu in scrim/Dialog

- packages/eds-core-react/src/components/Tooltip/Tooltip.test.tsx
> ✅  Add a11y test for Tooltip

- packages/eds-core-react/.storybook/components/index.ts
- packages/eds-core-react/src/components/Button/Button.docs.mdx
- packages/eds-core-react/src/components/Button/Button.stories.tsx
- packages/eds-core-react/src/components/mdx.d.ts
> 📝 Button documentation

- package.yaml
- packages/eds-core-react/package.json
- packages/eds-core-react/pnpm-lock.yaml
- packages/eds-core-react/src/components/Dialog/Dialog.test.tsx
- packages/eds-core-react/src/components/Input/Input.test.tsx
- packages/eds-core-react/src/components/Scrim/Scrim.test.tsx
- packages/eds-core-react/src/components/Slider/Slider.tsx
- packages/eds-core-react/src/components/Table/DataCell/DataCell.tokens.ts
- packages/eds-core-react/src/components/Table/Table.test.tsx
- packages/eds-core-react/stories/playground/DataTable.tsx
- packages/eds-core-react/stories/playground/Examples.stories.tsx
- packages/eds-icons/package.json
- packages/eds-icons/pnpm-lock.yaml
- packages/eds-lab-react/package.json
- packages/eds-lab-react/pnpm-lock.yaml
- packages/eds-tokens/package.json
- packages/eds-tokens/pnpm-lock.yaml
- packages/eds-utils/package.json
- packages/eds-utils/pnpm-lock.yaml
- pnpm-lock.yaml
> ⬆️ Upgrade typescript

- packages/eds-core-react/src/components/Slider/Slider.tsx
> 🐛 Fix Slider internal state if value changes

- packages/eds-core-react/src/components/Divider/Divider.stories.tsx
> 📝  Update Divider storyName

- packages/eds-core-react/src/components/Card/Card.docs.mdx
- packages/eds-core-react/src/components/Card/Card.stories.tsx
> 📝  Card documentation

- package.yaml
- packages/eds-core-react/package.json
- packages/eds-core-react/pnpm-lock.yaml
- packages/eds-lab-react/package.json
- packages/eds-lab-react/pnpm-lock.yaml
- packages/eds-utils/package.json
- packages/eds-utils/pnpm-lock.yaml
- pnpm-lock.yaml
> ⬆️ Update @babel/*

- packages/eds-core-react/src/components/Breadcrumbs/Breadcrumbs.docs.mdx
- packages/eds-core-react/src/components/Breadcrumbs/Breadcrumbs.stories.tsx
> 📝  Breadcrumbs documentation

- packages/eds-core-react/src/components/Chip/Chips.docs.mdx
- packages/eds-core-react/src/components/Chip/Chips.stories.tsx
> 📝 Chip documentation

- packages/eds-core-react/src/components/Dialog/Dialog.docs.mdx
- packages/eds-core-react/src/components/TextField/TextField.docs.mdx
- packages/eds-core-react/src/components/TextField/TextField.stories.tsx
> 📝 TextField documentation

- packages/eds-core-react/src/components/Breadcrumbs/Breadcrumbs.docs.mdx
- packages/eds-core-react/src/components/Card/Card.docs.mdx
- packages/eds-core-react/src/components/Chip/Chips.docs.mdx
- packages/eds-core-react/src/components/Dialog/Dialog.docs.mdx
- packages/eds-core-react/src/components/Divider/Divider.docs.mdx
- packages/eds-core-react/src/components/Snackbar/Snackbar.docs.mdx
- packages/eds-core-react/src/components/Snackbar/Snackbar.stories.tsx
> 📝  Snackbar documentation

- packages/eds-core-react/src/components/Accordion/Accordion.docs.mdx
- packages/eds-core-react/src/components/Accordion/Accordion.stories.tsx
> 📝 Accordion documentation

- packages/eds-core-react/src/components/Banner/Banner.docs.mdx
- packages/eds-core-react/src/components/Banner/Banner.stories.tsx
> 📝 Banner documentation

- packages/eds-core-react/src/components/Divider/Divider.docs.mdx
- packages/eds-core-react/src/components/Popover/Popover.docs.mdx
- packages/eds-core-react/src/components/Popover/Popover.stories.tsx
> 📝  Popover documentation

- packages/eds-core-react/src/components/List/List.docs.mdx
- packages/eds-core-react/src/components/List/Lists.stories.tsx
> 📝 List documentation

- packages/eds-core-react/src/components/Scrim/Scrim.docs.mdx
- packages/eds-core-react/src/components/Scrim/Scrim.stories.tsx
> 📝 Scrim documentation

- packages/eds-core-react/src/components/Pagination/Pagination.docs.mdx
- packages/eds-core-react/src/components/Pagination/Pagination.stories.tsx
> 📝 Pagination documentation

- packages/eds-core-react/src/components/Tooltip/Tooltip.docs.mdx
- packages/eds-core-react/src/components/Tooltip/Tooltip.stories.tsx
> 📝 Tooltip documentation

- packages/eds-lab-react/src/components/SideBar/ActionButton/ActionButton.test.tsx
- packages/eds-lab-react/src/components/SideBar/ActionButton/index.tsx
- packages/eds-lab-react/src/components/SideBar/SideBar.stories.tsx
- packages/eds-lab-react/src/components/SideBar/SideBar.test.tsx
- packages/eds-lab-react/src/components/SideBar/SideBar.tokens.ts
- packages/eds-lab-react/src/components/SideBar/SideBar.tsx
> Sidebar creatitem rename & upgrades

- packages/eds-core-react/src/components/TopBar/TopBar.docs.mdx
- packages/eds-core-react/src/components/TopBar/TopBar.stories.tsx
> 📝 TopBar documentation

- packages/eds-core-react/src/components/Progress/Circular/Circular.docs.mdx
- packages/eds-core-react/src/components/Progress/Circular/Circular.stories.tsx
- packages/eds-core-react/src/components/Progress/Dots/Dots.docs.mdx
- packages/eds-core-react/src/components/Progress/Dots/Dots.stories.tsx
- packages/eds-core-react/src/components/Progress/Linear/Linear.docs.mdx
- packages/eds-core-react/src/components/Progress/Linear/Linear.stories.tsx
- packages/eds-core-react/src/components/Progress/Star/Star.docs.mdx
- packages/eds-core-react/src/components/Progress/Star/Star.stories.tsx
> 📝 Progress documentation

- packages/eds-core-react/src/components/Search/Search.docs.mdx
- packages/eds-core-react/src/components/Search/Search.stories.tsx
> 📝 Search documentation

- packages/eds-lab-react/src/components/SideBar/SideBar.stories.tsx
- packages/eds-lab-react/src/components/SideBar/SideBar.test.tsx
- packages/eds-lab-react/src/components/SideBar/SideBar.tsx
- packages/eds-lab-react/src/components/SideBar/ToggleOpen/index.tsx
resolves #2140 
optional `toggleButton` prop with either "top" or "bottom" values.
Can now be toggled from the outside with the `open` prop
> ✨ Expand button customizable

- packages/eds-lab-react/src/components/Autocomplete/Autocomplete.docs.mdx
- packages/eds-lab-react/src/components/Autocomplete/Autocomplete.stories.tsx
- packages/eds-lab-react/src/components/Autocomplete/Autocomplete.test.tsx
- packages/eds-lab-react/src/components/Autocomplete/Autocomplete.tsx
resolves #2086 
* Added benefit is that we now support plain string arrays in addition to object arrays.
> ♻️ Autocomplete: Change id contraints for items

- .eslintrc.js
- packages/eds-core-react/README.md
- tsconfig.base.json
resolves #2180
Needed something to trigger checks, so updated README to give a better picture of current available components.
> 🔧  Update typescript configuration

- packages/eds-core-react/.storybook/components/Stack.tsx
- packages/eds-core-react/src/components/EdsProvider/EdsProvider.docs.mdx
- packages/eds-core-react/src/components/EdsProvider/EdsProvider.stories.tsx
> 📝 EdsProvider documentation

- packages/eds-core-react/src/components/Menu/Menu.docs.mdx
- packages/eds-core-react/src/components/Menu/Menu.stories.tsx
> 📝  Menu documentation

- packages/eds-core-react/src/components/Table/DataCell/DataCell.tsx
- packages/eds-core-react/src/components/Table/HeaderCell/HeaderCell.tsx
> 🐛 Fixed wrong Table Cell height

- packages/eds-core-react/jest.config.js
- packages/eds-core-react/jest.setup.ts
- packages/eds-core-react/src/components/Tooltip/Tooltip.test.tsx
> ✅ Fixed test warnings

- packages/eds-core-react/src/components/Accordion/Accordion.docs.mdx
- packages/eds-core-react/src/components/Breadcrumbs/Breadcrumbs.docs.mdx
- packages/eds-core-react/src/components/Button/Button.docs.mdx
- packages/eds-core-react/src/components/Dialog/Dialog.docs.mdx
- packages/eds-core-react/src/components/Menu/Menu.docs.mdx
- packages/eds-core-react/src/components/TopBar/TopBar.docs.mdx
> 📝  Update Aria links

- packages/eds-core-react/src/components/Dialog/Dialog.docs.mdx
- packages/eds-core-react/src/components/TableOfContents/TableOfContents.docs.mdx
- packages/eds-core-react/src/components/TableOfContents/TableOfContents.stories.tsx
> 📝  TableOfContent documentation

- packages/eds-core-react/src/components/Avatar/Avatar.docs.mdx
- packages/eds-core-react/src/components/Avatar/Avatar.stories.tsx
> 📝 Avatar documentation 

- packages/eds-core-react/src/components/Select/NativeSelect/NativeSelect.docs.mdx
- packages/eds-core-react/src/components/Select/NativeSelect/NativeSelect.stories.tsx
> 📝  Native Select documentation

- packages/eds-core-react/src/components/Icon/Icon.docs.mdx
- packages/eds-core-react/src/components/Icon/Icon.stories.tsx
> 📝 Icon documentation

- packages/eds-core-react/src/components/Popover/Popover.tsx
> 🐛 Popover: check for onClose existence

- packages/eds-core-react/src/components/TextField/TextField.docs.mdx
- packages/eds-core-react/src/components/TextField/TextField.stories.tsx
> 📝 Textfield storybook: added datetime examples

- assets/font/pnpm-lock.yaml
- assets/woman/pnpm-lock.yaml
- packages/eds-core-react/package.json
- packages/eds-core-react/pnpm-lock.yaml
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
- packages/eds-core-react/src/components/Autocomplete/Option.tsx
- packages/eds-icons/pnpm-lock.yaml
- packages/eds-lab-react/package.json
- packages/eds-lab-react/pnpm-lock.yaml
- packages/eds-tokens/pnpm-lock.yaml
- packages/eds-utils/package.json
- packages/eds-utils/pnpm-lock.yaml
- pnpm-lock.yaml
- scripts/figma-broker/pnpm-lock.yaml
* Updated lockfiles to pnpm v7.x.x. (lockfile version 5.4)
* Resolved unmeet peer deps
* Resolved circular dependency conflicts
> ⬆️ Updated lockfiles versions & resolved conflicts

- packages/eds-core-react/src/components/SideSheet/SideSheet.docs.mdx
- packages/eds-core-react/src/components/SideSheet/SideSheet.stories.tsx
> 📝  SideSheet documentation

- packages/eds-core-react/src/components/Slider/Slider.docs.mdx
- packages/eds-core-react/src/components/Slider/Slider.stories.tsx
- packages/eds-core-react/src/components/Slider/Slider.tsx
> 📝 Slider documentation

- packages/eds-core-react/src/components/Checkbox/Checkbox.docs.mdx
- packages/eds-core-react/src/components/Checkbox/Checkbox.stories.tsx
> 📝  Checkbox documentation

- packages/eds-core-react/src/components/Input/Input.docs.mdx
- packages/eds-core-react/src/components/Input/Input.stories.tsx
> 📝 Input documentation

- packages/eds-core-react/src/components/Label/Label.docs.mdx
- packages/eds-core-react/src/components/Label/Label.stories.tsx
> 📝 Label documentation

- packages/eds-icons/CHANGELOG.md
- packages/eds-icons/README.md
- packages/eds-icons/package.json
> 🔖 Release eds-icons@0.11.0

- packages/eds-core-react/src/components/Accordion/Accordion.docs.mdx
- packages/eds-core-react/src/components/Accordion/Accordion.stories.tsx
- packages/eds-core-react/src/components/Accordion/AccordionHeader.tsx
- packages/eds-core-react/src/components/Accordion/AccordionHeaderActions.tsx
- packages/eds-core-react/src/components/Accordion/AccordionHeaderTitle.tsx
- packages/eds-core-react/src/components/Accordion/__snapshots__/Accordion.test.tsx.snap
- packages/eds-core-react/src/components/Accordion/index.ts
resolves #2091 
Now, buttons or whatever else you want to add to the right side in the header can be put into the `Accordion.HeaderActions` subcomponent. This is placed next to the button toggle element instead of inside it.
> ♿️ Accordion header actions

- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
- packages/eds-core-react/src/components/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
fixes #2309 
bump to match the z-index of our other "dropdowns"
> 🐛 Fix Autocomplete z-index

- packages/eds-core-react/src/components/Input/Input.stories.tsx
- packages/eds-core-react/src/components/Textarea/Textarea.docs.mdx
- packages/eds-core-react/src/components/Textarea/Textarea.stories.tsx
> 📝  Textarea documentation

- packages/eds-core-react/src/components/Tabs/Tabs.docs.mdx
- packages/eds-core-react/src/components/Tabs/Tabs.stories.tsx
> 📝 Tabs documentation 

- packages/eds-core-react/src/components/Paper/Paper.docs.mdx
- packages/eds-core-react/src/components/Paper/Paper.stories.tsx
> 📝  Paper documentation

- packages/eds-core-react/src/components/Autocomplete/Autocomplete.docs.mdx
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.stories.tsx
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
> 🐛  Fix Autocomplete options update after initialization

- packages/eds-core-react/src/components/Slider/Slider.stories.tsx
- packages/eds-core-react/src/components/Switch/Switch.docs.mdx
- packages/eds-core-react/src/components/Switch/Switch.stories.tsx
> 📝 Switch documentation 

- packages/eds-core-react/src/components/Autocomplete/Autocomplete.docs.mdx
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.stories.tsx
- packages/eds-core-react/src/components/Button/Button.docs.mdx
- packages/eds-core-react/src/components/Button/Button.stories.tsx
- packages/eds-core-react/src/components/Card/Card.docs.mdx
- packages/eds-core-react/src/components/Icon/Icon.docs.mdx
- packages/eds-core-react/src/components/SideSheet/SideSheet.docs.mdx
> 📝  Docs typo fix

- packages/eds-core-react/src/components/Radio/Radio.docs.mdx
- packages/eds-core-react/src/components/Radio/Radio.stories.tsx
> 📝 Radio documentation

- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
> 🐛 Improved Autocomplete object comparisons for showing all available options on open 

- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/package.json
- ✨ Elevation options to Card/Banner/TopBar by @oddvernes in https://github.com/equinor/design-system/pull/2313
- 🐛 TypographyTemplate in Tab by @martalalik in https://github.com/equinor/design-system/pull/2316
- 🐛 Improved Autocomplete object comparisons for showing all available options on open by @mimarz in https://github.com/equinor/design-system/pull/2322
> 🔖 Release eds-core-react@0.20.3

- packages/eds-core-react/src/components/Popover/Popover.docs.mdx
- packages/eds-core-react/src/components/Popover/Popover.stories.tsx
> 📝 App launcher documentation

- packages/eds-core-react/src/components/Icon/Icon.tsx
> 🐛  Using Icon data should work properly if size is not defined

- packages/eds-core-react/package.json
- packages/eds-core-react/pnpm-lock.yaml
- packages/eds-lab-react/package.json
- packages/eds-lab-react/pnpm-lock.yaml
- packages/eds-utils/package.json
- packages/eds-utils/pnpm-lock.yaml
> ⬆️ Upgrade popperjs dependencies

- packages/eds-core-react/src/components/TextField/TextField.tsx
> 🐛 Fixed TextField style prop being sent container and inner input

- packages/eds-core-react/src/components/Autocomplete/Autocomplete.docs.mdx
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.stories.tsx
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
resolves #2333
- Turns our there was also a small bug when using `onOptionsChange` and `selectedOptions` was NOT set which i fixed.
- Did a big clean up of react forms hook
> 🐛 Fixed Autocomplete onOptionsChange when not controlled & cleaned up react hooks form example

- packages/eds-core-react/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
- packages/eds-core-react/src/components/Search/__snapshots__/Search.test.tsx.snap
- packages/eds-core-react/src/components/Select/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
- packages/eds-core-react/src/components/Select/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap
- packages/eds-core-react/src/components/SideSheet/__snapshots__/SideSheet.test.tsx.snap
- packages/eds-tokens/base/index.ts
- packages/eds-tokens/base/shape.ts
- packages/eds-tokens/tokens.css
> 🍱 Updated tokens

- packages/eds-icons/CHANGELOG.md
- packages/eds-icons/package.json
- `signature`
- `approve`
- `no_craning`
- `craning`
- `toolbox`
- `toolbox_wheel`
- `toolbox_rope`
- `badge`
- `hand_radio`
- `substation_onshore`
- `substation_offshore`
- `expand`
- `collapse`
> 🔖  Release eds-icons@0.12.0

- packages/eds-core-react/src/components/Accordion/AccordionHeader.tsx
- packages/eds-core-react/src/components/Accordion/AccordionHeaderActions.tsx
- packages/eds-core-react/src/components/Accordion/AccordionHeaderTitle.tsx
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
- packages/eds-core-react/src/components/Checkbox/Checkbox.tsx
- packages/eds-core-react/src/components/Checkbox/Input.tsx
- packages/eds-core-react/src/components/Radio/Radio.tsx
- packages/eds-core-react/src/components/Search/Search.tsx
- packages/eds-core-react/src/components/Select/NativeSelect/NativeSelect.tsx
- packages/eds-core-react/src/components/Switch/Switch.tsx
- packages/eds-core-react/src/components/Switch/SwitchDefault.tsx
- packages/eds-core-react/src/components/Switch/SwitchSmall.tsx
> 💄Conform outer styles

- packages/eds-core-react/package.json
- packages/eds-core-react/pnpm-lock.yaml
- packages/eds-core-react/src/components/Breadcrumbs/Breadcrumbs.test.tsx
- packages/eds-core-react/src/components/Tooltip/Tooltip.stories.tsx
- packages/eds-core-react/src/components/Tooltip/Tooltip.test.tsx
- packages/eds-core-react/src/components/Tooltip/Tooltip.tsx
- packages/eds-core-react/src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
- packages/eds-lab-react/src/components/SideBar/SideBar.test.tsx
- packages/eds-lab-react/src/components/SideBar/SidebarLink/SidebarLink.test.tsx
> ♻️ floating-UI tooltip

- packages/eds-core-react/src/components/Popover/Popover.test.tsx
- packages/eds-core-react/src/components/Popover/Popover.tsx
- packages/eds-core-react/src/components/Popover/__snapshots__/Popover.test.tsx.snap
> ♻️ Popover use floating-ui

- packages/eds-lab-react/src/components/SideBar/SideBar.test.tsx
- packages/eds-lab-react/src/components/SideBar/SideBar.tokens.ts
- packages/eds-lab-react/src/components/SideBar/SideBar.tsx
- packages/eds-lab-react/src/components/SideBar/SideBarButton/index.tsx
- packages/eds-lab-react/src/components/SideBar/SideBarContent.tsx
- packages/eds-lab-react/src/components/SideBar/SideBarFooter.tsx
- packages/eds-lab-react/src/components/SideBar/SideBarToggle.tsx
- packages/eds-lab-react/src/components/SideBar/SidebarLink/index.tsx
> 💄Sidebar design conforms

- .github/workflows/publish_core_react.yaml
- .github/workflows/publish_icons.yaml
- .github/workflows/publish_lab.yaml
- .github/workflows/publish_tokens.yaml
- .npmrc
- .vscode/settings.json
- packages/eds-lab-react/package.json
> 👷 Change how npm auth token is defined

- packages/eds-core-react/src/components/SideSheet/SideSheet.tsx
> ✨ Add width to SideSheet

- packages/eds-core-react/src/components/Banner/Banner.stories.tsx
> 📝 Clean up Banner story

- packages/eds-core-react/src/components/Accordion/Accordion.stories.tsx
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.stories.tsx
- packages/eds-core-react/src/components/Button/Button.stories.tsx
- packages/eds-core-react/src/components/Chip/Chips.stories.tsx
- packages/eds-core-react/src/components/Dialog/Dialog.stories.tsx
- packages/eds-core-react/src/components/Popover/Popover.stories.tsx
- packages/eds-core-react/src/components/Progress/Circular/Circular.stories.tsx
- packages/eds-core-react/src/components/Progress/Dots/Dots.stories.tsx
- packages/eds-core-react/src/components/Progress/Linear/Linear.stories.tsx
- packages/eds-core-react/src/components/Progress/Star/Star.stories.tsx
- packages/eds-core-react/src/components/SideSheet/SideSheet.stories.tsx
- packages/eds-core-react/src/components/Table/Table.stories.tsx
- packages/eds-core-react/src/components/Tabs/Tabs.stories.tsx
- packages/eds-core-react/src/components/Tabs/Tabs.types.ts
- packages/eds-core-react/src/components/TextField/TextField.stories.tsx
- packages/eds-core-react/src/components/Tooltip/Tooltip.stories.tsx
- packages/eds-core-react/src/components/TopBar/TopBar.stories.tsx
> 🎨  Add decorators

- packages/eds-lab-react/src/components/SideBar/SideBar.tokens.ts
- packages/eds-lab-react/src/components/SideBar/SideBar.tsx
- packages/eds-lab-react/src/components/SideBar/SidebarLink/index.tsx
Resolves #2261
Made links focusable and added focus outline
Made link overridable component so it can be used with routers
> ✨♿️Sidebar link improvements

- packages/eds-core-react/src/components/Accordion/Accordion.tokens.ts
- packages/eds-core-react/src/components/Accordion/AccordionPanel.tsx
- packages/eds-core-react/src/components/Accordion/__snapshots__/Accordion.test.tsx.snap
- packages/eds-core-react/src/components/SideSheet/SideSheet.tokens.ts
- packages/eds-core-react/src/components/SideSheet/SideSheet.tsx
- packages/eds-core-react/src/components/SideSheet/__snapshots__/SideSheet.test.tsx.snap
- packages/eds-core-react/src/components/TopBar/TopBar.stories.tsx
> 🎨  Fix canvas font in Storybook

- packages/eds-core-react/src/components/Radio/Radio.docs.mdx
- packages/eds-core-react/src/components/Radio/Radio.stories.tsx
>  📝  Add custom label to selection controls

- packages/eds-core-react/src/components/Card/Card.tsx
- packages/eds-core-react/src/components/Card/__snapshots__/Card.test.tsx.snap
> 🗑️ Card: removed cursor logic for onClick

- packages/eds-core-react/src/components/Popover/Popover.tsx
- packages/eds-core-react/src/components/Popover/__snapshots__/Popover.test.tsx.snap
> 🐛 Popover overflow

- .vscode/settings.json
- packages/eds-core-react/src/components/Typography/Typography.docs.mdx
- packages/eds-core-react/src/components/Typography/Typography.stories.tsx
- packages/eds-core-react/src/components/Typography/Typography.tsx
> ✨ Make typography an overridableComponent

- packages/eds-core-react/src/components/Breadcrumbs/Breadcrumb.tsx
- packages/eds-core-react/src/components/Breadcrumbs/Breadcrumbs.docs.mdx
> ✨OverridableComponent breadcrumb

- packages/eds-core-react/src/components/TopBar/TopBar.stories.tsx
- packages/eds-core-react/src/components/TopBar/TopBar.test.tsx
- packages/eds-core-react/src/components/TopBar/TopBar.tokens.ts
- packages/eds-core-react/src/components/TopBar/__snapshots__/TopBar.test.tsx.snap
Resolves #2445 
also fixed bug where snapshot was empty for this component
> 💄 Topbar padding

- packages/eds-core-react/src/components/Table/Table.test.tsx
- packages/eds-core-react/src/components/Table/__snapshots__/Table.test.tsx.snap
- packages/eds-core-react/src/components/TableOfContents/TableOfContents.test.tsx
- packages/eds-core-react/src/components/TableOfContents/__snapshots__/TableOfContents.test.tsx.snap
- packages/eds-core-react/src/components/Tabs/Tabs.test.tsx
- packages/eds-core-react/src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
- packages/eds-core-react/src/components/TextField/TextField.test.tsx
- packages/eds-core-react/src/components/TextField/__snapshots__/TextField.test.tsx.snap
- packages/eds-core-react/src/components/Typography/Typography.test.tsx
- packages/eds-core-react/src/components/Typography/__snapshots__/Typography.test.tsx.snap
> 📸🐛Created missing snapshots

- packages/eds-core-react/package.json
- packages/eds-core-react/pnpm-lock.yaml
- packages/eds-core-react/stories/utils/Utils.docs.mdx
- packages/eds-lab-react/package.json
- packages/eds-lab-react/pnpm-lock.yaml
- packages/eds-utils/src/hooks/usePopper.ts
> ➖Remove popperjs dependency

- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/package.json
- packages/eds-utils/CHANGELOG.md
- packages/eds-utils/package.json
> 🔖Release eds-core-react@0.21.0

- packages/eds-core-react/src/components/Dialog/Dialog.tsx
resolves #2328 
Instead of native dialog, I opted to use floating-ui's FloatingFocusManager to handle focus trapping and returning focus
> ♿️ Focustrapping in Dialog with floating-ui

- packages/eds-icons/package.json
> 📦 Bump eds-icons@0.13.0

- packages/eds-core-react/src/components/EdsProvider/EdsProvider.docs.mdx
- packages/eds-core-react/src/components/EdsProvider/EdsProvider.stories.tsx
- packages/eds-core-react/src/components/EdsProvider/eds.context.tsx
- Better documentation for `EdsProvider` with using `useEds`
- Fixed missing `setDensity` on `EdsProvider`
- Fixed a potentional edge-case when using `useEds` without setting default on `EdsProvider` using `density` property
> 🐛 Fix missing `setDensity` & better documentation for `EdsProvider`

- packages/eds-core-react/src/components/Tabs/Tabs.stories.tsx
resolves #2495 
fixes "next" button not disabling (it was a rounding error) and added code so it still works when resizing
> 🐛Tabs: scroll with buttons story improvements

- packages/eds-core-react/src/components/Popover/Popover.tsx
- packages/eds-core-react/src/components/Popover/__snapshots__/Popover.test.tsx.snap
resolves #2506
Also removed some redundant css
> 🐛Popover: fix missing arrow 

- packages/eds-core-react/src/components/SideSheet/SideSheet.docs.mdx
- packages/eds-core-react/src/components/SideSheet/SideSheet.stories.tsx
> 📝 Draggable sidesheet story

- packages/eds-core-react/src/components/Scrim/Scrim.tokens.ts
- packages/eds-core-react/src/components/Scrim/Scrim.tsx
- packages/eds-core-react/src/components/Scrim/__snapshots__/Scrim.test.tsx.snap
> 🎨 Add FloatingOverlay to Scrim

- packages/eds-core-react/src/components/Popover/Popover.docs.mdx
- packages/eds-core-react/src/components/Popover/Popover.stories.tsx
- packages/eds-core-react/src/components/Popover/PopoverContent.tsx
> Add not dismissible for Popover

- packages/eds-core-react/src/components/Button/Button.docs.mdx
- packages/eds-core-react/src/components/Button/Button.stories.tsx
- packages/eds-core-react/src/components/Button/ToggleButton/ToggleButton.tsx
- packages/eds-core-react/src/components/Button/ToggleButton/ToggleButton.types.ts
- packages/eds-core-react/src/components/Button/ToggleButton/index.ts
- packages/eds-core-react/src/components/Button/index.ts
> ✨ Create ToggleButton

- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
- packages/eds-core-react/src/components/Menu/Menu.tsx
- packages/eds-core-react/src/components/Popover/Popover.tsx
- packages/eds-core-react/src/components/Tooltip/Tooltip.tsx
> ♻️ Replaced all occurences of ?? with ||

- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/package.json
> 🔖Release eds-core-react@0.22.0

- packages/eds-core-react/src/components/Accordion/AccordionHeader.tsx
- packages/eds-core-react/src/components/Accordion/__snapshots__/Accordion.test.tsx.snap
> 🐛 Accordion: fixed shrinking icon

- package.json
- pnpm-lock.yaml
> ⬆️ Upgrade EDS project dependencies

- packages/eds-core-react/package.json
- packages/eds-core-react/pnpm-lock.yaml
resolves #2523 
The breaking changes did not apply to any of our code as far as i can see
> ⬆️ upgraded floating-ui to v0.10.1

- packages/eds-core-react/src/components/Tabs/Tab.tsx
- packages/eds-core-react/src/components/Tabs/Tabs.docs.mdx
- packages/eds-core-react/src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
resolves #2434 
tested downstream with react-router-dom and nested routes like this:
> ✨Polymorphic tabs

- packages/eds-core-react/package.json
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.stories.tsx
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
> ♻️ Autocomplete: Always show all options on re-open after selection

- packages/eds-lab-react/src/components/SideBar/SideBar.stories.tsx
- packages/eds-lab-react/src/components/SideBar/SideBar.tokens.ts
- packages/eds-lab-react/src/components/SideBar/SideBarButton/index.tsx
- packages/eds-lab-react/src/components/SideBar/SideBarToggle.tsx
- packages/eds-lab-react/src/components/SideBar/SidebarLink/index.tsx
> 💄 Sidebar spacing

- README.md
> 📝 Add quick links

- packages/eds-core-react/src/components/Popover/Popover.docs.mdx
- packages/eds-core-react/src/components/Popover/Popover.stories.tsx
- packages/eds-core-react/src/components/Popover/Popover.test.tsx
- packages/eds-core-react/src/components/Popover/Popover.tokens.ts
- packages/eds-core-react/src/components/Popover/Popover.tsx
- packages/eds-core-react/src/components/Popover/__snapshots__/Popover.test.tsx.snap
> ♿️  Add portal & focusManager to Popover

- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
> 💄 Bumped z-index for autocomplete 

- packages/eds-core-react/src/components/Tooltip/Tooltip.docs.mdx
> 📝 Update aria link for Tooltip

- .github/workflows/publish_packages.yaml
resolves #2581 
* This action will publish all packages in correct order
* All published packages (if new versions are detected) will have the same input tag
* Storybook slot is only for core-react storybook
* Lab is hardcoded to lab storybook slot
> 👷 Added publish all packages action

- packages/eds-core-react/src/components/Button/ToggleButton/ToggleButton.stories.tsx
> 🐛 Adjust `propTable` for Toggle in Storybook

- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/package.json
- packages/eds-lab-react/CHANGELOG.md
- packages/eds-lab-react/package.json
- packages/eds-tokens/CHANGELOG.md
- packages/eds-tokens/package.json
- packages/eds-utils/CHANGELOG.md
- packages/eds-utils/package.json
> 🔖 Release eds-core-react@0.25.0, eds-lab-react@0.5.2, eds-utils@0.6.0, eds-tokens@0.9.0

- packages/eds-lab-react/src/components/SideBar/SideBar.stories.tsx
- packages/eds-lab-react/src/components/SideBar/SideBar.tokens.ts
- packages/eds-lab-react/src/components/SideBar/SideBarContent.tsx
- packages/eds-lab-react/src/components/SideBar/SideBarToggle.tsx
- packages/eds-lab-react/src/components/SideBar/SidebarLink/index.tsx
> 💄Sidebar: changes to spacing

- packages/eds-core-react/src/components/Slider/Slider.stories.tsx
> 🐛 Disable control for value in `argTable` for Slider in Storybook

- packages/eds-core-react/src/components/Tooltip/Tooltip.docs.mdx
- packages/eds-core-react/src/components/Tooltip/Tooltip.stories.tsx
- packages/eds-core-react/src/components/Tooltip/Tooltip.tsx
- packages/eds-core-react/src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
> 🐛  Improve a11y for screen readers for Tooltip

- packages/eds-core-react/src/components/Typography/Typography.docs.mdx
- packages/eds-core-react/src/components/Typography/Typography.stories.tsx
> 🐛 Fix crushing story page for Typography

- .devcontainer/devcontainer.json
- .gitpod.yml
- .vscode/extensions.json
resolves #2577 
Suggested recommended extensions, with some personal recommendations such as rainbow-brackets 🌈 
- [dbaeumer.vscode-eslint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)
- [stylelint.vscode-stylelint](https://marketplace.visualstudio.com/items?itemName=stylelint.vscode-stylelint)
- [esbenp.prettier-vscode](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)
- [editorconfig.editorconfig](https://marketplace.visualstudio.com/items?itemName=editorconfig.editorconfig)
- [redhat.vscode-yaml](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml)
- [unifiedjs.vscode-mdx](https://marketplace.visualstudio.com/items?itemName=unifiedjs.vscode-mdx)
- [deque-systems.vscode-axe-linter](https://marketplace.visualstudi …
> 🔧 Suggestion for recommended extensions

- packages/eds-core-react/src/components/SideBar/SideBar.test.tsx
- packages/eds-core-react/src/components/SideBar/__snapshots__/SideBar.test.tsx.snap
> ✅ SideBar: added snapshot test

- packages/eds-core-react/src/components/TopBar/Header.tsx
- packages/eds-core-react/src/components/TopBar/__snapshots__/TopBar.test.tsx.snap
> 💄 Change header gap for TopBar

- packages/eds-core-react/src/components/Button/Button.docs.mdx
- packages/eds-core-react/src/components/Button/Button.stories.tsx
- packages/eds-core-react/src/components/Button/Button.tsx
- packages/eds-core-react/src/components/Button/__snapshots__/Button.test.tsx.snap
- packages/eds-core-react/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
- packages/eds-core-react/src/components/Select/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
- packages/eds-core-react/src/components/Select/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap
- packages/eds-core-react/src/components/SideBar/__snapshots__/SideBar.test.tsx.snap
- packages/eds-core-react/src/components/SideSheet/__snapshots__/SideSheet.test.tsx.snap
> :children_crossing: Visually disable components that have aria-disabled

- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/package.json
- packages/eds-core-react/src/components/SideBar/SideBar.docs.mdx
- packages/eds-lab-react/CHANGELOG.md
- packages/eds-lab-react/package.json
- packages/eds-utils/CHANGELOG.md
- packages/eds-utils/package.json
> 🔖 Release eds-core-react@0.26.0, eds-lab-react@0.6.0, eds-utils@0.7.0

- packages/eds-core-react/src/components/TextField/TextField.docs.mdx
- packages/eds-core-react/src/components/TextField/TextField.stories.tsx
> 📝 TextField: Updated documentation on validation

- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/package.json
> 🔖 Release eds-core-react@0.27.0

- package.json
- packages/eds-core-react/package.json
- packages/eds-core-react/pnpm-lock.yaml
- packages/eds-core-react/src/components/Table/Table.docs.mdx
- packages/eds-core-react/src/components/Table/Table.stories.tsx
- pnpm-lock.yaml
> 📝 Added example of virtual scrolling for Table

- packages/eds-core-react/src/components/TextField/TextField.stories.tsx
> 💄 Removed resize: none from TextField Storybook

- packages/eds-core-react/src/components/Table/Table.stories.tsx
> 💄 Storybook: Added bottom margin to Table header

- packages/eds-core-react/src/components/Autocomplete/Autocomplete.stories.tsx
- packages/eds-core-react/src/components/Breadcrumbs/Breadcrumbs.stories.tsx
- packages/eds-core-react/src/components/Dialog/Dialog.stories.tsx
- packages/eds-core-react/src/components/Menu/Menu.stories.tsx
- packages/eds-core-react/src/components/Popover/Popover.stories.tsx
- packages/eds-core-react/src/components/Scrim/Scrim.stories.tsx
- packages/eds-core-react/src/components/SideSheet/SideSheet.stories.tsx
- packages/eds-core-react/src/components/Slider/Slider.stories.tsx
> 📝 Fixed broken stories in Storybook

- packages/eds-core-react/CHANGELOG.md
- packages/eds-tokens/CHANGELOG.md
resolves #2657 
I have already updated the release notes on github with the same entries
> 📝 Added missing changelog items

- packages/eds-core-react/src/components/Table/Table.stories.tsx
> 📝 Handle aborted fetch in Table:virtual scroll

- packages/eds-core-react/CHANGELOG.md
> 📝 Updated missing changelog entry

- packages/eds-core-react/package.json
- packages/eds-core-react/pnpm-lock.yaml
- packages/eds-lab-react/package.json
- packages/eds-lab-react/pnpm-lock.yaml
resolves #2369 
Tested downstream in create react app before and after, seems to work, as dropdown is no longer open on page load like it was before
> ⬆️ Upgrade downshift to 7.0.5

- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/package.json
> 🔖 Release eds-core-react@0.28.0

- packages/eds-core-react/src/components/Menu/Menu.context.tsx
- packages/eds-core-react/src/components/Menu/Menu.docs.mdx
- packages/eds-core-react/src/components/Menu/Menu.stories.tsx
- packages/eds-core-react/src/components/Menu/Menu.tsx
- packages/eds-core-react/src/components/Menu/MenuItem.tsx
- packages/eds-core-react/src/components/Menu/MenuList.tsx
> ✨ Menu stays open after click with new prop

- packages/eds-core-react/src/components/Accordion/AccordionPanel.tsx
- packages/eds-core-react/src/components/Accordion/__snapshots__/Accordion.test.tsx.snap
> 🐛 Fixed border on Accordion

- packages/eds-core-react/src/components/Button/ToggleButton/ToggleButton.stories.tsx
- packages/eds-core-react/src/components/Button/ToggleButton/ToggleButton.tsx
> ✨ Add tooltip support for ToggleButton

- packages/eds-core-react/src/components/Banner/__snapshots__/Banner.test.tsx.snap
- packages/eds-core-react/src/components/Card/__snapshots__/Card.test.tsx.snap
- packages/eds-core-react/src/components/Dialog/__snapshots__/Dialog.test.tsx.snap
- packages/eds-core-react/src/components/Paper/Paper.tsx
- packages/eds-core-react/src/components/Popover/__snapshots__/Popover.test.tsx.snap
- packages/eds-core-react/src/components/Snackbar/__snapshots__/Snackbar.test.tsx.snap
- packages/eds-core-react/src/components/TopBar/__snapshots__/TopBar.test.tsx.snap
The elevation prop of Paper was beeing rendered to the dom, this is not valid html and should be transient
> Fixed issue #2763 by making the elevation props transient

- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/package.json
- packages/eds-core-react/pnpm-lock.yaml
> 🔖 Release eds-core-react@0.29.1

- packages/eds-core-react/src/components/Button/Button.docs.mdx
> 📝 Add note about nextLink in button docs

- packages/eds-core-react/package.json
- packages/eds-core-react/pnpm-lock.yaml
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
Does not resolve any issues
I have not been able to recreate this bug (where dropdown sometimes does not render when using portal). So, I have updated downshift, floating-ui and tanstack-virtual and changed to using new ref setters with floating ui.
> 🐛 Autocomplete: updated deps & refactor floating-ui refs

- packages/eds-core-react/src/components/Accordion/Accordion.docs.mdx
- packages/eds-core-react/src/components/Accordion/Accordion.stories.tsx
- packages/eds-core-react/src/components/Accordion/Accordion.test.tsx
- packages/eds-core-react/src/components/Accordion/AccordionItem.tsx
> 📝 Accordion: added "controlled" story, test

- packages/eds-core-react/src/components/Autocomplete/Autocomplete.docs.mdx
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.stories.tsx
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
resolves #2090
Introduces `onInputChange` and `loading` props and a new **Async search autocomplete** story
> ✨ Autocomplete async

- packages/eds-core-react/src/components/Select/NativeSelect/NativeSelect.tsx
> 🐛 NativeSelect: forward disabled prop to Label

- packages/eds-core-react/src/components/Menu/Menu.docs.mdx
- packages/eds-core-react/src/components/Menu/Menu.stories.tsx
- packages/eds-core-react/src/components/Menu/Menu.tsx
This makes the menu match the width of the anchor
Resolves #2805
> ✨ Menu: added matchAnchorWidth prop

- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
- packages/eds-core-react/src/components/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
> ✨ Autocomplete: added dropdownHeight prop

- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
- packages/eds-core-react/src/components/Input/Input.tsx
- packages/eds-core-react/src/components/Input/__snapshots__/Input.test.tsx.snap
- packages/eds-core-react/src/components/Search/__snapshots__/Search.test.tsx.snap
- packages/eds-core-react/src/components/TextField/__snapshots__/TextField.test.tsx.snap
> 🚸Input: added ellipsis, Autocomplete: improved padding-right

- packages/eds-icons/CHANGELOG.md
- packages/eds-icons/package.json
> :bookmark: Release eds-icons@0.19.1

- packages/eds-core-react/src/components/Menu/Menu.docs.mdx
- packages/eds-core-react/src/components/Menu/Menu.stories.tsx
- packages/eds-core-react/src/components/Menu/MenuItem.tsx
resolves #2813 
I tested with react-router downstream in my own app and it worked.
also added a story demonstrating external links, and adjusted the matchWidth story a little bit
> ✨ Menu: polymorphic menu.item

- COMPONENT_GUIDELINES.md
- README.md
- assets/font/subset.js
- packages/eds-core-react/.storybook/manager-head.html
- packages/eds-core-react/.storybook/preview-head.html
- packages/eds-core-react/.storybook/theme.js
- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/README.md
- packages/eds-core-react/src/components/Typography/Typography.docs.mdx
- packages/eds-icons/README.md
- packages/eds-lab-react/.storybook/manager-head.html
- packages/eds-lab-react/.storybook/preview-head.html
- packages/eds-lab-react/.storybook/theme.js
- packages/eds-lab-react/README.md
resolves #2787 
updated readmes and updated all the cdn links. Also fixed some outdated information in some readmes
> 📝 Updated storybook links in readmes

- packages/eds-lab-react/CHANGELOG.md
- packages/eds-lab-react/package.json
> 🔖 Release eds-lab-react@0.7.0

- scripts/figma-broker/transformers/typography.js
> Added css variables for typography colors

- packages/eds-core-react/src/components/Checkbox/Checkbox.tokens.ts
- packages/eds-core-react/src/components/Checkbox/Input.tsx
- packages/eds-core-react/src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap
- packages/eds-core-react/src/components/Radio/Radio.tokens.ts
- packages/eds-core-react/src/components/Radio/Radio.tsx
- packages/eds-core-react/src/components/Radio/__snapshots__/Radio.test.tsx.snap
- packages/eds-core-react/src/components/Switch/Switch.styles.ts
- packages/eds-core-react/src/components/Switch/Switch.tokens.ts
- packages/eds-core-react/src/components/Switch/Switch.tsx
- packages/eds-core-react/src/components/Switch/SwitchDefault.tsx
- packages/eds-core-react/src/components/Switch/__snapshots__/Switch.test.tsx.snap
resolves #2678 
Edit: switch is missing clickbound, so I will also fix this
> 💄 Radio/Checkbox: changed visual size of hover background

- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/package.json
- packages/eds-tokens/CHANGELOG.md
> 🔖 Release eds-core-react@0.31.0, eds-tokens@0.9.1

- packages/eds-core-react/src/components/Menu/MenuItem.tsx
> 🐛 Menu: make 'active' transient prop in Item

- .github/workflows/_purge_cdn.yaml
- .github/workflows/publish_core_react.yaml
- .github/workflows/publish_storybook_new.yaml
> ✨ Add purging of cdn to the list of jobs fwhen publishing SB

- packages/eds-core-react/src/components/Tooltip/Tooltip.test.tsx
> ✅ Fixed warning in Tooltip-test

- packages/eds-core-react/src/components/Autocomplete/Autocomplete.stories.tsx
> 📝 Improved Autocomplete selectAll-story

- packages/eds-core-react/package.json
- packages/eds-core-react/pnpm-lock.yaml
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
- packages/eds-core-react/src/components/Dialog/Dialog.tsx
- packages/eds-core-react/src/components/Dialog/__snapshots__/Dialog.test.tsx.snap
- packages/eds-core-react/src/components/Menu/Menu.tsx
- packages/eds-core-react/src/components/Popover/Popover.tsx
- packages/eds-core-react/src/components/Popover/__snapshots__/Popover.test.tsx.snap
- packages/eds-core-react/src/components/Tooltip/Tooltip.tsx
- packages/eds-core-react/src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
> ⬆️ Update floating-ui

- packages/eds-icons/CHANGELOG.md
- packages/eds-icons/package.json
- packages/eds-icons/rollup.config.js
> 🔖Release eds-icons@0.19.2

- packages/eds-tokens/CHANGELOG.md
- packages/eds-tokens/package.json
- packages/eds-tokens/rollup.config.js
> 🔖Release eds-tokens@0.9.2

- packages/eds-core-react/src/components/Tabs/TabPanel.tsx
- packages/eds-core-react/src/components/Tabs/TabPanels.tsx
> ⚡️ Tabs: conditionally render tab panels

- packages/eds-core-react/src/components/Typography/Typography.tsx
- packages/eds-core-react/src/components/Typography/__snapshots__/Typography.test.tsx.snap
> 🐛Typography: make color transient prop

- packages/eds-core-react/src/components/Card/CardActions.tsx
- packages/eds-core-react/src/components/Card/CardContent.tsx
- packages/eds-core-react/src/components/Card/CardHeader.tsx
- packages/eds-core-react/src/components/Popover/Popover.stories.tsx
- packages/eds-core-react/src/components/Popover/PopoverActions.tsx
- packages/eds-core-react/src/components/Popover/PopoverContent.tsx
resolves #2879 
Hopefully, as we are not upgraded to styled-components v6 yet to test this. 🤞
> 🐛Fix missing "&" on first/last-child selectors

- packages/eds-utils/CHANGELOG.md
- packages/eds-utils/package.json
- packages/eds-utils/rollup.config.js
> 🔖Prepare release of eds-utils@0.8.0

- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
> 🐛 Autocomplete: allow option value of 0

- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/package.json
- packages/eds-core-react/rollup.config.js
> 🔖Release eds-core-react@0.32.2

- packages/eds-data-grid-react/.storybook/preview.js
- packages/eds-data-grid-react/CHANGELOG.md
- packages/eds-data-grid-react/package.json
- packages/eds-data-grid-react/pnpm-lock.yaml
- packages/eds-data-grid-react/rollup.config.js
- packages/eds-data-grid-react/src/EdsDataGrid.docs.mdx
- packages/eds-utils/pnpm-lock.yaml
resolves #2959 
made some changes to build output based on feedback about core-react 0.31.1 issues
> 🔖Release data-grid-react@0.1.0-beta.2

- packages/eds-lab-react/CHANGELOG.md
- packages/eds-lab-react/package.json
- packages/eds-lab-react/pnpm-lock.yaml
- packages/eds-lab-react/rollup.config.js
> Release eds-lab-react@0.7.1

- packages/eds-icons/CHANGELOG.md
- packages/eds-icons/package.json
- packages/eds-icons/rollup.config.js
> 🔖Release eds-icons@0.19.3

- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/package.json
- packages/eds-core-react/pnpm-lock.yaml
- packages/eds-utils/package.json
> 🔖Release eds-core-react@0.32.3 eds-utils@0.8.1

- packages/eds-core-react/src/components/Chip/Icon.tsx
> 🔥 Remove z-index from chip x-icon

- packages/eds-core-react/package.json
- packages/eds-core-react/pnpm-lock.yaml
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
- packages/eds-core-react/src/components/Autocomplete/Option.tsx
- packages/eds-core-react/src/components/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
resolves #2996 
this also changes default behaviour to open dropdown on click instead of focus to [conform to aria 1.2 recomendation](https://github.com/downshift-js/downshift/blob/master/src/hooks/MIGRATION_V8.md#usecombobox-input-click)
> ⬆️ Update to Downshift 8.x

- design-tokens/merge.js
- design-tokens/package.json
> Added script for expanding variant modes

- packages/eds-core-react/src/components/Chip/Chip.test.tsx
- packages/eds-core-react/src/components/Chip/Chip.tsx
- packages/eds-core-react/src/components/Chip/__snapshots__/Chip.test.tsx.snap
> Chips should only have hover on onClick events

- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/package.json
> 🔖 Release eds core react@0.32.4

- packages/eds-core-react/.storybook/main.js
> 📈 Storybook: added siteimprove link

- package.json
- packages/eds-core-react/package.json
- packages/eds-core-react/pnpm-lock.yaml
- packages/eds-data-grid-react/package.json
- packages/eds-data-grid-react/pnpm-lock.yaml
- packages/eds-data-grid-react/src/EdsDataGrid.tsx
- packages/eds-icons/package.json
- packages/eds-icons/pnpm-lock.yaml
- packages/eds-lab-react/package.json
- packages/eds-lab-react/pnpm-lock.yaml
- packages/eds-tokens/package.json
- packages/eds-tokens/pnpm-lock.yaml
- packages/eds-utils/package.json
- packages/eds-utils/pnpm-lock.yaml
- pnpm-lock.yaml
> ⬆️ Update typescript to 5.1.6

- packages/eds-core-react/src/components/Breadcrumbs/Breadcrumb.tsx
- packages/eds-core-react/src/components/Breadcrumbs/Breadcrumbs.tsx
- packages/eds-core-react/src/components/Breadcrumbs/__snapshots__/Breadcrumbs.test.tsx.snap
> 💄 Breadcrumbs: fix vertical alignment for icons

- packages/eds-utils/package.json
- packages/eds-utils/pnpm-lock.yaml
> 🔒️ Utils: Move babel-jest to dev-dependencies

- packages/eds-core-react/src/components/Search/Search.tsx
> 🚸Search: remove clear button when disabled

- packages/eds-core-react/stories/icons/IconPreview.docs.mdx
> 📝Improved documentation on icons

- packages/eds-core-react/package.json
- packages/eds-core-react/pnpm-lock.yaml
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
- packages/eds-core-react/src/components/Autocomplete/Option.tsx
- packages/eds-lab-react/package.json
- packages/eds-lab-react/pnpm-lock.yaml
- packages/eds-lab-react/src/components/TimePicker/TimePicker.tsx
resolves #3059 and hopefully all the other ways of triggering this infinite loop
> 🐛 Autocomplete fix crash caused by merging refs

- packages/eds-core-react/src/components/Chip/Chip.tsx
> 🐛Chip: only hover when clickable (fix error variant)

- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/package.json
- packages/eds-lab-react/CHANGELOG.md
- packages/eds-lab-react/package.json
- packages/eds-utils/CHANGELOG.md
- packages/eds-utils/package.json
> 🔖 Release eds-core-react@0.33.1, eds-utils@0.8.3, eds-lab-react@0.7.3

- packages/eds-core-react/src/components/Slider/Slider.docs.mdx
- packages/eds-core-react/src/components/Slider/Slider.stories.tsx
- packages/eds-core-react/src/components/Slider/Slider.tsx
- packages/eds-core-react/src/components/Slider/__snapshots__/Slider.test.tsx.snap
> ✨ Slider: added hideActiveTrack prop

- packages/eds-core-react/package.json
- packages/eds-core-react/pnpm-lock.yaml
- packages/eds-data-grid-react/package.json
- packages/eds-data-grid-react/pnpm-lock.yaml
- packages/eds-icons/package.json
- packages/eds-icons/pnpm-lock.yaml
- packages/eds-lab-react/package.json
- packages/eds-lab-react/pnpm-lock.yaml
- packages/eds-tokens/package.json
- packages/eds-tokens/pnpm-lock.yaml
- packages/eds-utils/package.json
- packages/eds-utils/pnpm-lock.yaml
> ⬆️ Update rollup to 4.2.0

- packages/eds-core-react/package.json
- packages/eds-core-react/pnpm-lock.yaml
- packages/eds-lab-react/package.json
- packages/eds-lab-react/pnpm-lock.yaml
> ⬆️ Update downshift + floating-UI

- SECURITY.md
resolves #3158 
using official template for public repositories from https://github.com/equinor/it-professional-network/blob/master/doc/SECURITY-template.md
> 🔒️ Added SECURITY.md

- packages/eds-core-react/src/components/Slider/Slider.tsx
- packages/eds-core-react/src/components/Slider/__snapshots__/Slider.test.tsx.snap
> 🐛Slider: Fix label visibility for styled-components v5

- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/package.json
> 🔖 Release eds-core-react@0.35.1

- packages/eds-core-react/src/components/Accordion/Accordion.docs.mdx
- packages/eds-core-react/src/components/Accordion/Accordion.types.ts
> 📝 Accordion: Update docs to explain headerlevels

- assets/woman/package.json
- assets/woman/pnpm-lock.yaml
- packages/eds-core-react/package.json
- packages/eds-core-react/pnpm-lock.yaml
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.test.tsx
- packages/eds-data-grid-react/package.json
- packages/eds-data-grid-react/pnpm-lock.yaml
- packages/eds-data-grid-react/src/tests/EdsDataGrid.test.tsx
> ⬆️ @tanstack/react-virtual@3.0.1, browser-sync@3.0.2

- packages/eds-core-react/package.json
- packages/eds-core-react/pnpm-lock.yaml
- packages/eds-lab-react/package.json
- packages/eds-lab-react/pnpm-lock.yaml
> ⬆️ update downshift to 8.3.1

- packages/eds-data-grid-react/src/components/DebouncedInput.tsx
> 💄make autocomplete multiline

- packages/eds-core-react/src/components/InputWrapper/HelperText/HelperText.tsx
> 💄HelperText: allow line break character to work

- packages/eds-core-react/src/components/Slider/Slider.tsx
> 🐛 Slider: fix onChangeCommitted with touch input

- packages/eds-data-grid-react/src/EdsDataGrid.stories.tsx
- packages/eds-data-grid-react/src/EdsDataGrid.tsx
- packages/eds-data-grid-react/src/tests/utils.test.ts
- packages/eds-data-grid-react/src/utils.ts
Enables 100% width without requiring any custom code
@yusijs
> 🐛 Enable contain strict when width and height is provided

- .prettierignore
> 🚨 add icons data.ts file to .prettierignore

- packages/eds-data-grid-react/src/EdsDataGrid.docs.mdx
- packages/eds-data-grid-react/src/EdsDataGrid.stories.tsx
- packages/eds-data-grid-react/src/EdsDataGrid.tsx
- packages/eds-data-grid-react/src/EdsDataGridProps.ts
- packages/eds-data-grid-react/src/stories/columns.tsx
> feat(data-grid): Expose expansion-state controls

- package.json
- packages/eds-core-react/package.json
- packages/eds-core-react/pnpm-lock.yaml
- packages/eds-data-grid-react/package.json
- packages/eds-data-grid-react/pnpm-lock.yaml
- packages/eds-lab-react/package.json
- packages/eds-lab-react/pnpm-lock.yaml
- packages/eds-lab-react/src/components/DatePicker/DatePicker.stories.tsx
- packages/eds-lab-react/src/components/DatePicker/DatePicker.tsx
- packages/eds-utils/package.json
- packages/eds-utils/pnpm-lock.yaml
- pnpm-lock.yaml
> ⬆️ Update dependencies in packages

- packages/eds-data-grid-react/CHANGELOG.md
- packages/eds-data-grid-react/package.json
> 🔖Release eds-data-grid-react@0.4.0

- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/package.json
- packages/eds-lab-react/CHANGELOG.md
- packages/eds-lab-react/package.json
> 🔖 Release eds-core-react@0.36.1, eds-lab-react@0.7.6

- packages/eds-lab-react/CHANGELOG.md
- packages/eds-lab-react/README.md
- packages/eds-lab-react/src/components/DatePicker/DatePicker.stories.tsx
- packages/eds-lab-react/src/components/DatePicker/DatePicker.tsx
> 💥 remove default DatePicker style import from component

- packages/eds-data-grid-react/src/EdsDataGrid.docs.mdx
- packages/eds-data-grid-react/src/EdsDataGrid.stories.tsx
- packages/eds-data-grid-react/src/components/Filter.tsx
- packages/eds-data-grid-react/src/components/FilterWrapper.tsx
- packages/eds-data-grid-react/src/components/SortIndicator.tsx
- packages/eds-data-grid-react/src/components/TableHeaderCell.tsx
- packages/eds-data-grid-react/src/index.ts
- packages/eds-data-grid-react/src/stories/columns.tsx
- packages/eds-data-grid-react/src/stories/data.ts
- packages/eds-data-grid-react/src/tanstack.d.ts
- packages/eds-data-grid-react/src/tests/Filter.test.tsx
> Datagrid: Add possibility for custom filters

- .devcontainer/devcontainer.json
> Update node in Codespaces

- packages/eds-core-react/src/components/Tabs/TabList.tsx
> 🔥 Tabs: Remove invalid props from TabListProps

- packages/eds-core-react/src/components/Menu/MenuItem.tsx
resolves #3394 
I believe this was an oversight when making the component and not intended interaction design
> 💄Menu: focus-ring from :focus to :focus-visible

- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/package.json
- packages/eds-core-react/src/components/Datepicker/DatePicker.stories.tsx
- packages/eds-core-react/src/components/Datepicker/DatePicker.tsx
- packages/eds-core-react/src/components/Datepicker/DateRangePicker.tsx
- packages/eds-core-react/src/components/Datepicker/calendars/CalendarCell.tsx
- packages/eds-core-react/src/components/Datepicker/calendars/CalendarHeader.tsx
- packages/eds-core-react/src/components/Datepicker/fields/DateRangeField.tsx
- packages/eds-core-react/src/components/Datepicker/fields/FieldWrapper.tsx
- packages/eds-core-react/src/components/TextField/TextField.docs.mdx
- packages/eds-lab-react/src/components/DatePicker/DatePicker.stories.tsx
resolves #3402
needs final approval to release datepicker
> 🔖Release eds-core-react@0.37.0

- packages/eds-core-react/package.json
- packages/eds-core-react/src/components/Progress/Circular/CircularProgress.tsx
- packages/eds-core-react/src/components/Progress/Linear/LinearProgress.tsx
- packages/eds-data-grid-react/package.json
- packages/eds-lab-react/package.json
- packages/eds-utils/package.json
- pnpm-lock.yaml
styled-components released an update that fixes types and stuff that was broken for a while and required us to pin an  older version
> ⬆️ Styled-components@6.1.11

- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
resolves #3434 
also fixes parts of #3430 but there is a bug or behaviour in downshift i have not figured out yet to fully resolve this
> 🐛Autocomplete: fix kb-navigation after scrolling

- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/package.json
- packages/eds-lab-react/CHANGELOG.md
- packages/eds-lab-react/package.json
- packages/eds-utils/CHANGELOG.md
- packages/eds-utils/package.json
resolves #3432 
also release eds-utils@0.8.5 and eds-lab-react@0.7.7 with unly dependency updates
> 🔖Release eds-core-react@0.38.0

- packages/eds-core-react/package.json
- packages/eds-data-grid-react/package.json
- packages/eds-lab-react/package.json
- packages/eds-utils/package.json
> 📌 Bump required styled-components version to 5.1

- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/package.json
> 🔖 Release eds-core-react@0.39.0

- packages/eds-data-grid-react/CHANGELOG.md
- packages/eds-data-grid-react/package.json
- packages/eds-data-grid-react/src/EdsDataGridProps.ts
> 🔖Release eds-data-grid-react@0.6.0

- packages/eds-core-react/src/components/Datepicker/fields/DateSegment.tsx
> 💄datePicker: use correct token for text color

- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
> 🚸Autocomplete: return focus to input on clear

- packages/eds-core-react/src/components/Datepicker/index.ts
> 🐛 export DatePickerProps type

- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/package.json
> 🔖 Release eds-core-react@0.40.0

- packages/eds-core-react/package.json
- packages/eds-data-grid-react/package.json
- packages/eds-lab-react/package.json
- packages/eds-utils/package.json
- pnpm-lock.yaml
- scripts/figma-broker/package.json
> ⬆️ Updated prod dependencies

- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/package.json
> 🔖 Release eds-core-react@0.40.1

- .github/workflows/_setup.yml
- .npmrc
- pnpm-lock.yaml
> ⬆️ pnpm v9

- packages/eds-core-react/src/components/Datepicker/DateRangePicker.tsx
> 🐛 DateRangePicker: Add missing ...props spread

- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/package.json
> 🔖Release eds-core-react@0.41.0

- packages/eds-core-react/src/components/Button/ToggleButton/ToggleButton.docs.mdx
- packages/eds-core-react/src/components/Button/ToggleButton/ToggleButton.stories.tsx
- packages/eds-core-react/src/components/Button/ToggleButton/ToggleButton.tsx
> 🧑‍💻Button.Toggle: allow wrapped Button as child

- packages/eds-core-react/src/components/Snackbar/Snackbar.stories.tsx
- packages/eds-core-react/src/components/Snackbar/Snackbar.tsx
> 🐛Snackbar: fix setTimeout restarting every render

- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/package.json
> 🔖Release eds-core-react@0.41.1

- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/package.json
> 🔖 Release eds-core-react@0.41.2

- packages/eds-core-react/src/components/Popover/Popover.stories.tsx
- packages/eds-core-react/src/components/Popover/Popover.test.tsx
- packages/eds-core-react/src/components/Popover/Popover.tsx
- packages/eds-core-react/src/components/Popover/__snapshots__/Popover.test.tsx.snap
and deprecated withinPortal
resolves #3597
> ✨Popover: implement native [popover]

- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
> 🔥 Autocomplete: remove disablePortal prop

- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/package.json
- packages/eds-data-grid-react/CHANGELOG.md
- packages/eds-data-grid-react/package.json
> 🔖 Release eds-core-react@0.41.3, eds-data-grid-react@0.6.2

- packages/eds-core-react/src/components/Autocomplete/Autocomplete.stories.tsx
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
> 🐛 Autocomplete: Update selected state when changed programmatically

- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/package.json
> 🔖Release eds-core-react@0.41.4

- packages/eds-core-react/src/components/Scrim/Scrim.docs.mdx
- packages/eds-core-react/src/components/Scrim/Scrim.stories.tsx
- packages/eds-core-react/src/components/Scrim/Scrim.tsx
> 🐛Scrim: use own useHideBodyScroll instead of f-ui

- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/package.json
> 🔖 Release eds-core-react@0.41.5

- packages/eds-core-react/src/components/Datepicker/DatePicker.spec.tsx
- packages/eds-core-react/src/components/Datepicker/DatePicker.tsx
- packages/eds-core-react/src/components/Datepicker/DateRangePicker.tsx
- packages/eds-core-react/src/components/Datepicker/Datepicker.docs.mdx
- packages/eds-core-react/src/components/Datepicker/props.ts
- packages/eds-core-react/src/components/Datepicker/utils/useGetLocale.ts
> feat(datepickers): Enable setting locale from prop. 

- packages/eds-core-react/package.json
- packages/eds-core-react/src/components/Popover/Popover.tsx
> 🐛 Popover: Attempt to fix flicker issue

- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/package.json
> 🔖Release eds-core-react@0.42.1

- packages/eds-data-grid-react/src/EdsDataGrid.tsx
- packages/eds-data-grid-react/src/EdsDataGridProps.ts
Exposes `enableSortingRemoval` flag
https://tanstack.com/table/v8/docs/guide/sorting#sorting-removal
edit: resolves #3628
> 🎨 Expose enableSortingRemoval flag to EdsDataGrid

- packages/eds-core-react/package.json
- packages/eds-data-grid-react/package.json
- packages/eds-lab-react/package.json
- packages/eds-utils/package.json
- pnpm-lock.yaml
> ➖ Remove unused babel-loader devDependency

- packages/eds-data-grid-react/CHANGELOG.md
- packages/eds-data-grid-react/package.json
> 🔖 Release eds-data-grid@0.7.1

- packages/eds-core-react/src/components/Tooltip/Tooltip.tsx
> 🐛Tooltip: use portal to render element in body

- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/package.json
- packages/eds-data-grid-react/CHANGELOG.md
- packages/eds-data-grid-react/package.json
> 🔖 Release eds-core-react@0.42.2 eds-data-grid-react@0.7.2

- packages/eds-data-grid-react/CHANGELOG.md
- packages/eds-data-grid-react/package.json
> 🔖Release eds-data-grid-react@0.7.3

- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
resolves https://github.com/equinor/design-system/issues/3678
> 🎨 Expand Autocomplete api with onClear

- .github/workflows/_setup.yml
> feat: :sparkles: set the slack url as optional and disable log to slack

- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/package.json
- packages/eds-data-grid-react/CHANGELOG.md
- packages/eds-data-grid-react/package.json
> 🔖Release eds-core-react@0.42.4, eds-data-grid-react@0.7.4

- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/package.json
> 🔖 Release eds-core-react@0.42.5

- packages/eds-core-react/src/components/Tooltip/Tooltip.docs.mdx
- packages/eds-core-react/src/components/Tooltip/Tooltip.tsx
- packages/eds-core-react/src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
> 🧑‍💻Tooltip: added "eds-tooltip" class

- packages/eds-core-react/package.json
- packages/eds-core-react/src/components/Tooltip/Tooltip.tsx
resolves #3694 
I will make a `next` release from this branch first so the reporter of the bug can test if the issue is resolved
> 🐛 Tooltip: attempt to fix flicker issue

- packages/eds-core-react/package.json
- packages/eds-data-grid-react/package.json
- pnpm-lock.yaml
> ⬆️ prod dependencies

- packages/eds-core-react/src/components/SideSheet/SideSheet.tsx
- packages/eds-core-react/src/components/SideSheet/__snapshots__/SideSheet.test.tsx.snap
> 🐛 Sidesheet: fix shrinking close button

- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/package.json
> 🔖 Release eds-core-react@0.44.0

- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/package.json
- packages/eds-data-grid-react/CHANGELOG.md
- packages/eds-data-grid-react/package.json
- packages/eds-utils/CHANGELOG.md
> 🔖 Release eds-core-react@0.45.0, eds-utils@0.8.7, eds-data-grid-react@0.7.6

- packages/eds-data-grid-react/src/EdsDataGrid.tsx
Resolves #3779 
Disclaimer: this is my first fork & pull-request, please let me know if I should do things differently 😇
> Add class to pagination wrapper

- packages/eds-core-react/src/components/Autocomplete/Autocomplete.stories.tsx
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
- packages/eds-core-react/src/components/Table/HeaderCell/HeaderCell.tsx
- packages/eds-core-react/src/components/Table/__snapshots__/Table.test.tsx.snap
- packages/eds-core-react/src/components/TextField/TextField.tsx
- packages/eds-data-grid-react/src/EdsDataGrid.stories.tsx
- packages/eds-data-grid-react/src/EdsDataGrid.tsx
- packages/eds-data-grid-react/src/components/FilterWrapper.tsx
- packages/eds-data-grid-react/src/components/Resizer.tsx
- packages/eds-data-grid-react/src/components/TableHeaderCell.tsx
- packages/eds-data-grid-react/src/tests/EdsDataGrid.test.tsx
update resizer component to prevent mouse events from triggering sorting
> fix(eds-core-react, eds-data-grid-react): :bug: prevent triggering sorting on resize

- packages/eds-data-grid-react/src/EdsDataGrid.docs.mdx
> fix(eds-data-grid-react): :bug: Fix docs page error

- package.json
- packages/eds-core-react/package.json
- packages/eds-data-grid-react/package.json
- packages/eds-lab-react/package.json
- packages/eds-tokens-build/package.json
- packages/eds-tokens-sync/package.json
- packages/eds-utils/package.json
- pnpm-lock.yaml
This closes current Snyk and dependabot PRs
> chore: :arrow_up: Upgrade dependencies

- packages/eds-core-react/src/components/Autocomplete/Option.tsx
> feat(eds-core-react): :sparkles: Export Autocomplete Option Label

- package.json
- packages/eds-core-react/src/components/Slider/Slider.tsx
- packages/eds-core-react/src/components/Slider/__snapshots__/Slider.test.tsx.snap
> fix(eds-core-react): 🐛 Fix slider track disappearing on hover

- packages/eds-data-grid-react/src/components/DebouncedInput.tsx
- packages/eds-data-grid-react/src/tests/Filter.test.tsx
> feat(eds-data-grid-react): 🔥 remove redundant placeholder in DebouncedInput

- packages/eds-core-react/src/components/Banner/Banner.docs.mdx
- packages/eds-core-react/src/components/Banner/Banner.stories.tsx
- packages/eds-core-react/src/components/Banner/BannerMessage.tsx
> feat(eds-core-react): ✨ Banner.Message - Allow ReactNode as children

- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/package.json
- packages/eds-data-grid-react/CHANGELOG.md
- packages/eds-data-grid-react/package.json
> chore(eds-core-react, eds-data-grid-react): 🔖 Release eds-core-react@0.46.0 and eds-data-grid-react@0.8.0

- packages/eds-core-react/src/components/Autocomplete/Autocomplete.docs.mdx
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.stories.tsx
Related to #3812 
Just wanted to add an example with the new `totalOptions` prop ✨
> docs(eds-core-react): 📝 Update Autocomplete story

- packages/eds-core-react/src/components/Autocomplete/AddNewOption.tsx
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.stories.tsx
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.test.tsx
Resolves #3794 
Adding to #3833
> feat(eds-core-react): ✨ enhance Autocomplete onAddNewOption - stories, tests, and accessibility

- packages/eds-core-react/package.json
- packages/eds-data-grid-react/package.json
- packages/eds-tokens-sync/package.json
- pnpm-lock.yaml
Resolves #3859 
Closing snyk PRs
> chore: ⬆️ Upgrade dependencies

- apps/design-system-docs/docs/components/Inputs/Button.md
- apps/design-system-docs/docs/components/Inputs/Text_field.md
- apps/design-system-docs/docs/components/Navigation/Tabs.md
update note syntax for accessibility in Button, TextField,…and Tabs documentation
Fix adminitions
> fix(design-system-docs): 📝 update note syntax for accessibility in Button, TextField
