- libraries/core-react/src/Button/Button.jsx
Had a typo in my previous branch.
`12px` corrected to `8px` grid gap (gap between icons and text inside `Button`)
> Grid gap correction

- apps/storefront/package.json
Bumping version number to `1.0.0-beta` to have the [badge](https://github.com/equinor/design-system/issues/395) show correct version number.
> Bump storefront redesign version

- apps/storybook-react/.eslintrc.yaml
- package.yaml
- Sets eslint error level temporarily to warn
- Disables the no-default rule for the stories (from 101 to 69 ~errors~ warnings)
- Adds eslint shortcuts to root package.yaml
- `pnpm run lint` only includes the file suffixes (js and jsx) and now expects a path
_NB! The node_modules in the root must be installed._
**Lint some folder one-off**
```sh
pnpm run lint ./libraries/some-sub-folder
```
**Lint all the things** 🤘 
```sh
pnpm run lint:all
```
**Lint the stories**
```sh
pnpm run lint:storybook
```
related to #403
> Set eslint error level to warn for stories

- libraries/core-react/src/Table/Head.jsx
Table header text changed from center aligned to left aligned
**Edit:** resolves #407
> Bugfix - Left aligned table header text

- apps/storefront/pnpm-lock.yaml
- apps/storefront/src/components/ComponentStatus/ComponentStatus.jsx
Removes style overrides of table component as this is now fixed in #454
> Don’t override table styles

- apps/storefront/src/components/ComponentStatus/ComponentStatus.jsx
Unfortunate typo here that results in table text being 12.25px instead of 14px
> Use rem for font-size in storefront component table

- apps/storybook-react/stories/Typography.stories.jsx
- libraries/core-react/src/Typography/README.md
- libraries/core-react/src/Typography/Typography.jsx
- libraries/core-react/src/Typography/Typography.test.jsx
- libraries/core-react/src/Typography/Typography.tokens.js
resolves #299 
Done some updates on usage with `Typography` component for easier use with other components and standalone.
Started on documentation here, [README](https://github.com/mimarz/design-system/tree/update/typography-component/libraries/core-react/src/Typography)
Other notable changes
* Children is no longer mandatory
* Removed `margin:0` from component, but its still present in `typographyTemplate` so no margins still as of now
* Kept props `bold`, `italic` and `link` for backwards compatibility and typography lookup (Looking at you `body_short_link` 👀)
* Buuuunch of test ✅
* Updated component structure to as is now in EDS (forwardRef, .tokens etc.)
> Update Typography component

- apps/figma-broker/.eslintrc.yaml
Temporarily sets Eslint error levels to warn in Figma broker to prevent builds from failing
> Set error level to warn in Figma broker

- libraries/core-react/src/Button/Button.jsx
Fixes #465
* Workaround for missaligment inside button using `css-grid` on Webkit browsers
* Fixed  colorfull 🦄  border on buttons on Webkit browsers
> Button content alignments fix for Webkit browsers

- apps/storybook-react/stories/Tooltip.stories.jsx
- libraries/core-react/src/Button/Button.jsx
- libraries/core-react/src/Tabs/Tab.jsx
- libraries/core-react/src/Tooltip/Tooltip.jsx
Mouse Events on disabled elements are buggy.
[This is a known issue on Safari and Chrome browsers.](https://github.com/facebook/react/issues/19419) Testing in Firefox gives us the desired outcome.
Trying to find a workaround that goes for all browsers...
> Trigger Tooltip on disabled elements

- CODEOWNERS
Adding Wenche and Frida to CODEOWNERS means every time we make a pull request we’re all added as reviewers by default for everything but the documentation – which is owned by @BeckyBrekke.
> Add Wenche and Frida to codeowners

- apps/storefront/docs/updates/release-information/known-issues.mdx
- apps/storefront/src/gatsby-theme-docz/components/MainContainer/index.js
In [production ](https://eds.equinor.com) pages that are in drafts mode are hidden, while they're visible in [development](https://eds-storefront-development.azurewebsites.net). This pr makes sure tabs that link to pages in drafts mode behave in the same way.
> Hide drafts tabs in the storefront

- apps/storybook-react/stories/Snackbar.stories.jsx
- libraries/core-react/src/Snackbar/Snackbar.jsx
- libraries/core-react/src/Snackbar/Snackbar.tokens.js
fixes #535 
The color is not correct on this branch as updated color tokens are part of tokens release v0.4.0 #536 with correct color
> Use correct color token for action in snackbar

- apps/storybook-react/stories/Tabs.stories.jsx
- libraries/core-react/src/Tabs/TabList.jsx
- libraries/core-react/src/Tabs/TabPanels.jsx
fixes #539
When using Styled Components, Emotion or any other library who wraps the React component for styling changes type when checking on propTypes.
Loosened up checking so that its possible to use these to style compound components in `Tabs`
> Loosened up type checking for Tabs components

- apps/storybook-react/stories/Menu.stories.jsx
- libraries/core-react/src/Menu/Menu.jsx
- libraries/core-react/src/_common/hooks/index.js
- libraries/core-react/src/_common/hooks/useOutsideClick.js
* Added simple `outsideClick` hooks for future use
* `onClose` will now be triggered when clicking outside of the Menu
resolves #548
> Added support for close on Menu when clicking outside

- apps/storybook-react/stories/Icon.stories.jsx
- libraries/core-react/src/Icon/Icon.jsx
- libraries/core-react/src/Icon/Icon.test.jsx
* Use `data` property to directly set icon data being rendered
* Provided data object must follow [icon object structure](https://github.com/equinor/design-system/tree/develop/libraries/icons#example-of-javascript-object-data)
* Code housekeeping
* Fixed malformed proptypes description (even though we are changing it soon 🤪)
resolves #584
> Support for directly setting icon on Icon component

- libraries/icons/CHANGELOG.md
- libraries/icons/package.json
- New icon as alternative to `filter` (funnel) called `filter_alt`
- Tweaked svg data for `info_circle` & `list`
> Release icons@0.4.0

- apps/storybook-react/stories/Table.stories.jsx
- libraries/core-react/src/Table/Cell.jsx
- libraries/core-react/src/Table/Head.jsx
- libraries/core-react/src/Table/Table.tokens.js
* Header background is applied to `Head` instead of `Cell` when as is `th`
* Will now feel more native when `thead` is stretched to fit table width
* Created `Table.tokens` file and moved relevant code there
* Simplified token extraction from`table` token
* Added example with fixed header in stories
resolves #610
> Move application of header background to thead instead of Cell

- libraries/core-react/CHANGELOG.md
- libraries/core-react/package.json
- libraries/core-react/src/Icon/README.md
- Fixed `onClose` handler not being called when `MenuItem` was used inside `MenuSection` ([#546](https://github.com/equinor/design-system/issues/546))
- Fixed focus showing when clicking on `MenuItem` ([#544](https://github.com/equinor/design-system/issues/544))
- Fixed an issue where `Divider` did not stretch to full width ([#608](https://github.com/equinor/design-system/issues/608))
- Fixed `Head` styling when `Table` is set to `width: 100%` ([#610](https://github.com/equinor/design-system/issues/610))
- Added outside click support for closing `Menu`. Outside clicks will now call the `onClose` handler function. ([#548](https://github.com/equinor/design-system/issues/548))
- Added `data` property to `Icon` component to easily compose icon to be rendered. …
> Release eds-core-react@0.6.2

- libraries/core-react/package.json
- libraries/core-react/pnpm-lock.yaml
- libraries/core-react/rollup.config.js
- libraries/core-react/tsconfig.json
- tsconfig.base.json
* Updated `base.tsconfig.json` with `skipLibCheck` as [recommended](https://www.npmjs.com/package/@tsconfig/recommended)
* Removed `babel-plugin-react-docgen-typescript` as `Icon` typescript variant ran into [this bug](https://github.com/strothj/babel-plugin-react-docgen-typescript/pull/21) which has not been approved yet. Does not seem to be [maintained](https://github.com/strothj/babel-plugin-react-docgen-typescript/issues/18) anymore either
Issue for finding alternative #622
> Typescript config tweaks

- libraries/core-react/package.json
- libraries/core-react/pnpm-lock.yaml
- libraries/core-react/rollup.config.js
- libraries/core-react/src/Menu/Menu.context.jsx
- libraries/core-react/src/Menu/Menu.jsx
- libraries/core-react/src/Menu/Menu.test.jsx
- libraries/core-react/src/Menu/MenuItem.jsx
- libraries/core-react/src/Menu/MenuList.jsx
- libraries/core-react/src/Menu/MenuSection.jsx
- libraries/core-react/src/Menu/index.jsx
- libraries/core-react/src/Paper/Paper.jsx
- libraries/core-react/src/index.ts
- libraries/core-react/tsconfig.json
* Turns out the official `@rollup/plugin-typescript` plugin still has some [issues...](https://github.com/rollup/plugins/issues?q=is%3Aissue+is%3Aopen+typescript).
* Switching to `rollup-plugin-typescript2` works 👍
* Added missing `ts-no-checks` for now since we had to change `index.js` file to `.ts` for declarations to work
* Declarations are saved under `dist/types` as they are not bundled into one file and thus follow the same folder structure as is under `/src` but as type files
resolves #624
> Added typescript declarations to core-react

- libraries/core-react/src/Banner/BannerActions.jsx
- libraries/core-react/src/Card/CardMedia.jsx
Fixes #603 - missing spacing on left side of middle variant
Also fixes the full-width variant where spacing was applied on the right side of the media
> 🐛 fix spacing bugs on CardMedia

- apps/storefront/src/components/EditPageOnGithub.jsx
- apps/storefront/src/gatsby-theme-docz/components/MainContainer/index.js
Resolves #620 
In addition to fixing the dead links, I also took the liberty of refactoring the `EditPageOnGithub` component to use the EDS icon and converted the inline styling to styled-components.
> fix link to edit page on github in storefront

- libraries/core-react/package.json
- libraries/core-react/pnpm-lock.yaml
- libraries/core-react/rollup.config.js
The babel-plugin-react-docgen has been updated and works as expected as far as I can see. It doesn’t have a maintainer at the moment, so long term we should either take on maintainer responsibility or find a better solution. I expect there will be more suitable tools available once we teak the leap to typescript for the storybook as well as the components.
resolves #622
> Bring back the docgen plugin

- libraries/core-react/src/Accordion/Accordion.jsx
Adds a guard clause to the rendering of AccordionItems to handle `null`, `undefined`, `false` values passed as Accordion children
Resolves #688
> fix: Accordion can't handle null value as child

- libraries/core-react/src/Banner/Banner.test.jsx
- libraries/core-react/src/Progress/Circular/CircularProgress.test.tsx
- libraries/core-react/src/Progress/Dots/DotProgress.test.tsx
- libraries/core-react/src/Progress/Linear/LinearProgress.test.tsx
- libraries/core-react/src/Progress/Star/StarProgress.test.tsx
partially fixes #708 
Changed in files that are not touched yet.
Follow has `..` imports which needs to be fixed in respective PRs.
* `Card.test.jsx` in #699 
* `Popover.test`, `PopoverItem` & `PopoverTitle` in #695 
* `TableOfContents.jsx` in #689
> Change .. imports to direct

- libraries/core-react/src/Accordion/AccordionItem.tsx
Related to this issue: https://github.com/equinor/design-system/issues/677
This change lets users change the AccordionItem expanded state from outside the component, by programatically changing the `isExpanded`-prop.
----
Made a new PR for typescript branch.
> Made AccordionItem toggleable through "isExpanded"

- libraries/core-react/src/Accordion/AccordionHeader.tsx
- libraries/core-react/src/Menu/MenuItem.tsx
- libraries/core-react/src/Menu/MenuList.tsx
- libraries/core-react/src/Menu/MenuSection.tsx
- libraries/core-react/src/Popover/Popover.tsx
resolves #726
* Removed usages of checking using `displayName === "some-components-displayName`
* Simplified `Popover` children splitting from its anchor element
> Children type checking

- libraries/core-react/src/Accordion/Accordion.tsx
added fix: Accordion can't handle null value as child #703 to typescript branch
resolves #709
> Bugfix in develop moved to typescript branch

- apps/storybook-react/stories/Divider.stories.tsx
- libraries/core-react/src/Divider/Divider.tsx
- libraries/core-react/src/Divider/index.ts
- The Divider component now uses a named function instead of an arrow function
- The component and it’s type is re-exported as `*`, which gets rid of the error message that type cannot be found
I’ve added some Eslint exceptions to the story, but these issues are something we have to discuss
Part of #735
> 🎨 Improve story for Divider

- apps/storybook-react/stories/.eslintrc.yaml
Extends the eslintconfig from root, but turns off the default exports error since storybook relies on default exports in the stories.
> 🔧 Lint stories

- libraries/core-react/package.json
- libraries/core-react/pnpm-lock.yaml
- libraries/core-react/rollup.config.js
- libraries/core-react/src/Button/Button.tsx
- libraries/core-react/src/index.ts
* Turns out `focus-visible` does not work being loaded via the `rollup-plugin-polyfill` anymore / with typescript?
* Fixed missing default tabIndex for `Button`
> Fix focus-visible & button focus

- libraries/core-react/src/Accordion/index.ts
- libraries/core-react/src/Banner/index.ts
- libraries/core-react/src/Breadcrumbs/index.ts
- libraries/core-react/src/Card/index.ts
- libraries/core-react/src/List/index.ts
- libraries/core-react/src/Popover/index.ts
- libraries/core-react/src/Table/Table.tsx
- libraries/core-react/src/Table/index.ts
- libraries/core-react/src/TableOfContents/index.ts
- libraries/core-react/src/Tabs/index.ts
- libraries/core-react/src/TopBar/index.tsx
> ♻️  Export conform for compound components

- libraries/core-react/package.json
- libraries/core-react/rollup.config.js
> eds-core-react bundle improvements 

- apps/storybook-react/stories/Table.stories.jsx
- libraries/core-react/src/Table/Caption.jsx
- libraries/core-react/src/Table/Table.test.jsx
- libraries/core-react/src/Table/index.js
An attempt in solving issue #621. Also added a simple test file for Table, covering the properties related to "Caption".
> Add table caption

- libraries/core-react/package.json
- libraries/core-react/pnpm-lock.yaml
Moved correct dependencies to `dev` and change `react` to be a minimum instead of up to minor releases.
This was done due to problems with resolving react versions and leaking dependencies used for development to consumers. 
So in short the following packages was installed for any user installing `eds-core-react`.... 🙈
*  @testing-library/react-hooks
* @types/lodash
* csstype
* focus-visible
* lodash
> eds-core-react dependencies 

- libraries/core-react/package.json
- libraries/core-react/pnpm-lock.yaml
- libraries/icons/package.json
- libraries/icons/rollup.config.js
- libraries/tokens/commonjs/package.json
- libraries/tokens/package.json
- libraries/tokens/rollup.config.js
* `tokens` and `icons` have `cjs` bundle as main now.
* Removed `type` flag on `icons` & `tokens` as this flag is meant for consuming applications as[ i've understood](https://nodejs.org/docs/latest-v15.x/api/esm.html#esm_enabling). Meaning if you make a new application and set `type="module"` in `package.json`, it will then load the bundle under `"module"` in our library.
* Set all peer-deps to have a min.version approach
> Simplify dependencies and package type

- libraries/core-react/.size-snapshot.json
- libraries/core-react/package.json
- libraries/core-react/pnpm-lock.yaml
- libraries/core-react/rollup.config.js
- libraries/icons/.size-snapshot.json
- libraries/icons/package.json
- libraries/icons/pnpm-lock.yaml
- libraries/icons/rollup.config.js
- libraries/tokens/.size-snapshot.json
- libraries/tokens/package.json
- libraries/tokens/pnpm-lock.yaml
- libraries/tokens/rollup.config.js
Added plugins to help us track bundle size (normal + tree-shaked) and delete dist folder before build to avoid faulty publishes.
Plugins
* [rollup-plugin-delete](https://github.com/vladshcherbin/rollup-plugin-delete)
* [rollup-plugin-size-snapshot](https://github.com/TrySound/rollup-plugin-size-snapshot)
> ➕ New Rollup plugins for libraries

- libraries/core-react/src/Card/CardActions.tsx
Type error in CardActions is causing `core-react` build to fail now for some reason...
> 🐛 Fixed CardActions type error

- apps/storefront/Dockerfile
- apps/storefront/package.json
- apps/storefront/pnpm-lock.yaml
- package.yaml
- Installs dependencies from npm in Docker instead of hard linking internally
- Uses the @next release of the EDS components
> ⬆️ Use @next in the Storefront

- apps/storybook-react/stories/TextField.stories.tsx
Solves #871
Notes:
- `rows` prop was always included in `InputHTMLAttributes` but I added it manually to the Story to have it documented. It's probably not intuitive for all users that these default attributes are included as well as the custom ones.
- Regarding the `errorMsg` prop, I don't find that it deprecated on Typescript migration. It was already labeled `helperText`. I didn't take more time to research this, but I guess they have used this prop before and now after TS support it's not allowed.
- `variant` prop in Icon has never been a case before either, so I guess the same happened as with the `errorMsg` mentioned above
So the only 'fix' here is adding rows prop to `TextField` story to document multiline input.
> 📝 Added 'rows' to TextField prop table 

- libraries/core-react/src/components/TextField/Input/Input.tokens.ts
- libraries/core-react/src/components/TextField/Input/Input.tsx
Avoiding height of 37px with border. Add the correct color to the tokens. The color in use was not the correct one from Figma, so changed that as well.
> ♻️  Fix some of the minor issues discovered by working on the Select

- libraries/icons/CHANGELOG.md
- libraries/icons/package.json
- Types, as part of the [Typescript Milestone](https://github.com/equinor/design-system/milestone/7?closed=1)
- Changed module types for better support with `commonjs` and `esm`. Using the `<some-eds-npm-package>/commonjs` path on packages should no longer be needed and will be deprecated in the future ([#887](https://github.com/equinor/design-system/issues/887))
Resolves #909
> Release eds-icons@0.5.0

- libraries/tokens/CHANGELOG.md
- libraries/tokens/package.json
- Types, as part of the [Typescript Milestone](https://github.com/equinor/design-system/milestone/7?closed=1)
- Updated line height for Cell Text (`Table`) tokens and text color for `Snackbar` [#824](https://github.com/equinor/design-system/issues/824)
- Changed module types for better support with `commonjs` and `esm`. Using the `<some-eds-npm-package>/commonjs` path on packages should no longer be needed and will be deprecated in the future ([#887](https://github.com/equinor/design-system/issues/887))
Resolves #908
> Release eds-tokens@0.5.0

- libraries/core-react/CHANGELOG.md
- libraries/core-react/package.json
- Types, as part of the [Typescript Milestone](https://github.com/equinor/design-system/milestone/7?closed=1)
- `NativeSelect` component ([#509](https://github.com/equinor/design-system/issues/509))
- `Table` caption ([#621](https://github.com/equinor/design-system/issues/621))
- `isExpanded` prop to control `Accordion` externally ([#677](https://github.com/equinor/design-system/issues/677))
- Added a guard clause to handle null values for `Accordion` children ([#688](https://github.com/equinor/design-system/issues/688))
- `CardMedia` spacing bug ([#603](https://github.com/equinor/design-system/issues/603))
- Added props spread to `BannerAction` ([#478](https://github.com/equinor/design-system/issues/478))
- `Pagination` bug ([#647](https://github.com/equinor/design-system/issues/647))
- …
> Release eds-core-react@0.7.0

- apps/storefront/src/components/EditPageOnGithub.jsx
When clicking “edit in Github” the url should lead to the document in the documentation branch
> Change url to documentation

- libraries/tokens/CHANGELOG.md
- libraries/tokens/package.json
Part of #965 
- Removed component tokens in favour of the base tokens approach
- `Table`
- `Button`
- Danger
- Disabled
- Primary
- Secondary
> Release eds-tokens

- README.md
- apps/storefront/docs/getting-started/developers/introduction.mdx
In the Readme and in the storefront docs the code for creating a React button was wrong
> 📝 Replace non-working React code

- libraries/core-react/src/components/SelectionControls/Checkbox/Input.tsx
- libraries/core-react/src/components/SelectionControls/Radio/Radio.tsx
- libraries/core-react/src/components/SelectionControls/Switch/InputWrapper.tsx
Solves #987 
Using [CSS media query](https://medium.com/@mezoistvan/finally-a-css-only-solution-to-hover-on-touchscreens-c498af39c31c) approach to check if device has a mouse before applying hover styles
> 🐛 Stuck hover effects on touch devices

- apps/storybook-react/stories/Table.stories.tsx
- libraries/core-react/src/components/Table/Body.tsx
- libraries/core-react/src/components/Table/Caption.tsx
- libraries/core-react/src/components/Table/Cell/index.tsx
- libraries/core-react/src/components/Table/Head.tsx
- libraries/core-react/src/components/Table/Inner.context.tsx
- libraries/core-react/src/components/Table/Row.tsx
- libraries/core-react/src/components/Table/Table.test.tsx
- libraries/core-react/src/components/Table/Table.types.ts
- libraries/core-react/src/components/Table/index.tsx
resolves #997 
* Created a `Inner.context`, which determines which variant `Cell` within that context are rendered as. 
* ⚠️ Removed property "as", as its no longer needed and causes bugs when trying to extend `Cell` with styling using `styled()`
* Exposed typings for the other `Table` components as needed when "extending" our components with additional styling. 
* Added icon on hover for sortable cells in example
> Table cell improvements

- apps/storybook-react/package.json
- apps/storybook-react/pnpm-lock.yaml
#757 removed addon-actions as the package is a part of addon-essentials. However, I missed that we use i directly in some components, like in the `Menu`. I didn't catch this error previously. 😊  
I can't see how the [new way to use actions](https://storybook.js.org/docs/react/essentials/actions) will solve the way we use them, since we're not on the actual parent component. Feels like we still need what storybook mentions as Advanced / legacy usage. 🤔
> 🐛  Add addon-actions back in

- libraries/core-react/src/components/Button/Button.tsx
- libraries/core-react/stories/components/Button.stories.tsx
resolves #992 
Tried solutions:
* Different CSS Grid variants using js to place elements in correct areas.
* Different Flex-variants
Not tried:
Having a `prefix/suffix` prop where we can pass a component for rendering icons and progress indicators would be a solution here, but it goes against our component-design philosophy of not passing components/elements as props. 
This was the best solution I could make work, using flexbox:
It works unless you have them full-width and stacked with different directions, its not optimal, but better that today atleast 🤷‍♂️
> Adjustments for elements inside button

- libraries/core-react/src/components/Button/Button.test.tsx
- libraries/core-react/src/components/Button/Button.tsx
fixes #1093 
Inversed operator for when an child gets put in a element inside `Button` since react elements are `objects`,
> 🐛 Fixed centering of content when its not text in Button

- libraries/core-react/stories/components/Menu.stories.tsx
Resolve #1087  
Seems like this is a classic user error. 🤓  I updated the markup used in storybook to something that makes more sense, and is aligned with Figma. As a magical side effect, the height is now 48px. 🥳
> Fix menu height

- libraries/core-react/src/components/Accordion/Accordion.test.tsx
- libraries/core-react/src/components/Accordion/AccordionHeader.tsx
**problem:** 
AccordionItem shadows external toggleExpanded. The internal and external props are mixed.
A common use case is to defer  render of components that are not visible to the user. I many of the inhouse application do have a lot of data and hidden components may be expensive to render. 
**solution:** 
add a new onToggle prop to support toggleExpanded when it's wrapped in AccordionItem. 
#1120
> Fix AccordionHeader toggleExpanded

- libraries/core-react/.storybook/preview.js
- libraries/core-react/src/components/Accordion/Accordion.tokens.ts
- libraries/core-react/src/components/Accordion/AccordionHeader.tsx
- libraries/core-react/src/components/Banner/Banner.test.tsx
- libraries/core-react/src/components/Banner/Banner.tokens.ts
- libraries/core-react/src/components/Banner/Banner.tsx
- libraries/core-react/src/components/Banner/BannerActions.tsx
- libraries/core-react/src/components/Banner/BannerIcon.tsx
- libraries/core-react/src/components/Breadcrumbs/Breadcrumb.tsx
- libraries/core-react/src/components/Breadcrumbs/Breadcrumbs.tokens.ts
- libraries/core-react/src/components/Breadcrumbs/Breadcrumbs.tsx
- libraries/core-react/src/components/Card/Card.test.tsx
- libraries/core-react/src/components/Card/Card.tokens.ts
- libraries/core-react/src/components/Card/Card.tsx
- libraries/core-react/src/components/Card/CardActions.tsx
- libraries/core-react/src/components/Card/CardHeader.tsx
- libraries/core-react/src/components/Card/CardHeaderTitle.tsx
- libraries/core-react/src/components/Card/CardMedia.tsx
- libraries/core-react/src/components/Chip/Chip.test.tsx
- libraries/core-react/src/components/Chip/Chip.tokens.ts
- libraries/core-react/src/components/Chip/Chip.tsx
- libraries/core-react/src/components/Chip/Icon.tsx
- libraries/core-react/stories/components/Breadcrumbs.stories.tsx
- libraries/core-react/stories/testing/GlobalStyles.ts
- libraries/tokens/src/types/component.ts
- libraries/tokens/src/types/index.ts
Part of #1129 
Edit: The initial approach of this PR was to rewrite the React components to use CSS vars. it quickly became evident that it was too difficult. The approach was changed to rewrite the tokens of the components, but that was cumbersome as well. The final approach was to add CSS color variables inside the tokens, see #1137 . 
This PR features some tokens cleanup to make it easier to add CSS vars and a test file for CSS vars used for testing inside Storybook
> Some cleanup for CSS variables

- libraries/core-react/.storybook/main.js
- libraries/core-react/tsconfig.json
For a long time we had typings for test being included in `core-react`. 
Excluded files including `.test` and `.stories` (so its ready for moving story files 👌)
> 🔧  Update config files to exclude test and stories files

- libraries/core-react/src/components/Input/Input.tokens.ts
- libraries/core-react/src/components/Input/Input.tsx
- libraries/core-react/src/components/TextField/Icon/Icon.tsx
- libraries/core-react/src/components/TextField/InputWrapper.tsx
- libraries/core-react/src/components/TextField/TextField.tokens.ts
- libraries/core-react/src/components/TextField/TextField.tsx
- libraries/core-react/src/components/TextField/context.tsx
- libraries/core-react/stories/components/TextField.stories.tsx
- libraries/tokens/src/types/focus.ts
> Support for unit in TextField

- .github/workflows/publish_core_react.yaml
- .github/workflows/publish_icons.yaml
- .github/workflows/publish_tokens.yaml
- libraries/tokens/package.json
fixes #1166 
The problem was due to a cache being used multiple times, expecting it to be updated.  Caches in github actions are fixed once they have been greated. You have to save it under a different key if you want to add new files.
> Fix wrong use of cache in actions

- libraries/core-react/src/components/Search/Search.tokens.ts
- libraries/core-react/src/components/Search/Search.tsx
- libraries/tokens/src/types/clickbound.ts
resolves #1263 
⚠️Needs [fixes to `shorthand` ](https://github.com/equinor/design-system/pull/1283/files#diff-f61f2546a34dd189728cf8f685243e55aaa1b009f7dab9e2fd9af5705dd58375)(used in `borderTemplate`) from #1283
> ♻️ Updated Search tokens

- libraries/core-react/CHANGELOG.md
- libraries/core-react/package.json
- Missing border on "outlined" `Button` ([#1332](https://github.com/equinor/design-system/issues/1332))
> Release core react@0.11.1

- libraries/core-react/src/components/TextField/TextField.stories.tsx
- libraries/core-react/src/components/Textarea/Textarea.tsx
- libraries/core-react/src/hooks/useAutoResize.ts
> Fix rowsMax bug

- libraries/core-react/src/components/Accordion/index.ts
Fixing a typo affecting the Accordion components' displayName property.
> fix: Accordion displayName typo

- libraries/icons/CHANGELOG.md
- libraries/icons/package.json
resolves #1418 
- New icons:
- `power_bi`
- `engineering`
- `boundaries`
- `inspect3d`
- `inspectrotation`
- `invert`
- Updated `svgo` from `1.3.2` to `2.3.0` with new parsing, bundling and minimizing plugins.
> Release of eds-icons@0.7.0

- .gitpod.Dockerfile
- .gitpod.yml
When installing pnpm globablly using npm, it’s not available when the environment is prebuilt. Using a minimal dockerfile with pnpm installed with homebrew will (hopefully) fix the problem.
> 🔨 Keep pnpm after prebuild

- libraries/core-react/src/components/Menu/Menu.test.tsx
- libraries/core-react/src/components/Menu/Menu.tsx
- libraries/core-react/src/components/Menu/__snapshots__/Menu.test.tsx.snap
resolves: #1672 
This will allow users to overwrite styles on an element that is also used by popper to set position via `position`, `inset (top, left, bottom, right)` and `transform`, but I think it's fine, users will quickly realize if they try that..
> ✨Menu: className and style props are put on outermost element

- libraries/core-react/src/components/Menu/MenuList.tsx
Resolves #1668 
The internal logic to add indexes to focusable children and then make them focusable with keyboard did not work at all with menuSections present. 
I have changed the code now to add index to menuItems inside sections, as well as menuItems that are not in sections. I then  made a separate flat array of children to build the focusableIndexs.
I also added event.preventDefault when pressing up/down arrows inside menu to stop scrolling the viewport.
On a sidenote it does not appear that memo works on menuItems, I guess because of the function props, so there are probably some more optimizations that can be done on this component
> 🐛 Fixed keyboard navigation when menuSection is present

- libraries/core-react/src/components/Menu/Menu.tsx
- libraries/core-react/src/components/Menu/MenuItem.tsx
- libraries/core-react/src/components/Menu/MenuList.tsx
- libraries/core-react/src/components/Menu/MenuSection.tsx
- libraries/core-react/src/components/Menu/__snapshots__/Menu.test.tsx.snap
resolves #1702 
In the menu, we want keyboard 'enter' to behave the same as clicking an item with the mouse. By replacing the `li` element with a `button` element we get this `onClick` behaviour with keyboard for free
> 🐛♻️ Replacing ul>li with div>button fixes keyboard enter-as-click

- libraries/core-react/src/components/Menu/Menu.tsx
> 🚸 Menu: Return focus to anchor after escape/enter keypress

- libraries/core-react/src/components/Table/Cell.tsx
- libraries/core-react/src/components/Table/DataCell/DataCell.tsx
- libraries/core-react/src/components/Table/HeaderCell/HeaderCell.tsx
resolves #1739 
`HTMLTableDataCellElement` and `HTMLTableHeaderCellElement` are deprecated.
According to MDN docs. the new DOM interface is `HTMLTableCellElement`, for manipulating the layout and presentation of table cells, either header or data cells, in an HTML document.
> 🐛 Cell, DataCell: fix deprecated DOM intefrace

- libraries/core-react/CHANGELOG.md
- libraries/core-react/package.json
resolves #1700 
- New sub-component `Card.Content` for content inside `Card`. ([#1711](https://github.com/equinor/design-system/issues/1711))
- Adjusted `Topbar.Actions` to vertically align elements. ([#1680](https://github.com/equinor/design-system/issues/1680))
- Adjusted `Card.Media` spacings. ([#1713](https://github.com/equinor/design-system/issues/1713))
- `Menu.Item` focus should no longer jump after being re-opened. ([#1681](https://github.com/equinor/design-system/issues/1681))
- Keyboard interaction in `Menu` should now work as intended. ([#1702](https://github.com/equinor/design-system/issues/1702))
- Focus should now return to anchor when `Menu` is closed by esc/enter. ([#1704](https://github.com/equinor/design-system/issues/1704))
- Replaced deprecated …
> 🔖 Release eds-core-react@0.15.0

- libraries/core-react/CHANGELOG.md
- libraries/core-react/package.json
Resolves #1724 
- Esm package is now unbundled enabling tree-shaking ([#1043](https://github.com/equinor/design-system/issues/1043))
- Adjusted `browserslist` to `defaults, not IE 11` resulting in less babel transpiled code and polyfill bloat ([#1043](https://github.com/equinor/design-system/issues/1043))
- Native support for `focus-visible` (enables focus-ring on elements when using `TAB` key). [Browser support](https://caniuse.com/?search=focus-visible) ([#1043](https://github.com/equinor/design-system/issues/1043))
- Removed umd package from build. ([#1043](https://github.com/equinor/design-system/issues/1043))
- Removed [focus-visible polyfill](https://github.com/WICG/focus-visible), while still retaining support for it in the components. Users who need to support focus-visible in …
> 🔖 Release eds-core-react@0.16.0

- libraries/icons/CHANGELOG.md
- libraries/icons/package.json
resolves #1789 
New icons ([#1743](https://github.com/equinor/design-system/issues/1743)) ([#1581](https://github.com/equinor/design-system/issues/1581)) ([#1734](https://github.com/equinor/design-system/issues/1734))
- `ducting`
- `electrical`
- `fault`
- `formula`
- `go_to`
- `grid_layer`
- `grid_layers`
- `heat_trace`
- `hill_shading`
- `instrument`
- `junction_box`
- `line`
- `log_in`
- `log_out`
- `manual_valve`
- `miniplayer_fullscreen`
- `miniplayer`
- `pipe_support`
- `surface_layer`
- `tag_main_equipment`
- `tag_more`
- `tag_relations`
- `tag_special_equipment`
- `telecom`
- `thumb_pin`
- `well`
- `launch` (should no longer be confused with `external_link` icon) ([#1742](https://github.com/equinor/design-system/issues/1742))
- Renamed `inspectrotation` to `inspect_rotation` …
> 🔖 Release eds-icons@0.9.0

- libraries/core-react/jest.config.js
- libraries/core-react/package.json
- libraries/core-react/pnpm-lock.yaml
- libraries/core-react/rollup.config.js
- libraries/core-react/src/test/__mocks__/styleMock.js
Resolves #1690 
Tested by adding a test.css file with a class selector (to set background-color) in a component and importing it, and using the className in the component.
Tested Jest on the component to make sure snapshot fails but otherwise no other error messages
Tested import css from node_modules by temporarily installing react-datepicker and importing its css into a component
Tested building. this results in a core-react.cjs.css file in /dist and a bundle.css file in /dist/esm
Edit:
Tested pnpm pack and using this in a create-react-app, and it seems you need to add
`import '@equinor/eds-core-react/dist/esm/bundle.css'`
for the css to be inlcuded
> ✨Support css import

- libraries/icons/CHANGELOG.md
- libraries/icons/package.json
- Missing vector on `fault` icon ([#1793](https://github.com/equinor/design-system/issues/1793))
> 🔖 Release eds-icons@0.9.1

- libraries/core-react/src/components/Accordion/Accordion.stories.tsx
- libraries/core-react/src/components/Banner/Banner.stories.tsx
- libraries/core-react/src/components/Button/Button.stories.tsx
- libraries/core-react/src/components/Checkbox/Checkbox.stories.tsx
- libraries/core-react/src/components/Dialog/Dialog.stories.tsx
- libraries/core-react/src/components/Input/Input.stories.tsx
- libraries/core-react/src/components/Menu/Menu.stories.tsx
- libraries/core-react/src/components/Popover/Popover.stories.tsx
- libraries/core-react/src/components/Radio/Radio.stories.tsx
- libraries/core-react/src/components/Search/Search.stories.tsx
- libraries/core-react/src/components/Select/MultiSelect/MultiSelect.stories.tsx
- libraries/core-react/src/components/Select/NativeSelect/NativeSelect.stories.tsx
- libraries/core-react/src/components/Select/SingleSelect/SingleSelect.stories.tsx
- libraries/core-react/src/components/Snackbar/Snackbar.stories.tsx
- libraries/core-react/src/components/Switch/Switch.stories.tsx
- libraries/core-react/src/components/TableOfContents/TableOfContents.stories.tsx
- libraries/core-react/src/components/Tabs/Tabs.stories.tsx
- libraries/core-react/src/components/TextField/TextField.stories.tsx
- libraries/core-react/src/components/TopBar/TopBar.stories.tsx
Split things up a bit. This pr is just about fixing stories with direct usage of compact as density value. Also added missing descriptions to some of the stories and fixed some typos along the way.
Resolves #1707
> 🩹 Don’t use density prop (cleaned up)

- libraries/core-react/src/components/Table/HeaderCell/HeaderCell.tsx
- libraries/core-react/src/components/Table/Table.stories.tsx
resolves #1816
To test, replace content of Table.Cell  with  buttons in the FixedTableHeader story
> 🐛 Make sure table header is on top of content when sticky

- libraries/core-react/src/components/TextField/Field.tsx
- libraries/core-react/src/components/TextField/TextField.tsx
resolves #1145 
Screenreader should now read the helpertext
I implemented aria-invalid when variant="error"
> ♿️ textfield a11y improvements

- libraries/core-react/src/components/Scrim/Scrim.stories.tsx
- libraries/core-react/src/components/Scrim/Scrim.test.tsx
- libraries/core-react/src/components/Scrim/Scrim.tsx
- libraries/core-react/src/components/Scrim/__snapshots__/Scrim.test.tsx.snap
- libraries/core-react/src/hooks/useHideBodyScroll.ts
resolves #1176 
This introduces breaking changes to scrim:
Use `open` prop to align Scrim open/close logic with other components. It now hides itself (with `display: none` and not rendering children)  (breaking)
Removed the second argument (`open`) in onClose (breaking)
The useHideBodyScroll hook is changed to take a boolean that is watched to determine when to hide scroll (since the Scrim is not neccessarily fully unmounted when closed now)
> 💥Conform Scrim open logic

- libraries/core-react/CHANGELOG.md
- libraries/core-react/package.json
resolves #1829 
- `Scrim` is now controlled via an `open` property. ([#1176](https://github.com/equinor/design-system/issues/1176))
- Improvements to `Menu` & `Popover` DOM imprint when closed and subsuquent opennings. ([#1675](https://github.com/equinor/design-system/issues/1675))
- `event` & `open` was removed as parameters to the `onClose` callback for `Scrim`. ([#1176](https://github.com/equinor/design-system/issues/1176))
- `MultiSelect` should now clear properly on blur and clicking clear button. ([#1664](https://github.com/equinor/design-system/issues/1664))
- Improved `TextField` a11y for when error messages are displayed as `helperText`. ([#1145](https://github.com/equinor/design-system/issues/1145))
- `Button` in tables should now have proper stacking context for sticky table …
> 🔖 Release eds-core-react@0.17.0

- .vscode/launch.json
- packages/eds-icons/src/data.ts
- packages/eds-icons/src/types.ts
- scripts/figma-broker/actions/createAssets.js
- scripts/figma-broker/files/assets/icon.js
- scripts/figma-broker/functions/figma.js
- scripts/figma-broker/functions/file.js
resolves #1826 
New IconData used in `eds-icons` looks something like this for icons with `small` icons: 
```tsx
export const fullscreen: IconData = {
name: 'fullscreen',
prefix: 'eds',
height: '24',
width: '24',
svgPathData:
'M7 10H5V5h5v2H7v3zm-2 4h2v3h3v2H5v-5zm12 3h-3v2h5v-5h-2v3zM14 7V5h5v5h-2V7h-3z',
sizes: {
small: {
name: 'fullscreen_small',
prefix: 'eds',
height: '18',
width: '18',
svgPathData:
'M5 7H3V3h4v2H5v2zm-2 4h2v2h2v2H3v-4zm10 2h-2v2h4v-4h-2v2zm-2-8V3h4v4h-2V5h-2z',
},
},
}
```
Lets see how this format feels and revise it again in #1827.
Did not update the svg files, as I would like a separate issue for that as we already have a lot of changes in this PR. For now they will be exported as separate files with `_small` ending. Like so: `fullscreen_small`. Follow up #1885
> ✨Figma-broker export small icons

- packages/eds-lab-react/src/components/Combobox/Combobox.stories.tsx
- packages/eds-lab-react/src/components/Combobox/Combobox.tsx
- packages/eds-lab-react/src/components/Combobox/__snapshots__/Combobox.test.tsx.snap
fixes #1913 
* Introduced use of react portal & popper for placement. 
* Due to using popper, options width now scales based on content.
* ~~This can be fixed in #1004 after #1848, as changes in `usePopper` hook are needed~~
* Edit: We decided that this will be the default behaviour now and if requested add feature for toggling this later. Decided on PR-review meet 01.02.2022
> 🐛 Fix Combobox dropdown layering

- packages/eds-core-react/src/components/Menu/MenuItem.tsx
resolves #1932 
Use raf to delay focus by one frame so transform values from popper take hold
> 🐛 menu: fix unwanted viewport scroll when kb-navigation

- packages/eds-core-react/stories/playground/DataTable.tsx
> Add keyboard navigation

- packages/eds-lab-react/src/components/Combobox/Combobox.stories.tsx
- packages/eds-lab-react/src/components/Combobox/Combobox.test.tsx
- packages/eds-lab-react/src/components/Combobox/Combobox.tsx
After started working on #1657 it would be better to use a option callback function instead of object prop for declaring an option as disabled. This will better tie in with upcoming feature #1657 and option labeling also being callback functions.
> ♻️ Change disabled option feature for Combobox

- packages/eds-core-react/src/components/Tabs/Tab.tsx
- packages/eds-core-react/src/components/Tabs/TabList.tsx
- packages/eds-core-react/src/components/Tabs/Tabs.context.ts
- packages/eds-core-react/src/components/Tabs/Tabs.stories.tsx
- packages/eds-core-react/src/components/Tabs/Tabs.tokens.ts
- packages/eds-core-react/src/components/Tabs/Tabs.tsx
resolves #1650 
- Added `scrollable` prop to add `overflow-x: auto` on Tabs.List (default its `overflow-x: hidden`
- added `scroll-snap` properties to Tabs.List and tabs.Tab, so that next/prev buttons can be more easily implemented by just using `element.scrollTo`.
- Fixed an internal focus issue that prevented clicking on tabs when active tab has been scrolled out of view (the event listener state juggling might be a bridge too far though,  hehe).
- Added a story showing how to add prev/next buttons on an overflowing Tabs list.
- Added a story with `scrollable` on an overflowing Tabs list.
- Added a story with scrollable on an overflowing Tabs list with custom styled scrollbar (for the sake of the pull request and discussion, I guess we might just go for one solution and delete the …
> ✨ Enable Tabs horizontal overflow

- .github/workflows/publish_core_react.yaml
- packages/eds-core-react/package.json
- packages/eds-utils/package.json
resolves #1949 
Suggest keeping the -dev version names as its the latest versions that are published under the `next` tag which is what is in development
> 👷‍♂️ Working published core-react with eds-utils

- packages/eds-core-react/src/components/Menu/MenuList.tsx
fixes #2015
* Fixed crash in `Menu` when using conditional rendering on `Menu.Item`
* Fixed divider not hiding in `Menu.Section` when first.
> 🐛 Fixes in Menu.Item & Menu.Section

- packages/eds-utils/src/hooks/useOutsideClick.ts
this is not a bug, not a feature, but typescript type mismatch. 
eslint complains about wrong type
> Fixes useOutsideClick type

- packages/eds-core-react/src/components/Menu/Menu.context.tsx
- packages/eds-core-react/src/components/Menu/Menu.stories.tsx
- packages/eds-core-react/src/components/Menu/Menu.test.tsx
- packages/eds-core-react/src/components/Menu/Menu.tsx
- packages/eds-core-react/src/components/Menu/MenuList.tsx
- packages/eds-core-react/stories/playground/DataTable.tsx
- packages/eds-core-react/stories/playground/Examples.stories.tsx
Resolves #1936 
Make keyhandling of anchor internal (open and move focus to menu after pressing `enter`/`keyUp`/`keyDown`).
Adds eventlistener to the anchor for the keypresses, so a new requirement for developers now is to use `useState` to set the `anchorEl` ref. Previously in our examples we used useRef, but this will not trigger rerender to add listener when ref switches from null to the actual element
> 🧑‍💻Menu anchor handle keypress internal

- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/package.json
- packages/eds-utils/CHANGELOG.md
- packages/eds-utils/package.json
resolves #2119 
- `Menu` now supports keyhandling on anchor element for open & focus on `Enter`/`ArrowUp`/`ArrowDown` ([#1936](https://github.com/equinor/design-system/issues/1936))
- Users now need to store anchor element in `useState` for correct re-renders & listening events
- 
- `Menu` no longer has `focus` property as focus is now handled internally ([#1936](https://github.com/equinor/design-system/issues/1936))
- 
- Adjustments to focus outline visibility ([#1733](https://github.com/equinor/design-system/issues/1733))
- `Menu` should no longer crash when using conditional rendering inside on children such as `Menu.Item` or `Menu.Section` ([#2015](https://github.com/equinor/design-system/issues/2015))
- Hide top divider when `Menu.Section` is first child in `Menu` …
> 🔖  Release eds-core-react@0.19.0

- packages/eds-core-react/src/components/Search/Search.tsx
- packages/eds-core-react/src/components/Search/__snapshots__/Search.test.tsx.snap
> 💄 Search: Override Chrome autofill background

- packages/eds-core-react/src/components/Slider/Slider.test.tsx
- packages/eds-core-react/src/components/Slider/Slider.tsx
- packages/eds-core-react/src/components/Slider/__snapshots__/Slider.test.tsx.snap
resolves #2167 
- Added` aria-valuemin/max/now` (handled internally since these should be same as min/max/value anyway)
- Internally  set `aria-valuetext` with `getFormattedText`, which returns the return of `outputFunction`-prop, or raw value
- use `useId` instead of `ariaLabelledby` to construct internal ids
- Made `ariaLabelledby` optional with a deprecation warning log if used, and added support for native `aria-labelledby`
> ♿️ Slider a11y improvements

- packages/eds-core-react/src/components/Card/Card.stories.tsx
- packages/eds-core-react/src/components/Card/Card.tsx
- packages/eds-core-react/src/components/Card/CardActions.tsx
- packages/eds-core-react/src/components/Card/__snapshots__/Card.test.tsx.snap
resolves #2248 
Card can now be stretched when in a grid, this was not possible before due to height: fit-content. 
Card is now a flex column, with margin-top: auto on card.actions to push it down in the case where card is stretched. This means having multiple actions will kind of break the layout by evenly spacing the actions though, so users should have only one actions at the bottom (and just make a new styled div for rows inside content)
> 💄Card: changed to flex column, removed height, actions pushed down

- packages/eds-core-react/src/components/TextField/TextField.stories.tsx
resolves #2146 
Turns out it wasn't a bug, per se, someone set style="200px" on the textfield, but style goes into  ...rest goes into the input and setting width on the input is wrong. It would have to be set on the outermost element wrapping both input and adornments to work. Fixed by making a div around the input in the story and set width on that. 
Also removed double edsprovider
> 🐛 Fix textfield compact story

- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/package.json
- packages/eds-core-react/src/components/Select/MultiSelect/MultiSelect.tsx
- packages/eds-core-react/src/components/Select/SingleSelect/SingleSelect.tsx
- packages/eds-utils/CHANGELOG.md
- packages/eds-utils/package.json
#2238
IDE preview of deprecated components 
- New component! 🎉 `Autocomplete` has been moved from our labs to core! ([#2201](https://github.com/equinor/design-system/pull/2201))
- This is a new component based on feedback from `MultiSelect` & `SingleSelect` aimed resolving their shortcomings, complexity and improve further development
- Improved `Progress` legibility ([#2182](https://github.com/equinor/design-system/pull/2182))
- `Card` is now less opinonated making it easier to use inside flex/grid containers ([#2273](https://github.com/equinor/design-system/pull/2273))
- Upgraded dev dependencies, fixed missing types in Slider & removed `Menu.Item` memo as it was not working as intended ([#2183](https://github.com/equinor/design-system/pull/2183))
- `MultiSelect` has been deprecated in …
> 🔖 Release eds-core-react@0.20.0 & eds-utils@0.2.2

- packages/eds-core-react/src/components/Slider/Slider.tsx
Replaced `console.warn` with `@deprecated` annotation.
> ♻️  Reduce property deprecation warning intensity for Slider

- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/package.json
- `ariaLabelledby` has been deprecated on `Slider`. Use `aria-labelledby` instead. ([#2173](https://github.com/equinor/design-system/pull/2173))
> 🔖 Release eds-core-react@0.20.1

- packages/eds-tokens/CHANGELOG.md
- packages/eds-tokens/package.json
resolves #2238 
- Upgraded dev dependencies([#2183](https://github.com/equinor/design-system/pull/2183))
> 🔖  Release eds-tokens@0.7.1

- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
resolves #2295 
basicaly the same solution as on menu, except here i also have to trigger popper for one frame after load so menu is positioned correctly first time you open it
> ⚡️ Autocomplete: disable popper when closed

- packages/eds-core-react/src/components/Autocomplete/Autocomplete.docs.mdx
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.stories.tsx
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
> 🐛 Fix Autocomplete onOptionsChange not always firing

- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/package.json
resolves #2314 
Added dev-version flag for testing before release.
Current changelog:
- `Accordion` now has a new sub-component; `Accordion.HeaderActions`! This should make it easier to have interactive elements in the `Accordion.Header` while maintaining proper a11y. ([#2091](https://github.com/equinor/design-system/pull/2091))
- `Autocomplete`
- Should no longer trigger re-renders when closed. ([#2295](https://github.com/equinor/design-system/pull/2295))
- Should now correctly update if options are changed after initialization. ([#2304](https://github.com/equinor/design-system/pull/2304))
- `onOptionsChange` should now properly trigger when controlled in single select mode. ([#2300](https://github.com/equinor/design-system/pull/2300))
- Bumped dropdown `z-index` to match other EDS …
> 🔖 Release eds-core-react@0.20.2

- packages/eds-core-react/src/components/Tabs/Tab.tsx
- packages/eds-core-react/src/components/Tabs/TabPanel.tsx
- packages/eds-core-react/src/components/Tabs/Tabs.stories.tsx
- packages/eds-core-react/src/components/Tabs/Tabs.tokens.ts
> 🐛  typographyTemplate in Tab

- packages/eds-core-react/src/components/Banner/Banner.stories.tsx
- packages/eds-core-react/src/components/Banner/Banner.tsx
- packages/eds-core-react/src/components/Banner/__snapshots__/Banner.test.tsx.snap
- packages/eds-core-react/src/components/Card/Card.tsx
- packages/eds-core-react/src/components/Card/__snapshots__/Card.test.tsx.snap
- packages/eds-core-react/src/components/Dialog/__snapshots__/Dialog.test.tsx.snap
- packages/eds-core-react/src/components/Paper/Paper.tokens.tsx
- packages/eds-core-react/src/components/Paper/Paper.tsx
- packages/eds-core-react/src/components/Paper/index.ts
- packages/eds-core-react/src/components/Popover/__snapshots__/Popover.test.tsx.snap
- packages/eds-core-react/src/components/Snackbar/__snapshots__/Snackbar.test.tsx.snap
- packages/eds-core-react/src/components/TopBar/TopBar.stories.tsx
- packages/eds-core-react/src/components/TopBar/TopBar.tsx
resolves #2230 
as per design directives, the allowed elevations are: 
TopBar: none, raised
Banner: none, raised, overlay
Card: none, raised, overlay 
This pr also removes max/min width on Paper
> ✨ elevation options to Card/Banner/TopBar

- packages/eds-core-react/package.json
- packages/eds-core-react/src/components/Menu/Menu.stories.tsx
- packages/eds-core-react/tsconfig.build.json
- packages/eds-core-react/tsconfig.json
- packages/eds-lab-react/package.json
- packages/eds-lab-react/tsconfig.build.json
- packages/eds-lab-react/tsconfig.json
- packages/eds-utils/package.json
- packages/eds-utils/tsconfig.build.json
- packages/eds-utils/tsconfig.json
resolves #2318 
Seems like this also finally fixed the mdx import problem in stories.
Build output is identical to before with these changes, but now vscode uses tsconfig when evaluation stories and test files
> 🔧 Dedicated tsconfig for build w exclude paths

- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/package.json
- packages/eds-utils/CHANGELOG.md
- packages/eds-utils/package.json
- 📝 App launcher documentation by @martalalik in https://github.com/equinor/design-system/pull/2303
- ⬆️ Upgrade popperjs dependencies by @mimarz in https://github.com/equinor/design-system/pull/2347
- 🐛 Using `Icon` `data` should work properly if `size` is not defined by @mimarz in https://github.com/equinor/design-system/pull/2327
- 🐛 Fixed `TextField` `style` prop being sent container and inner input by @mimarz in https://github.com/equinor/design-system/pull/2337
- 🐛 Fixed `Autocomplete` `onOptionsChange` when not controlled & cleaned up react hooks form example by @mimarz in https://github.com/equinor/design-system/pull/2335
> 🔖  Release eds-core-react@0.20.4

- packages/eds-core-react/src/components/Button/Button.docs.mdx
- packages/eds-core-react/src/components/Button/Button.stories.tsx
- packages/eds-core-react/src/components/Button/Button.tsx
- packages/eds-core-react/src/components/Button/Button.types.ts
- packages/eds-core-react/src/components/Button/tokens/contained_icon.ts
- packages/eds-core-react/src/components/Button/tokens/index.ts
resolves #2340 
- Updated docs to reflect new `Button` icon variant
- Updated docs to streamline `a11y` to use `aria-label` for icon buttons instead of title on icon
The size for icon buttons ghost & contained are to big (48px vs 40px), this is due to wrong value in shape token. This will be fixed from Figma and new tokens will need to be exported to fix this.
> ✨ Added `contained_icon` variant to Button

- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
In some situations it would be preferable to hide the clear button, e.g. when a field has a default and can never be null.
This PR adds a simple hideClearButton prop that is added onto the "showClearButton" computed bool.
Resolves #2383
> feat(autocomplete): add disable clear button prop

- packages/eds-core-react/src/components/Menu/Menu.test.tsx
- packages/eds-core-react/src/components/Menu/Menu.tsx
resolves #2343 
further improvements can be done by letting floating-ui handle keyboard navigation and add support for nested menus with `FloatingTree` but this is a larger undertaking to be handled by separate tickets 
Like with popover, it is unclear to me why the menu is hidden with visibility, but i am leaving it be
> ♻️ menu: replace popper with floating-UI

- packages/eds-core-react/src/components/Button/Button.docs.mdx
- packages/eds-core-react/src/components/Button/Button.stories.tsx
- packages/eds-core-react/src/components/Button/Button.test.tsx
- packages/eds-core-react/src/components/Button/Button.tsx
- packages/eds-core-react/src/components/Button/__snapshots__/Button.test.tsx.snap
- packages/eds-core-react/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
- packages/eds-core-react/src/components/Search/__snapshots__/Search.test.tsx.snap
- packages/eds-core-react/src/components/Select/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
- packages/eds-core-react/src/components/Select/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap
- packages/eds-core-react/src/components/SideSheet/__snapshots__/SideSheet.test.tsx.snap
- packages/eds-utils/src/utils/index.ts
- packages/eds-utils/src/utils/overridableComponent.ts
resolves #2338 (perhaps)
This solution does seem to work with button, although you need to set `as="a"` explicitly, as just setting `href`, which converts it to an `a` internally, is not picked up by typescript so adding `target` attribute gets an error in that case.
This pr also fixes a bug i came across where height of button is 36px when as=button, 38px when other things due to different default box-sizing. So i added explicit box-sizing: border-box to force always 36px
> ✨Overrideable component spike

- packages/eds-core-react/src/components/Dialog/DialogHeader.tsx
- packages/eds-core-react/src/components/Progress/Linear/Linear.stories.tsx
- packages/eds-core-react/src/components/Slider/Slider.stories.tsx
- packages/eds-core-react/src/components/Typography/Typography.docs.mdx
- packages/eds-core-react/src/components/Typography/Typography.stories.tsx
- packages/eds-core-react/src/components/Typography/Typography.tsx
> 📝 Typography documentation 

- .vscode/settings.json
- packages/eds-lab-react/src/components/SideBar/SideBar.stories.tsx
- packages/eds-lab-react/src/components/SideBar/SideBar.test.tsx
- packages/eds-lab-react/src/components/SideBar/SideBar.tokens.ts
- packages/eds-lab-react/src/components/SideBar/SideBar.tsx
- packages/eds-lab-react/src/components/SideBar/SideBarToggle.tsx
resolves #2389 
Topbar padding change have separate issue #2445 
changed width from 66 to 72px when collapsed
removed max-height prop from sidebar,  removed deprecated background color setting from storybook argstable
> 💄 Sidebar design conforms

- packages/eds-core-react/src/components/Menu/Menu.tsx
- packages/eds-core-react/src/components/Popover/Popover.tsx
- packages/eds-core-react/src/components/Popover/__snapshots__/Popover.test.tsx.snap
resolves #2493 
Is this solution ok? I don't know why it was hidden with visibility. I'm guessing perhaps a concern for lag with conditional rendering large menus? Otherwise we can do that also instead of display none
Edit: fixed the same issue with popover although here overflow happens on the container element since popover is not portalized
> 🐛 hide closed menu with display: none

- packages/eds-icons/package.json
- packages/eds-icons/pnpm-lock.yaml
- packages/eds-icons/rollup.config.js
- packages/eds-tokens/package.json
- packages/eds-tokens/pnpm-lock.yaml
- packages/eds-tokens/rollup.config.js
resolves #2376 
Turns out `rollup-plugin-size-snapshot` had dependencies to outdated webpack 4x which caused errors. This is just a fix so it works now. Added new issue to update remaining packages with new rollup config using babel for transpiling all code, #2499
> 💚 Fix build errors node was higher than v16.x

- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
resolves #2502 
Also tested menu inside popover but it works fine (they have same z-index)
> 🐛autocomplete: same zindex as tooltip

- packages/eds-core-react/src/components/TopBar/TopBar.tsx
- packages/eds-core-react/src/components/TopBar/__snapshots__/TopBar.test.tsx.snap
> ✨ Add sticky prop to Topbar

- packages/eds-core-react/src/components/Banner/__snapshots__/Banner.test.tsx.snap
- packages/eds-core-react/src/components/Divider/Divider.tokens.ts
- packages/eds-core-react/src/components/Divider/Divider.tsx
- packages/eds-core-react/src/components/Divider/__snapshots__/Divider.test.tsx.snap
resolves #2515 
There was some elaborate functional code to subtract divider height from margin bottom. I am not sure why it is important the total height of the divider + margins remain the same (perhaps so the total remains divisable by 8?). Regardless I reimplemented it in 1 line of css.
Should the prop name be `thickness` or `size`, like mantine? I feel like `thickness` is less ambigous since the` variant` changes margins and therefore total size as well
Also this component does not support compact yet but I imagine this might be needed at some point
> ✨Divider thickness option

- packages/eds-lab-react/src/components/SideBar/SidebarLink/index.tsx
resolves #2529 
Turns out extending an overridable component (Button) inside another overridable component (SideBar.Link) does not work very well when overriding, and adds the props as html attrs onto the final component. But I realized it is pointless to extend Button here anyway, so I removed it and just use an `a` element as base.
> 🐛Sidebar link active warning

- packages/eds-core-react/src/components/Breadcrumbs/Breadcrumb.tsx
- packages/eds-core-react/src/components/Typography/Typography.tsx
resolves #2538 
Now casting breadcrumb `as={Link}` from react router will not throw warnings about maxWidth being applied to a dom element
> 🐛 Breadcrumb/Typography: use transient props

- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/package.json
- packages/eds-lab-react/CHANGELOG.md
- packages/eds-lab-react/package.json
- packages/eds-utils/CHANGELOG.md
- packages/eds-utils/package.json
resolves #2534 
- 🐛 Accordion: fixed shrinking icon by @oddvernes in https://github.com/equinor/design-system/pull/2540
- ⬆️ Upgrade to React 18 by @mimarz in https://github.com/equinor/design-system/pull/2510
- 🐛 Breadcrumb/Typography: use transient props by @oddvernes in https://github.com/equinor/design-system/pull/2542
- ⬆️ Upgrade to React 18 by @mimarz in https://github.com/equinor/design-system/pull/2510
- 🐛Sidebar link active warning by @oddvernes in https://github.com/equinor/design-system/pull/2531
- ⬆️ Upgrade to React 18 by @mimarz in https://github.com/equinor/design-system/pull/2510
> 🔖 Release core@0.23.0, lab@0.5.0 & utils@0.4.0

- packages/eds-core-react/src/components/Autocomplete/Autocomplete.docs.mdx
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.stories.tsx
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
> ✨ Autocomplete: Support for toggling if input is cleared on selection

- packages/eds-core-react/src/components/Accordion/AccordionHeader.tsx
- packages/eds-core-react/src/components/Accordion/__snapshots__/Accordion.test.tsx.snap
resolves #2566 
tested by wrapping a form around one of the stories. Before: it submitted which reloads page. After: it does not submit
> 🐛 Accordion: prevent toggle from submitting form

- packages/eds-icons/commonjs/package.json
- packages/eds-tokens/commonjs/package.json
resolves #2559 
Remove the last of fallback support for commonjs when node had problems figuring out esm vs commonjs modules.
> 🔥 Remove commonjs path for in eds-icons & eds-tokens

- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/package.json
- packages/eds-icons/CHANGELOG.md
- packages/eds-icons/package.json
- packages/eds-lab-react/CHANGELOG.md
- packages/eds-lab-react/package.json
- packages/eds-tokens/CHANGELOG.md
- packages/eds-tokens/package.json
- packages/eds-utils/CHANGELOG.md
- packages/eds-utils/package.json
resolves #2535 
Need to release all packages as they need to be updated with new dependencies for tokens & icons.
Publish order:
- tokens
- icons
- utils
- core-react
- lab-react
> 🔖 Release eds-core-react@0.24.0, eds-icons@0.15.0, eds-lab-react@0.5.0, eds-tokens@0.8.0, eds-utils@0.5.0 

- packages/eds-lab-react/src/components/DatePicker/DatePicker.tsx
resolves #2366 
If a user leaves an empty string as label, the empty span element was positioned differently in firefox vs chrome. This changed the height of the wrapper that the icon was positioned relatively to.
> 🐛Datepicker: fix calendar icon position

- packages/eds-core-react/src/components/Tooltip/Tooltip.tsx
- packages/eds-core-react/src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
> :bug: Tooltip: fix arrow persistence

- packages/eds-core-react/src/components/Tabs/Tabs.stories.tsx
> 🐛 Remove focus from useEffect in Tabs to prevent unwanted scrolling in Storybook

- packages/eds-core-react/src/components/TextField/TextField.tsx
> 🐛 TextField: id sent to inputwrapper was always null

- packages/eds-core-react/package.json
- packages/eds-core-react/pnpm-lock.yaml
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
- packages/eds-core-react/src/components/Select/MultiSelect/MultiSelect.tsx
- packages/eds-core-react/src/components/Select/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
- packages/eds-core-react/src/components/Select/SingleSelect/SingleSelect.tsx
- packages/eds-core-react/src/components/Select/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap
- packages/eds-lab-react/package.json
- packages/eds-lab-react/pnpm-lock.yaml
- packages/eds-lab-react/src/components/TimePicker/TimePicker.tsx
> ⬆️ Upgraded downshift to 7.0.1

- packages/eds-core-react/src/components/SideBar/SideBar.stories.tsx
- packages/eds-core-react/src/components/SideBar/SideBar.tsx
- packages/eds-core-react/src/components/SideBar/SideBarButton/index.tsx
- packages/eds-core-react/src/components/SideBar/SideBarToggle.tsx
- packages/eds-core-react/src/components/SideBar/SidebarLink/index.tsx
resolves #2649 
The ForwardRefExoticComponent type was not needed and made typescript reject adding `ref` to `SideBar.Button` and `SideBar.Toggle`
Also added a `Menu` to the SideBar "with button" story as this is what amplify is doing, and requires the button ref to work
> 🐛 SideBar: fixed button and toggle ref

- packages/eds-core-react/src/components/TextField/TextField.stories.tsx
resolves #2595 
Clicking on the "set object" button for `inputRef` and `textareaRef` in the argstable would crash the page, so I have removed them
> 🐛 TextField: Fix argstable crash in storybook

- packages/eds-core-react/src/components/Slider/Slider.tsx
I spent a bit of time on finding this option, as it was not clear to me that the `outputFunction` processes the current value for display text.
I added a suggested change, but feel free to change it 👍
> Improve docs for Slider outputFunction

- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
when `multiple`: pressing `tab` no longer toggles the focused item selection state as the menu closes
resolves #2675
> 🐛♿️ Autocomplete: change behaviour on inputBlur

- packages/eds-core-react/package.json
- packages/eds-core-react/pnpm-lock.yaml
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.docs.mdx
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.stories.tsx
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tokens.ts
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
- packages/eds-core-react/src/components/Autocomplete/Option.tsx
- packages/eds-core-react/src/components/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
- packages/eds-core-react/src/components/Button/Button.stories.tsx
resolves https://github.com/equinor/design-system/issues/1909
Remains to figure out a musterious error message in storybook and look into if i can make virtualization optional (its a bit decentralized with changes various placed that would need to be toggled)
> ✨ Virtualized autocomplete

- packages/eds-core-react/src/components/Input/Input.docs.mdx
- packages/eds-core-react/src/components/Input/Input.stories.tsx
- packages/eds-core-react/src/components/Input/Input.tsx
- packages/eds-core-react/src/components/Input/__snapshots__/Input.test.tsx.snap
- packages/eds-core-react/src/components/Search/__snapshots__/Search.test.tsx.snap
- packages/eds-core-react/src/components/TextField/__snapshots__/TextField.test.tsx.snap
resolves #2712 
From before, which I did not even realize until I updated snapshots, is that the colors from token are already wrapped in a css-variable with the color as fallback. So technically you can (and some people probably do already) use that. But since that is a core token (`--eds_ui_background__light`) which will most likely change with the new token system, I think it is still better to have a local variable that won't randomly change in the future
> ✨ Input: Added css-variable to override background

- packages/eds-core-react/src/components/Button/Button.docs.mdx
- packages/eds-core-react/src/components/Button/Button.stories.tsx
- packages/eds-core-react/src/components/Tooltip/Tooltip.docs.mdx
- packages/eds-core-react/src/components/Tooltip/Tooltip.stories.tsx
> 📝 Improved documentation on Button

- packages/eds-core-react/src/components/Accordion/AccordionItem.tsx
Setting the onExpandedChange will make the AccordionItem controlled, meaning the expanded state must be handled outside the component
> Added a onExpandedChange prop to AccordionItem

- packages/eds-core-react/src/components/Slider/Output.tsx
- packages/eds-core-react/src/components/Slider/Slider.tsx
- packages/eds-core-react/src/components/Slider/__snapshots__/Slider.test.tsx.snap
resolves #2782 
Decided preventing max and min from crossing was the easiest to implement and least confusing.
When keyboardnavigating, focus seamlessly shifts to the other thumb when they cross. With mouse the thumb stops when reaching equal value to the other thumb.
I also refactored how dynamic styles are injected to significantly improve performance of the slider and made custom props transient.
> 🚸⚡️ Slider: prevent crossing min/max, performance improved

- packages/eds-core-react/src/components/Dialog/DialogHeader.tsx
resolves #2798 
Not sure if moving `...rest` into the inner div is the right call. The problem the reporter of this bug have is setting style on DialogHeader, but it has a surrounding div to contain both the header and `Divider` to prevent an extra gap due to dialog being a grid. 
Normally we: 
1. set ...rest to the outermost element
2. make sure `style` and `className` goes to the same place
But here we would want style to go to the styled component. So either seperate it from classname or be consistent
> 🐛 DialogHeader: fix css syntax errors

- packages/eds-lab-react/src/components/DatePicker/DatePicker.stories.tsx
- packages/eds-lab-react/src/components/DatePicker/DatePicker.tokens.ts
- packages/eds-lab-react/src/components/DatePicker/DatePicker.tsx
- packages/eds-lab-react/src/components/DatePicker/DatePickerSelectHeader.tsx
- packages/eds-lab-react/src/components/DatePicker/SelectHeader.tsx
The DatePicker component has a cumbersome navigation when you have to navigate several years.
- To simplify navigation i've added support for adding a custom header component.
- Forwarded disabled prop to allow disabling of DatePicker
- added min-width 128px to avoid icon overlapping label/text
- added disableAfterDate (considered overriding using a filterDate prop, but kept it in line with existing code instead)
- reworked filterDate to be able to use both disableBeforeDate and disableAfterDate at the same time
- removed the custom label and imported EDS Label
- Added disabled styling
- Forwarded minDate & maxDate
When using disableBeforeDate for a future date, minDate seems like the only way to start picking dates in future without setting a date value
Also use this in our project to …
> react-datepicker: added selects for changing view

- packages/eds-core-react/package.json
- packages/eds-core-react/pnpm-lock.yaml
- packages/eds-lab-react/package.json
- packages/eds-lab-react/pnpm-lock.yaml
- packages/eds-utils/package.json
- packages/eds-utils/pnpm-lock.yaml
resolves #2846 
core-react: 
@babel/runtime            7.20.7 -> 7.21.0
@floating-ui/react         0.19.2 -> 0.23.0
@tanstack/react-virtual 3.0.0-beta.45 -> 3.0.0-beta.54
downshift                      7.2.0 -> 7.6.0
lab-react:
@babel/runtime            7.20.7 -> 7.21.0
downshift                      7.2.0 -> 7.6.0
react-datepicker            4.10.0 -> 4.11.0
utils:
@babel/runtime            7.20.7 -> 7.21.0
babel-jest                      29.3.1 -> 29.5.0
> ⬆️ Update prod dependencies all packages

- packages/eds-core-react/src/components/Autocomplete/Autocomplete.docs.mdx
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.stories.tsx
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.test.tsx
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
- packages/eds-core-react/src/components/Autocomplete/Option.tsx
resolves #2487 
`optionComponent` allows users to provide their own template `(option: T) => ReactNode`
I made a new story and updated the async story with flag pictures in the options
> ✨ Autocomplete optionComponent

- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/package.json
resolves #2859
Patches warning when using menu.item as react-router Link
> 🔖Release eds-core-react@0.31.1

- packages/eds-core-react/src/components/SideBar/SideBar.tsx
resolves #2853 
I propose we visibly hide the scrollbar when sidebar is collapsed. The scrolling is still accessible with mouse scrollwheel or dragging finger on touch screen or tabbing through items on keyboard. this is the solution they have in the slack sidebar (where you click between organizations). Also considering this is a pretty unlikely edge case 🤷‍♂️
> 💄Sidebar: Remove visible scrollbar when closed

- packages/eds-core-react/src/components/Button/ButtonGroup/ButtonGroup.stories.tsx
- packages/eds-core-react/src/components/Menu/Menu.docs.mdx
- packages/eds-core-react/src/components/Menu/Menu.stories.tsx
- packages/eds-core-react/src/components/SideBar/SideBar.stories.tsx
Adds null as possible type for anchor Elements in storybooks documentation.
This does not produce and error in the eds project itself as typescript is not set to strict, but does produce an error in most projects.
The default for most popular react bootstrapping tools like: create-react-app, create-vite and create-next-app default to typescript in strict mode.
> 📝 Storybook: Add null as a possible value for useState hooks that receive HTML elements to avoid type error

- packages/eds-core-react/src/components/Dialog/Dialog.tsx
- packages/eds-core-react/src/components/Tooltip/Tooltip.stories.tsx
When closing a díalog utilizing the floating-ui library the previous focused element is always refocused. This pull-request makes this feature an optional configuration.
> fixed: Issue with refocusing after closing floating dialog

- packages/eds-core-react/src/components/Dialog/Dialog.docs.mdx
- packages/eds-core-react/src/components/Dialog/Dialog.stories.tsx
- packages/eds-core-react/src/components/Dialog/Dialog.test.tsx
- packages/eds-core-react/src/components/Dialog/Dialog.tokens.ts
- packages/eds-core-react/src/components/Dialog/Dialog.tsx
- packages/eds-core-react/src/components/Dialog/__snapshots__/Dialog.test.tsx.snap
- packages/eds-utils/src/hooks/useHideBodyScroll.ts
resolves #2949 
removes `Scrim` and `floating-ui` as dependencies and instead uses a native `<dialog>` element in modal mode (uses `DialogElement.showModal()`)
I kept the functionality the same as the old Dialog to not introduce breaking changes (which means i did block pressing escape to close unless `isDismissable` is true, maybe something to discuss
> ♻️🚸Dialog: refactor to use native dialog

- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/package.json
- packages/eds-core-react/rollup.config.js
- packages/eds-lab-react/jest.config.cjs
resolves #2962 
I think stoybook fixed the issue with modules in one of the dependency updates because now it seems I am able to build and run the storybook using the old and technically incorrect syntax in package.json, which is needed for react 17 users to run core-react
> 🔖Release eds-core-react-0.32.1

- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
> Fixed issue where onFocus and onBlur broke internals of Autocomplete

- packages/eds-core-react/src/components/Dialog/Dialog.tsx
resolves #3002 
I was unable to reproduce this problem in storybook, but was able to do it in downstream app and this fix seems to have resolved it 🤷‍♂️. I don't remember if I added the check (this pr removes) due to a bug or just an assumption that calling showModal multiple times is bad but it doesn't seem like removing it is causing any ill effects 🤞
> 🐛 Dialog: remove check to allow open on mount

- packages/eds-core-react/src/components/Autocomplete/Option.tsx
- packages/eds-core-react/src/components/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
resolves #2889 
This does not fix the problem completely, but at least now it does not crash the component on item click using touch input.
I can still trigger "maximum update depth" infinite loop by selecting items quickly enough with keyboard on multiselect.
It looks to be some sort of race condition inside downshift that the added settimeout mitigates
> 🐛Autocomplete: Added a workaround for touch crash

- packages/eds-core-react/src/components/Checkbox/Input.tsx
- packages/eds-core-react/src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap
- packages/eds-core-react/src/components/Radio/Radio.tsx
- packages/eds-core-react/src/components/Radio/__snapshots__/Radio.test.tsx.snap
- packages/eds-core-react/src/components/Switch/Switch.styles.ts
- packages/eds-core-react/src/components/Switch/__snapshots__/Switch.test.tsx.snap
resolves #3031 
use `isolation: isolate` to create new stacking contexts for these components so their internal z-index doesnt bleed out and make them poke through overlaying html
> 💄Radio/Checbox/Switch z index bug

- packages/eds-core-react/package.json
- packages/eds-core-react/pnpm-lock.yaml
- packages/eds-core-react/src/components/Tabs/Tab.tsx
- packages/eds-core-react/src/components/Tabs/TabList.tsx
- packages/eds-core-react/src/components/Tabs/Tabs.context.ts
- packages/eds-core-react/src/components/Tabs/Tabs.docs.mdx
- packages/eds-core-react/src/components/Tabs/Tabs.stories.tsx
- packages/eds-core-react/src/components/Tabs/Tabs.tsx
resolves #3022 
The feature request was to fix the `active` prop on `<Tabs.Tab>` so it could be used to manually set active tab when using tabs as router links, however this proved difficult due to how the internal logic controls the active state. So instead I opted to implement it the way MUI does it by having a `value` prop on `<Tabs.Tab>` that sets the active tab if it matches the value sent into `activeTab`.
I also created a storybook story with a practical example using `react-router-dom`
> ✨Tabs: controlled mode

- packages/eds-core-react/src/components/Tabs/TabPanels.tsx
- packages/eds-core-react/src/components/Tabs/Tabs.docs.mdx
- packages/eds-core-react/src/components/Tabs/Tabs.stories.tsx
resolves #3040 
Made conditionalRender false by default, restoring the original behaviour
> 🚸 Tabs: make conditionalRender prop for Panels

- packages/eds-core-react/src/components/SideBar/SideBarToggle.tsx
The toggle button causes an accessibility warning for missing text label. Also, without the label the button is hard to find in playwright tests and the like.
> fix(sidebar): add aria-label to toggle button

- packages/eds-core-react/src/components/Table/Row/Row.tsx
> 🐛 Table.Row: fix Styled v6 false positive warning on active prop

- packages/eds-core-react/src/components/Button/Button.docs.mdx
- packages/eds-core-react/src/components/Button/Button.stories.tsx
- packages/eds-core-react/src/components/Button/Button.tsx
> 📝Update button documentation for fullWidth

- packages/eds-core-react/package.json
- packages/eds-core-react/pnpm-lock.yaml
- packages/eds-core-react/src/components/Pagination/Pagination.tsx
- packages/eds-data-grid-react/package.json
- packages/eds-data-grid-react/pnpm-lock.yaml
- packages/eds-icons/package.json
- packages/eds-icons/pnpm-lock.yaml
- packages/eds-lab-react/package.json
- packages/eds-lab-react/pnpm-lock.yaml
- packages/eds-tokens/package.json
- packages/eds-tokens/pnpm-lock.yaml
- packages/eds-utils/package.json
- packages/eds-utils/pnpm-lock.yaml
> ⬆️ Rollup v4.x

- packages/eds-core-react/src/components/Autocomplete/Autocomplete.docs.mdx
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.stories.tsx
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tokens.ts
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
> ✨Added variant and helper-text to Autocomplete

- packages/eds-core-react/src/components/Slider/Output.tsx
- packages/eds-core-react/src/components/Slider/Slider.docs.mdx
- packages/eds-core-react/src/components/Slider/Slider.stories.tsx
- packages/eds-core-react/src/components/Slider/Slider.tokens.ts
- packages/eds-core-react/src/components/Slider/Slider.tsx
- packages/eds-core-react/src/components/Slider/__snapshots__/Slider.test.tsx.snap
resolves #3105 
pending final design review
> 💄 Slider: redesign, labelAlwaysOn prop 

- packages/eds-core-react/src/components/Autocomplete/Autocomplete.test.tsx
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
- packages/eds-core-react/src/components/Label/Label.test.tsx
- packages/eds-core-react/src/components/Label/Label.tsx
- packages/eds-core-react/src/components/TextField/TextField.test.tsx
- packages/eds-core-react/src/components/TextField/TextField.tsx
This allow reactNode to be assigned to the label prop for the Label, TextField and Autocomplete component. This makes it easier to customize the label for a field.
An example of a use case this solves is adding a "required star" to a field in a form
resolves #3141
> feat: allow React Node type for label props to allow it to be more customizable

- packages/eds-core-react/src/components/Slider/Output.tsx
- packages/eds-core-react/src/components/Slider/__snapshots__/Slider.test.tsx.snap
resolves #3119 
the problem was the calculation in` margin-left` of the `output` element. I believe the definition of 100% changes on hover when using safari, causing the calculated value to increase more and more. By making the `output` `position: absolute` it no longer contributes to the width and that fixed it
> 🐛 Slider: fix safari hover bug

- packages/eds-core-react/src/components/Slider/Slider.tsx
resolves #2973 
Made it so range slider works with touch input, and both range and regular slider always shows value label when using touch input. It is a dynamic solution that switches mode based on current input type so it works with devices that has both touch and mouse.
> 📱 Slider: added touch support

- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/package.json
> 🔖 Release eds-core-react@0.34.0

- packages/eds-core-react/src/components/SideSheet/SideSheet.test.tsx
- packages/eds-core-react/src/components/SideSheet/SideSheet.tsx
- packages/eds-core-react/src/components/SideSheet/__snapshots__/SideSheet.test.tsx.snap
resolves #3157 
changes:
- made `open` a required prop
- conditionally render `header` if `title` and/or `onClose` exists
- conditionally render `title`
- conditionally render `close button` if `onClose` is defined
> 🧑‍💻SideSheet: open required, conditional render header, title, button

- packages/eds-data-grid-react/src/EdsDataGrid.docs.mdx
- packages/eds-data-grid-react/src/EdsDataGrid.stories.tsx
- packages/eds-data-grid-react/src/EdsDataGrid.tsx
- packages/eds-data-grid-react/src/EdsDataGridProps.ts
- packages/eds-data-grid-react/src/components/TableBodyCell.tsx
- packages/eds-data-grid-react/src/components/TableHeaderCell.tsx
- packages/eds-data-grid-react/src/stories/columns.tsx
> feat(data-grid): Add column pinning feature

- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
- packages/eds-core-react/src/components/Autocomplete/Option.tsx
- packages/eds-core-react/src/components/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
resolves #3170 
The problem was the scollbar (when `autowith` and `multiline` is not set) cutting off the rightmost part of the label (it steals the content width) in firefox, whereas in chrome etc the scrollbar does not cut but instead adds to the total width.
I have tried a bunch of things to try and coax the scrollbar to behave in firefox as it does in chrome to no avail, so I decided to instead sacrifice the ellipsis by making the label `overflow: clip` in firefox only (so if `autowidth` is true and label is wider than input, it will clip the end insead of showing ellipsis).  I Also made the `scrollbar-width: thin` for firefox so it looks less weird
> 🐛Autocomplete: Firefox scrollbar clipping issue

- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/package.json
- packages/eds-data-grid-react/CHANGELOG.md
- packages/eds-data-grid-react/package.json
- packages/eds-icons/CHANGELOG.md
- packages/eds-icons/package.json
- packages/eds-lab-react/CHANGELOG.md
- packages/eds-lab-react/package.json
resolves #3183 #3184 #3185 
I will also release a patch update for lab-react so its core-react/icons dependencies are up to date
> 🔖Release eds-core-react@0.35.0, eds-icons@0.20.0, eds-data-grid-react@0.2.0

- packages/eds-core-react/src/components/Typography/Typography.tsx
resolves #3192 
This was another one of those random changes in behaviour between styled components v5 and v6
> 🐛 Typography: Fix line clamp bug for styled v6

- packages/eds-core-react/package.json
- packages/eds-core-react/pnpm-lock.yaml
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.stories.tsx
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.test.tsx
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tokens.ts
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
- packages/eds-lab-react/package.json
- packages/eds-lab-react/pnpm-lock.yaml
resolves #3070 
- Input is cleared on blur
- A dropdown with "no options" is shown if a user types in the input and there are no search results
- Added a `noOptionsText` prop with default value "No options" and empty string to force off
This pr also fixes a bug where 
- if multiselect had readOnly set, it was still accessible by clicking in the input (dropdown opens and you can select deselect items)
- `readOnly` on both singleselect and multiselect still accessible by focusing on the input and then pressing up or down arrow  
I had to downgrade downshift to version 8.2.3 due to a bug in multiselect where items can not be toggled unless you move the mouse to another item and then back again. Follow issue at downshift [here](https://github.com/downshift-js/downshift/issues/1566)
> 🚸🐛Autocomplete ux changes/fixes

- .vscode/settings.json
- packages/eds-data-grid-react/package.json
- packages/eds-data-grid-react/src/EdsDataGrid.stories.tsx
- packages/eds-data-grid-react/src/EdsDataGrid.tsx
- packages/eds-data-grid-react/src/EdsDataGridProps.ts
- packages/eds-data-grid-react/src/components/TableBodyCell.tsx
- packages/eds-data-grid-react/src/components/TableHeaderCell.tsx
- packages/eds-data-grid-react/src/components/TableRow.tsx
- packages/eds-data-grid-react/src/index.ts
- packages/eds-data-grid-react/src/tests/EdsDataGrid.test.tsx
- packages/eds-data-grid-react/src/types.ts
resolves #3234 
This pull request introduces the following improvements to the data-grid:
Most of these changes have been discussed with @yusijs.
- ✨ Reexport `@tanstack/react-table` types to ease typing in apps using the data grid
- 📌 Move eds-core-react to peer dependencies
- This is neccessary because EDS uses React Context and the grid and the project should
have the same React instance running. This makes it possible to set EDS Density of the
table above the component.
- ♻️ Move text truncating into default cell to enable overwriting cell content
- This enables custom cells like popover, autocomplete or other cells that overflows the cell itself.
- 🐛 Inherit row background color for pinned cells
- This ensures hover color on the whole row when columns are pinned
- 🐛 Support 100% …
> :sparkles: Improve data grid

- packages/eds-data-grid-react/src/EdsDataGrid.tsx
Setting `width="100%` does not currently work due to the current contain CSS value. Removing the contain attribute from the table wrapper element solves the issue. Setting `contain: strict` for performance reasons can be done per project by nesting classes using `styled-components`.
#3251 
@yusijs
> 🐛 Fix 100% width bug by removing contain strict

- packages/eds-core-react/src/components/Slider/Output.tsx
- packages/eds-core-react/src/components/Slider/Slider.docs.mdx
- packages/eds-core-react/src/components/Slider/Slider.stories.tsx
- packages/eds-core-react/src/components/Slider/Slider.tokens.ts
- packages/eds-core-react/src/components/Slider/Slider.tsx
- packages/eds-core-react/src/components/Slider/__snapshots__/Slider.test.tsx.snap
resolves #3223
Reviewed and approved by design
> 💄Slider: removed arrow & added labelBelow prop

- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/package.json
- packages/eds-lab-react/CHANGELOG.md
- packages/eds-lab-react/package.json
- packages/eds-utils/CHANGELOG.md
- packages/eds-utils/package.json
> 🔖Release eds-core-react@0.36.0, eds-lab-react@0.7.5, eds-utils@0.8.4

- packages/eds-data-grid-react/src/EdsDataGrid.stories.tsx
- packages/eds-data-grid-react/src/EdsDataGrid.tsx
- packages/eds-data-grid-react/src/EdsDataGridProps.ts
- packages/eds-data-grid-react/src/stories/columns.tsx
Closes https://github.com/equinor/design-system/issues/3269
As it is implemented today, the column size is only controlled within the datagrid. This should be possible to control externally from the consuming application, to allow preserving the previous settings.
> Data-grid: Allow controlling size

- packages/eds-data-grid-react/package.json
- packages/eds-data-grid-react/pnpm-lock.yaml
resolves #3266 
Unfortunately pnpm does not seem to support dynamic` "workspace:>=*"` syntax so we'll hardcode it as `"workspace:>=0.36.0"` instead and then update this number manually when there are breaking changes in core-react. We are also puzzled by why "workspace:^" does not work but speculate that maybe due to the leading 0 in 0.36.0
> 📌data-grid: changed core-react peerDependency range

- packages/eds-data-grid-react/CHANGELOG.md
- packages/eds-data-grid-react/package.json
> Release eds-data-grid@0.3.0

- packages/eds-data-grid-react/src/EdsDataGrid.tsx
- packages/eds-data-grid-react/src/EdsDataGridProps.ts
- packages/eds-data-grid-react/src/components/TableBodyCell.tsx
- packages/eds-data-grid-react/src/components/TableHeaderCell.tsx
* Closes #3299 (warning in next.js when spreading key)
* Adds `defaultColumn` prop to allow overriding stuff like size, cells etc
> Fix prop-spreading in datagrid + add defaultColumn prop

- packages/eds-data-grid-react/src/EdsDataGrid.stories.tsx
- packages/eds-data-grid-react/src/EdsDataGrid.tsx
- packages/eds-data-grid-react/src/EdsDataGridProps.ts
> Deprecate virtualHeight

- packages/eds-core-react/src/components/Textarea/Textarea.tsx
resolves #3363 
The problem was clicking and dragging scrollbar with mouse did not work due to rightAdornments element overlapping it.
fixed by adding` pointer-events: none` to rightAdornments for TextArea
> 🐛 TextArea: fix scrollbar being inaccessible

- packages/eds-core-react/src/components/Input/Input.stories.tsx
- packages/eds-core-react/src/components/TextField/TextField.stories.tsx
- packages/eds-core-react/src/components/TextField/TextField.tsx
- packages/eds-core-react/src/components/TextField/__snapshots__/TextField.test.tsx.snap
resolves #3354 
I could not find any other way to make this work then forcing a re-render in `TextField` if `rightAdornments` change
Updated the TextField "with icons" story with a button to toggle icon to demonstrate that it works
> 🐛 TextField: dynamically update padding for icon

- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
resolves #3381 
If there are no options in the Autocomplete, it will show the "no otions" text on focus instead of waiting until the user starts typing
> 🚸 Autocomplete: show "no options" on focus

- packages/eds-core-react/src/components/Datepicker/Datepicker.docs.mdx
Case sensitive path (broken link to code in storybook [DatePicker](https://storybook.eds.equinor.com/?path=/docs/inputs-dates-datepicker--docs))
The convention for other components is using pascal case for names with multiple words. EDS documentation uses two words for this ("[Date/time picker](https://eds.equinor.com/0b0c666ab/v/0/p/07b531-datetime-picker)"), so perhaps a better fix is renaming the folder and files to "Date**P**icker" for consistency.
Edit: eds-lab-react uses pascal case for the [DatePicker](https://github.com/equinor/design-system/tree/develop/packages/eds-lab-react/src/components/DatePicker) component.
> Broken link in Datepicker.docs.mdx

- packages/eds-core-react/src/components/Autocomplete/Autocomplete.test.tsx
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
> 🚸 Autocomplete: implement native popover

- packages/eds-core-react/src/components/Autocomplete/Autocomplete.stories.tsx
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
resolves #3427 
changes
- moved defaultValue of `optionDisabled` to an external const so it does not break useMemo's where it is a dependency
- "select all" now only selects/unselects items that are not disabled
- "clear" button only unselects all selected items that are not disabled
- "x/y selected" text - changed y from "all not disabled items length" to "all items length" (due to the fact that disabled items can still have selected state)
> 🐛 Autocomplete select all: consider disabled items

- packages/eds-core-react/src/components/Datepicker/fields/DateSegment.tsx
I forgot to account for literals/placeholder-values, so it acts a bit... off now.
In latest release:
This fix:
> fix: Datetime-input is formatted with / instead of :

- packages/eds-core-react/src/components/Autocomplete/Autocomplete.stories.tsx
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
> feat(autocomplete): Possible solution for object-checking

- packages/eds-data-grid-react/CHANGELOG.md
- packages/eds-data-grid-react/package.json
> 🔖 Release eds-data-grid-react@0.5.0

- packages/eds-data-grid-react/src/EdsDataGrid.tsx
- packages/eds-data-grid-react/src/EdsDataGridProps.ts
This PR ensures that enableSubRowSelection is disabled by default and can be enabled by passing the optional parameter enableSubRowSelection if needed.
> EdsDataGrid: disable enableSubRowSelection by default

- packages/eds-core-react/package.json
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
resolves #3514, resolves #3493 
removed the conditional type for #3514 and added readonly to options T[] for #3493
> 🐛 Autocomplete: revert 3408 type change + readonly

- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
> 🐛 Autocomplete: handle case all items disabled

- packages/eds-core-react/src/components/Datepicker/DatePicker.tsx
- packages/eds-core-react/src/components/Datepicker/DateRangePicker.tsx
- packages/eds-core-react/src/components/Datepicker/fields/Toggle.tsx
- packages/eds-core-react/src/components/Datepicker/props.ts
also hides clearbutton when no date is set, similar to Autocomplete
resolves #3488
resolves #3492
> ✨Date/Daterange: hideClearButton prop

- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
This pull request improves support for SSR for `Autocomplete` by checking if `typeof document === "undefined"` before attaching `document.body` to `floating-ui`.
This should not change any existing functionality since the code is already checking that document is defined using `?`. `typeof` can be used on the server.
Get this error when our `Next.js` application tries to render an Autocomplete.
Did not manage to reproduce it in CodeSandbox, so it was just as fast creating a PR for it 😄
> :bug: Do not attach document.body if SSR

- packages/eds-core-react/src/components/Icon/Icon.tsx
This pull request improves the type defintion of the `Icon` component by making it a discrimited union on the props `name` and `data`. This makes it so that you have to supplie either as if you the `Icon` ends up crashing and throwing an error
> fix(Icon): improve icon type definition by making it a descriminated union on name and data

- packages/eds-core-react/src/components/Autocomplete/Autocomplete.test.tsx
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
* Adds a bounds check for Autocomplete's findIndex, to prevent infinite recursion once the index has gone beyond bounds.
* Adds test to prevent regression
> Bugfix/add missing bounds check for findIndex

- packages/eds-core-react/src/components/Dialog/Dialog.stories.tsx
- packages/eds-core-react/src/components/Tooltip/Tooltip.stories.tsx
- packages/eds-core-react/src/components/Tooltip/Tooltip.tsx
- packages/eds-core-react/src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
> 💄 Tooltip: implement [popover]

- packages/eds-core-react/src/components/Dialog/Dialog.stories.tsx
- packages/eds-core-react/src/components/Snackbar/Snackbar.test.tsx
- packages/eds-core-react/src/components/Snackbar/Snackbar.tsx
- packages/eds-core-react/src/components/Snackbar/__snapshots__/Snackbar.test.tsx.snap
> 💄 Snackbar: implement [popover]

- packages/eds-core-react/src/components/Tabs/TabList.tsx
This PR fixes a minor issue in the CSS value for the ⁠`scrollbar-width` property in the ⁠`TabList.tsx` component, which resulted in errors being logged in the console of the Firefox Developer Tools. Changing the value to `none` fixes this.
> 🩹 Fix error in parsing value for scrollbar-width

- packages/eds-core-react/src/components/Datepicker/calendars/Calendar.tsx
- packages/eds-core-react/src/components/Datepicker/calendars/CalendarGrid.tsx
- packages/eds-core-react/src/components/Datepicker/calendars/CalendarHeader.tsx
- packages/eds-core-react/src/components/Datepicker/calendars/RangeCalendar.tsx
- packages/eds-core-react/src/components/Datepicker/calendars/YearGrid.tsx
> Add possibility to navigate year picker in calendar

- packages/eds-data-grid-react/src/components/TableHeaderCell.tsx
See https://equinor.slack.com/archives/CJT20H1B9/p1724243461395399
> fix(eds-data-grid-react): Sortindicator should be hidden on custom filters

- packages/eds-core-react/src/components/Select/NativeSelect.test.tsx
- packages/eds-core-react/src/components/Select/NativeSelect.tsx
- packages/eds-core-react/src/components/Select/__snapshots__/NativeSelect.test.tsx.snap
> 🐛 Remove dropdown svg icon when rendering multi-select

- packages/eds-core-react/package.json
- packages/eds-core-react/src/components/Popover/Popover.tsx
> 🐛 blind fix for "disconnected" popover

- packages/eds-core-react/CHANGELOG.md
- packages/eds-core-react/package.json
- packages/eds-data-grid-react/CHANGELOG.md
- packages/eds-data-grid-react/package.json
- pnpm-lock.yaml
> 🔖 Release eds-core-react@0.42.0, eds-data-grid-react@0.7.0

- packages/eds-data-grid-react/src/EdsDataGrid.tsx
- packages/eds-data-grid-react/src/EdsDataGridProps.ts
Like in EDS, we are also using styled components. 
It would be nice to be able to pass the className prop to the root to have more control of the styles.
https://styled-components.com/docs/basics#styling-any-component
> 🎨 Pass className to root

- packages/eds-core-react/src/components/Menu/MenuItem.tsx
When using `Menu` in a form, the form is submitted when clicking on a menu item if `closeMenuOnClcik` is set to false
The problem is a missing `type="button"`.
Looks like this bug has been hiding behind the fact that having it in a form and having `closeMenuOnClick` set to `false` is rare.
The `onClick` callback being called twice when you set `closeMenuOnClick` set to `false` and dont give a `onClose` callback seems to have some have resolved for that instance
> fix: when using menu in a form, the form is submitted

- packages/eds-core-react/src/components/Datepicker/calendars/CalendarCell.tsx
Previously upon opening the calendar current date was focused. Not anymore.
Pressing button Today - does not seem to trigger focus. 
Changing month or focusing manually on other cell - fixes the today button focus.
Issue started after - https://github.com/equinor/design-system/pull/3610
> 🐛 Datepicker doesn't focus on today's cell

- packages/eds-data-grid-react/src/EdsDataGrid.tsx
- packages/eds-data-grid-react/src/EdsDataGridProps.ts
There are a few instances where people want / need to access the `table` instance returned from `useReactTable`, or where certain features that we can't prioritize immediately (for example #3667) is required. By exposing the instance, we allow the consumers to bypass these limitations until we can either address their request, or we still allow them to do whatever they need to do without us having to officially ™️ support it.
Resolves #3586
> feat(data-grid): Expose table-instance via ref

- packages/eds-core-react/src/components/SideBar/SideBar.context.tsx
- packages/eds-core-react/src/components/SideBar/SideBar.tsx
This PR addresses a bug in the sidebar component where setting the `open` state to `true` by default results in an initial layout shift. The component briefly renders as closed before opening, causing an unwanted animation.
The issue stems from using a `useEffect` to sync the internal state with the `open` prop, leading to a mismatch on initial render.
The internal state now defaults directly to the `open` prop, ensuring the sidebar renders correctly without unnecessary transitions.
> fix: fixes issue where sidebar default state always starts as closed

- packages/eds-data-grid-react/src/EdsDataGrid.tsx
> 🎨 Expose ref to Datagrid api

- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
resolves #3677 
For some reason `selectedItems` (returned from `useMultipleSelection` from downshift) contains an array with null (`[null]`) if you have a controlled singleselect and update `selectedOptions` with an empty array from the outside. This then causes the component to crash if `optionDisabled` is defined and tries to read a property from null. I have fixed this by adding an extra null check when creating the `selectedDisabledItemsSet`
> 🐛 Autocomplete: undefined param in optionDiabled

- packages/eds-core-react/src/components/Datepicker/DatePicker.stories.tsx
- packages/eds-core-react/src/components/Datepicker/DateRangePicker.tsx
- packages/eds-core-react/src/components/Datepicker/fields/DateField.tsx
- packages/eds-core-react/src/components/Datepicker/fields/DateFieldSegments.tsx
- packages/eds-core-react/src/components/Datepicker/fields/DateRangeField.tsx
> feat(eds-core-react): :sparkles: use locale prop for text and formats when it is defined

- packages/eds-core-react/src/components/EdsProvider/eds.context.tsx
- packages/eds-core-react/src/components/Tooltip/Tooltip.docs.mdx
- packages/eds-core-react/src/components/Tooltip/Tooltip.stories.tsx
- packages/eds-core-react/src/components/Tooltip/Tooltip.tsx
This is done to allow overriding where the tooltip is rendered, as just using `document.body` can cause issues in certain contexts (e.g style leakage)
> feat(tooltip): Allow defining custom root element for tooltips

- package.json
- packages/eds-core-react/src/components/Accordion/__snapshots__/Accordion.test.tsx.snap
- packages/eds-core-react/src/components/Icon/Icon.tsx
- packages/eds-core-react/src/components/Icon/Icon.types.tsx
- packages/eds-core-react/src/components/Icon/library.ts
- packages/eds-utils/src/hooks/useId.ts
Does two things: 
1. Updates custom `useId` hook to be stable (actually just return an increasing number).
2. Make use of the updated `useId` hook in `Icon.tsx` for title id.
Closes #3705, see that for more details on "why".
> fix: icon id for next.js

- packages/eds-data-grid-react/src/EdsDataGrid.tsx
- packages/eds-data-grid-react/src/EdsDataGridProps.ts
- packages/eds-data-grid-react/src/components/TableRow.tsx
I've added a new event to the EDS Data Grid: `onRowDoubleClick`
It propagates `onDoubleClick` event on the row. Works the same way as `onRowClick` event
> EDS Data Grid Feature: +onRowDoubleClick event

- packages/eds-core-react/package.json
- packages/eds-core-react/src/components/Accordion/index.ts
- packages/eds-core-react/src/components/Banner/index.ts
- packages/eds-core-react/src/components/Breadcrumbs/index.ts
- packages/eds-core-react/src/components/Button/index.ts
- packages/eds-core-react/src/components/Card/index.ts
- packages/eds-core-react/src/components/Dialog/index.ts
- packages/eds-core-react/src/components/List/index.ts
- packages/eds-core-react/src/components/Menu/index.tsx
- packages/eds-core-react/src/components/Popover/index.ts
- packages/eds-core-react/src/components/SideBar/index.ts
- packages/eds-core-react/src/components/Snackbar/index.ts
- packages/eds-core-react/src/components/Table/index.tsx
- packages/eds-core-react/src/components/TableOfContents/index.ts
- packages/eds-core-react/src/components/Tabs/index.ts
- packages/eds-core-react/src/components/TopBar/index.tsx
> 🧱 Export subcomponents individually for ssr support

- packages/eds-core-react/src/components/TextField/TextField.test.tsx
- packages/eds-core-react/src/components/TextField/TextField.tsx
* Allows users to omit creating their own Id for Textfield by falling back to a generated id
> feat: make TextField id optional

- packages/eds-core-react/src/components/Tooltip/Tooltip.tsx
Add `ReactNode` to the `title` prop in the `Tooltip` component.
The title is used directly in the JSX and passing custom components as title seems to work.
Not sure this is intended, up to the EDS team.
> 🏷️ Allow ReactNode as title in Tooltip

- packages/eds-core-react/src/components/Datepicker/fields/DateFieldSegments.tsx
- packages/eds-core-react/src/components/Datepicker/fields/Toggle.tsx
Resolves #3747 
This fixes the misalignment of the calendar icon in `DatePicker` when toggling between disabled and enabled states and ensures the correct font is applied consistently.
- Fixed icon offset: The calendar icon no longer shifts position when enabling `DatePicker` from a disabled state.
- Ensured consistent font-family: The date input now retains the correct font-family after state changes.
- Preserved `Toggle` in the DOM by applying `visibility: hidden` instead of removing it when `disabled={true}`.
- Explicitly set font-family in `DateFieldSegments` to prevent incorrect font inheritance after enabling `DatePicker`.
- Ensured layout stability by maintaining space for `Toggle`, preventing flexbox or grid shifts when re-enabling the component.
The fix has been manually tested …
> 🐛 DatePicker & DateRangePicker: Ensure consistent styling on state changes

- packages/eds-core-react/src/components/Autocomplete/Autocomplete.stories.tsx
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.test.tsx
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
this is yet-another blind fix for issue #3259 - this time, intended to fix an issue where sometimes, downshift doesn't even trigger the onSelectedItemsChange function
> expose itemToKey, add deprecation notice to itemCompare

- packages/eds-core-react/src/components/Autocomplete/Autocomplete.stories.tsx
- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
- packages/eds-core-react/src/components/TextField/TextField.tsx
This pull request addresses an issue with integrating the `Autocomplete` and `TextField` components with `react-hook-form`.
When using these components, `react-hook-form`'s scroll-to-error functionality does not behave correctly. This is because `react-hook-form` expects refs to be attached directly to the underlying `<input>` elements. In the current implementation, the refs are attached to container elements instead, which breaks this behavior.
Refs are now correctly forwarded to the input elements themselves. This ensures that `react-hook-form` can properly detect and scroll to fields with validation errors.
A quick demo has been added to the `Autocomplete` + `react-hook-form` story to help you test and verify the fix.
> fix(Autocomplete, TextField): moves refs from containers to input element to fix scroll to field error with react hook form

- packages/eds-core-react/src/components/Button/Button.tsx
This pr make it so that when a `<Button />` is disabled, it always renders as a native `<button>`, even if it's using a link component like `react-router-dom`'s `<Link>` or `next/link`.
- Most navigation in modern apps uses internal links (`<Link>`) instead of standard `<a>` tags.
- Previously, a `<Button as={Link} disabled />` would still render as a clickable link, which isn’t actually disableable.
- This change ensures disabled buttons behave consistently and aren’t interactive, regardless of how routing is handled.
Helps developers build more accessible apps by ensuring links remain links and disabled buttons behave correctly—no need for workarounds like `useNavigate`.
> fix(eds-core-react): allow button to become disabled when the as prop is used

- packages/eds-tokens-build/package.json
- packages/eds-tokens-sync/package.json
- pnpm-lock.yaml
resolves #3798 
I did not downgrade @babel/runtime as dependabot suggested because it did not seem like it knew the lates version we were on in its description anyway. It thought we were on 7.24.0 but actually we were already on 7.27.1
> chore(eds-tokens-build, eds-tokens-sync): ⬆️ Upgrade dependencies from dependabot

- .github/workflows/checks.yaml
The packages job was failing because it tried to run pnpm commands without first checking out the repository code. This worked previously but broke when triggered directly on develop branch.  (Guilty 😅 ) 
- Add checkout step before cache restore 
- Update pnpm version to 9 
- Remove unnecessary node_modules/.bin/ prefix from pnpm commands
> fix: 👷 Add missing checkout step to packages job

- .github/workflows/publish_core_react.yaml
Resolves #3818 
Storybook changes were taking days to appear after deployment due to incorrect CDN purging (it was only purging artefacts as it was set to default).. 
The `purge-cdn` job was using the default `artefacts` endpoint instead of the `storybook` endpoint, so the storybook CDN cache was never cleared.
- Add explicit `endpoint: storybook` parameter to `purge-cdn` job in the publish core-react workflow
- This ensures storybook CDN cache is purged immediately after deployment
This explains why storybook changes in previous releases took days to appear while npm package changes were immediate
> ci(eds-core-react): 💚 Purge correct CDN endpoint after storybook deployment

- packages/eds-data-grid-react/src/EdsDataGrid.stories.tsx
- packages/eds-data-grid-react/src/EdsDataGrid.tsx
- packages/eds-data-grid-react/src/components/TableHeaderCell.tsx
As the default table-cell doesn't support multiple levels of headers / sticky, I just implemented custom logic to calculate the offset for each row which seems to solve this nicely.
Reported on slack: https://equinor.slack.com/archives/CJT20H1B9/p1749111631826999
> fix(datagrid): Fix sticky-ness of grouped headers

- packages/eds-core-react/src/components/Datepicker/calendars/Calendar.tsx
- packages/eds-core-react/src/components/Datepicker/calendars/CalendarHeader.tsx
- packages/eds-core-react/src/components/Datepicker/calendars/RangeCalendar.tsx
- packages/eds-core-react/src/components/Datepicker/calendars/YearGrid.tsx
- packages/eds-core-react/src/components/Datepicker/utils/getPageYears.ts
This PR resolves an issue in the `DatePicker` where the **back/next buttons** was incorrectly disabled when `min`/`max` values were set.
The disabled state was previously based only on the currently selected **date**, which caused problems in **year selection mode**. Specifically, if the back/next button was disabled and the user navigated to a different years page, they could no longer go back to the previous/next page.
Fixes #3843
Before:
Now:
> fix: Disable back button in year range based on year, not month

- packages/eds-core-react/src/components/Tabs/TabList.tsx
- packages/eds-core-react/src/components/Tabs/TabPanels.tsx
- packages/eds-core-react/src/components/Tabs/Tabs.test.tsx
Null-children will be ignored and removed.
Primary motivation for this is to allow conditional rendering if tabs alongside new [biome](https://biomejs.dev/) linting rule.
We used to the the following to conditionally render tabs:
```
<Tabs>
<Tabs.List>
{someConditional ? <Tabs.Tab>My Tab</Tabs.Tab> : <></>}
</Tabs.List>
<Tabs.Panels>
{someConditional ? <Tabs.Panel>My Panel</Tabs.Panel> : <></>}
</Tabs.Panels>
</Tabs>
```
In the above solution we would render out an empty `<></>` which would work without a problem with EDS Tabs.
The Biome rule https://biomejs.dev/linter/rules/no-useless-fragments/ now consideres the `<></>` to be redundant. Following this new rule we changed our code to the following:
```
<Tabs>
<Tabs.List>
{someConditional && <Tabs.Tab>My Tab</Tabs.Tab>}
</Tabs.List> …
```
> fix: Tabs now allow 'null' value as child element 'Tabs.List' and 'Tabs.Panel'

- packages/eds-core-react/src/components/Table/index.tsx
This pull request changes the exported name of the table row component from `tableRow` to `TableRow` as it was in earlier versions.
> fix(table): export table row with pascal case

- packages/eds-core-react/src/components/Tabs/TabList.tsx
- packages/eds-core-react/src/components/Tabs/Tabs.context.ts
- packages/eds-core-react/src/components/Tabs/Tabs.test.tsx
- packages/eds-core-react/src/components/Tabs/Tabs.tsx
**Before:**  
The `onChange` function in the `Tabs` component always received the selected tab’s index.
**After:**  
`onChange` now receives the tab’s `value` prop if one is provided. If no `value` is set, it will fall back to the tab’s index.
Previously, managing tab state often meant:
- Using “magic numbers” tied to tab order
- Creating a lookup table to map indexes to meaningful values
> feat(eds-core-react): call onChange with provided value if present

- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
This pull request changes the internal behaviour of the `Autocomplete` component so that the `optionLabel` callback is called even though the options are typeof `number` or `string` and not only `object`.
This would allow formatting the label without having to map from/to objects.
> feat: allow option-label prop to be used without type of object

- packages/eds-data-grid-react/src/EdsDataGrid.stories.tsx
- packages/eds-data-grid-react/src/components/ClickableCell/ClickableCell.test.tsx
- packages/eds-data-grid-react/src/components/ClickableCell/ClickableCell.tokens.tsx
- packages/eds-data-grid-react/src/components/ClickableCell/ClickableCell.tsx
- packages/eds-data-grid-react/src/components/ClickableCell/index.ts
This PR introduces a new ClickableCell component that enables interactive cells within the EDS DataGrid, following the design specifications from [Figma Desktop Design](https://www.figma.com/design/luNobpDIWTuQ9rhyovGLBI/Desktop?node-id=5112-91759&t=RrxLyUDIlm1EqiMe-4).
- Accessible clickable cells with proper ARIA labels (required) and button semantics
- Full keyboard navigation support (Enter, Space, Tab)
- Visual feedback states using EDS design tokens
- Seamless DataGrid integration with proper styling coordination
```jsx
const clickableColumns = [
helper.accessor('id', {
header: 'ID',
cell: ({ getValue }) => {
const cellId = `id-${getValue()}`
return (
<ClickableCell
onClick={() => handleCellClick(cellId)}
isSelected={selectedCell === cellId}
ariaLabel={`View details for ID …
```
> feat(eds-data-grid-react): ✨ New `ClickableCell` component

- packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx
This PR fixes a bug where the `onOptionsChange` callback was incorrectly triggered in single-select mode when the "Add new option" button was clicked.
> Don't call onOptionsChange when clicking "Add new"
